### ISSUE TITLE
SQL Query Pool-File

### ISSUE THREAD

**Issue by ace16vitamine** [jokob-sk/NetAlertX#422]
**Is your feature request related to a problem? Please describe.**
database is most of the time locked. It is mostly not possible to edit devices etc.

**Describe the solution you'd like**
Put the SQL Query(s) in a Pool-File and execute it if the DB is free

**Comment by cvc90** [comment]
Hi @ace16vitamine,

Do you use reverse proxy?

**Comment by ace16vitamine** [comment]
No, direct access to the container. Most of the time the DB is locked (actual version (fresh install) and also before).

**Comment by cvc90** [comment]
Could you show me the .conf file or log files, to see in more detail what could be happening?

**Comment by ace16vitamine** [comment]
its not a bug. During scans I receive the message that DB is locked and I can not edit entries. I can wait, no problem, but it is better to store the query in a file (for example if I change the name of a device) and add this later to the db.

**Comment by jokob-sk** [comment]
shelved for later
