### ISSUE TITLE
Better Handling of Plugin Configuration Updates

### ISSUE THREAD

**Issue by jordantrizz** [jokob-sk/NetAlertX#450]
**Is your feature request related to a problem? Please describe.**
When a new version of Pialert contains plugin configuration changes, you have to manually update your pialert.conf

**Describe the solution you'd like**
A process that would check for new configuration fields, and check existing configuration fields such as _CMD _metdata etc.

**Describe alternatives you've considered**
:(

**Additional context**

**Comment by jokob-sk** [comment]
I know, the current way of updating saved configs isn't ideal, I'm already thinking about how to automate this.
