### ISSUE TITLE
[Feedback] Workflows 🦺

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/NetAlertX#562]
Please feedback on the ongoing Workflow development. 

> This is not a promise of delivering on any functionality. This is to get inspirational insights.

1. What use cases would you like to see supported?
2. What triggers are you interested in?
3. What actions are you considering?
4. What configuration options would you like to see?

Thanks a lot,
jokob

**Comment by wild9** [comment]
Looks like potentially a good way of resolving the query I had about ageing off the new device check mark. In an ideal scenario I would be able to automate something along the lines of:  after a scan / on a cron - if a device had a first session date older than xx days remove new device flag.

**Comment by Tharic99** [comment]
Perhaps a value in Settings under either Core or Workflows of:

"Number of Days to Consider a Device as New: "

Then when that X days has passed, the workflow will flip the device off of new.

**Comment by jokob-sk** [comment]
Not much traction -> shelving for now
