### ISSUE TITLE
Remove a device's network node

### ISSUE THREAD

**Issue by ameer1234567890** [jokob-sk/NetAlertX#601]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently, there is no option to remove a device's network node.

### Describe the solution you'd like

An option in the dropdown to select an empty node or a button to remove the node.

### Describe alternatives you've considered

An option in settings 

### Anything else?

None

**Comment by jokob-sk** [comment]
Hi, 

Good point, will work on this, in the mean time you can use the Multi-edit functionality as a workaround:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/383eaf22-e15c-444a-a609-d8d208c352bc)

**Comment by jokob-sk** [comment]
released 🚀 -> closing
