### ISSUE TITLE
Strange Issue in v24.3.19

### ISSUE THREAD

**Issue by ameer1234567890** [jokob-sk/NetAlertX#606]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/Pi.Alert/tree/main/docs

### Current Behavior

When I run [v24.3.19](https://github.com/jokob-sk/Pi.Alert/tree/v24.3.19), the backend seems to run just fine, but I have an issue loading the devices page (home page) of Pi.Alert. Strangely, this issue only happens when trying to load the page over Tailscale (a VPN) and no issue is encountered when loaded within the local network.

To confirm this, I ran the previous version v24.2.17 in a clean install (empty config and db folders) and it works perfectly. When running the new v24.3.19 on a clean install, the issue arises.

When I load the devices page in Chrome, it gives me below errors in console.

```
Setting with key "UI_LANG" not found
GET http://fileserver.tail802a.ts.net:17812/api/table_settings.json?nocache=1711284935269 404 (Not Found)
```

### Expected Behavior

Pi.Alert loading normally in Tailscale as previous versions.

### What branch are you running?

Production

### pialert.log

12:15:05 [MAIN] Setting up ...
12:15:05 [conf.tz] Setting up ...
12:15:05 

12:15:05 The container restarted (started). If this is unexpected check https://bit.ly/PiAlertDebug for troubleshooting tips.
12:15:05 

12:15:05 Permissions check (All should be True)
12:15:05 ------------------------------------------------
12:15:05   /config/pialert.conf |  READ  | True
12:15:05   /config/pialert.conf |  WRITE | True
12:15:05   /db/pialert.db       |  READ  | True
12:15:05   /db/pialert.db       |  WRITE | True
12:15:05 ------------------------------------------------
12:15:05 [Setup] Attempting to fix permissions.
12:15:05 [Setup] Attempting to fix permissions.
12:15:05 [Database] Opening DB
12:15:06 [upgradeDB] Adding dev_Network_Node_MAC_ADDR to the Devices table
12:15:06 [upgradeDB] Adding dev_Network_Node_port to the Devices table
12:15:06 [upgradeDB] Adding dev_Icon to the Devices table
12:15:06 [upgradeDB] Re-creating Settings table
12:15:06 [upgradeDB] Re-creating Pholus_Scan table
12:15:06 [upgradeDB] Re-creating Parameters table
12:15:09 [Version check] Running the latest version.
12:15:09 [Config] reading config file
17:15:09 [Config] Plugins: Number of dynamically loaded plugins: 29
17:15:09 [Plugin utils] ---------------------------------------------
17:15:09 [Plugin utils] display_name: Apprise publisher
17:15:09 [Plugin utils] description: A plugin to publish a notification via the Apprise gateway.
17:15:17 [Plugin utils] ---------------------------------------------
17:15:17 [Plugin utils] display_name: Email publisher (SMTP)
17:15:17 [Plugin utils] description: A plugin to publish a notification via Email (SMTP) gateway.
17:15:28 [Plugin utils] ---------------------------------------------
17:15:28 [Plugin utils] display_name: MQTT publisher
17:15:28 [Plugin utils] description: A plugin to publish a notification via the Apprise gateway.
17:15:35 [Plugin utils] ---------------------------------------------
17:15:35 [Plugin utils] display_name: NTFY publisher
17:15:35 [Plugin utils] description: A plugin to publish a notification via the NTFY gateway.
17:15:42 [Plugin utils] ---------------------------------------------
17:15:42 [Plugin utils] display_name: Pushover publisher
17:15:42 [Plugin utils] description: A plugin to publish a notification via the pushover.net
17:15:47 [Plugin utils] ---------------------------------------------
17:15:47 [Plugin utils] display_name: Pushsafer publisher
17:15:47 [Plugin utils] description: A plugin to publish a notification via the Pushsafer gateway.
17:15:50 [Plugin utils] ---------------------------------------------
17:15:50 [Plugin utils] display_name: Webhook publisher
17:15:50 [Plugin utils] description: A plugin to publish a notification via Webhooks.
17:15:57 [Plugin utils] ---------------------------------------------
17:15:57 [Plugin utils] display_name: Arp-Scan (Network scan)
17:15:57 [Plugin utils] description: This plugin is to execute an arp-scan on the local network
17:16:04 [Plugin utils] ---------------------------------------------
17:16:04 [Plugin utils] display_name: CSV backup
17:16:04 [Plugin utils] description: A plugin to auto-generate devices.csv backups.
17:16:07 [Plugin utils] ---------------------------------------------
17:16:07 [Plugin utils] display_name: DB cleanup
17:16:07 [Plugin utils] description: A plugin to schedule database cleanup & upkeep tasks.
17:16:10 [Plugin utils] ---------------------------------------------
17:16:10 [Plugin utils] display_name: DDNS update
17:16:10 [Plugin utils] description: A plugin update the DDNS record.
17:16:17 [Plugin utils] ---------------------------------------------
17:16:17 [Plugin utils] display_name: DHCP Leases (Device import)
17:16:17 [Plugin utils] description: This plugin is to import devices from dhcp.leases files.
17:16:24 [Plugin utils] ---------------------------------------------
17:16:24 [Plugin utils] display_name: Rogue DHCP
17:16:24 [Plugin utils] description: This plugin is to use NMAP to monitor for rogue DHCP servers.
17:16:28 [Plugin utils] ---------------------------------------------
17:16:28 [Plugin utils] display_name: Internet-Check
17:16:28 [Plugin utils] description: A plugin to check your internet connectivity and IP.
17:16:35 [Plugin utils] ---------------------------------------------
17:16:35 [Plugin utils] display_name: Internet speedtest
17:16:35 [Plugin utils] description: A plugin to perform a scheduled internet speedtest.
17:16:40 [Plugin utils] ---------------------------------------------
17:16:40 [Plugin utils] display_name: Maintenance
17:16:40 [Plugin utils] description: A plugin for maintenance tasks.
17:16:42 [Plugin utils] ---------------------------------------------
17:16:42 [Plugin utils] display_name: New Devices
17:16:42 [Plugin utils] description: The template used for new devices.
17:16:49 [Plugin utils] ---------------------------------------------
17:16:49 [Plugin utils] display_name: Services & Ports (NMAP)
17:16:49 [Plugin utils] description: This plugin shows all services discovered by NMAP scans.
17:16:56 [Plugin utils] ---------------------------------------------
17:16:56 [Plugin utils] display_name: Notification Processing
17:16:56 [Plugin utils] description: A plugin to for advanced notification processing.
17:16:57 [Plugin utils] ---------------------------------------------
17:16:57 [Plugin utils] display_name: NSLOOKUP (Name discovery)
17:16:57 [Plugin utils] description: A plugin to discover device names.
17:17:00 [Plugin utils] ---------------------------------------------
17:17:00 [Plugin utils] display_name: Pholus (Name discovery)
17:17:00 [Plugin utils] description: This plugin is to execute a Pholus (name discovery) on the local network
17:17:06 [Plugin utils] ---------------------------------------------
17:17:06 [Plugin utils] display_name: PiHole (Device sync)
17:17:06 [Plugin utils] description: This plugin syncs devices from the PiHole database
17:17:10 [Plugin utils] ---------------------------------------------
17:17:10 [Plugin utils] display_name: Set password
17:17:10 [Plugin utils] description: A simple plugin to set the web ui password on app start.
17:17:12 [Plugin utils] ---------------------------------------------
17:17:12 [Plugin utils] display_name: SNMP discovery
17:17:12 [Plugin utils] description: This plugin is used to discover devices via the arp table(s) of a RFC1213 compliant router or switch.
17:17:17 [Plugin utils] ---------------------------------------------
17:17:17 [Plugin utils] display_name: Un-Discoverable Devices
17:17:17 [Plugin utils] description: This plugin is to import undiscoverable devices from a file.
17:17:23 [Plugin utils] ---------------------------------------------
17:17:23 [Plugin utils] display_name: UniFi import
17:17:23 [Plugin utils] description: This plugin is used to import devices from an UNIFI controller.
17:17:33 [Plugin utils] ---------------------------------------------
17:17:33 [Plugin utils] display_name: Vendor update
17:17:33 [Plugin utils] description: A plugin to schedule vendor database updates for mac based vendor resolution.
17:17:40 [Plugin utils] ---------------------------------------------
17:17:40 [Plugin utils] display_name: Website monitor
17:17:40 [Plugin utils] description: This plugin is to monitor status changes of services or websites.
17:17:46 [Plugin utils] ---------------------------------------------
17:17:46 [Plugin utils] display_name: Workflows
17:17:46 [Plugin utils] description: A plugin to adjust behavior of workflows.
17:18:35 [API] Updating table_settings.json file in /front/api
17:18:35 [Config] Imported new config
17:18:35 [API] Updating table_appevents.json file in /front/api
17:18:35 [API] Updating table_devices.json file in /front/api
17:18:35 [API] Updating table_events_pending_alert.json file in /front/api
17:18:35 [API] Updating table_plugins_events.json file in /front/api
17:18:35 [API] Updating table_plugins_history.json file in /front/api
17:18:35 [API] Updating table_plugins_objects.json file in /front/api
17:18:35 [API] Updating table_plugins_language_strings.json file in /front/api
17:18:35 [Database] - SQL ERROR: no such table: Notifications
17:18:35 [API] Updating table_notifications.json file in /front/api
17:18:35 [API] Updating table_custom_endpoint.json file in /front/api
17:18:35 [Plugin utils] ---------------------------------------------
17:18:35 [Plugin utils] display_name: NSLOOKUP (Name discovery)
17:18:35 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
12:18:35 [NSLOOKUP] In script
12:18:35 [Database] Opening DB
12:18:35 [NSLOOKUP] Unknown devices count: 0
12:18:35 [NSLOOKUP] Script finished
17:18:35 [Plugins] No output received from the plugin NSLOOKUP - enable LOG_LEVEL=debug and check logs
17:18:35 [Notification] Check if something to report
17:18:35 [Notification] Included sections: ['new_devices', 'down_devices', 'events']
17:18:36 [Notification] No changes to report
17:18:36 [MAIN] Process: Wait
17:18:41 [API] Updating table_notifications.json file in /front/api
17:19:37 [Plugin utils] ---------------------------------------------
17:19:37 [Plugin utils] display_name: NSLOOKUP (Name discovery)
17:19:37 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
12:19:37 [NSLOOKUP] In script
12:19:37 [Database] Opening DB
12:19:37 [NSLOOKUP] Unknown devices count: 0
12:19:37 [NSLOOKUP] Script finished
17:19:37 [Plugins] No output received from the plugin NSLOOKUP - enable LOG_LEVEL=debug and check logs
17:19:37 [Notification] Check if something to report
17:19:37 [Notification] Included sections: ['new_devices', 'down_devices', 'events']
17:19:37 [Notification] No changes to report
17:19:37 [MAIN] Process: Wait
17:20:42 [Plugin utils] ---------------------------------------------
17:20:42 [Plugin utils] display_name: Arp-Scan (Network scan)
17:20:42 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/arp_scan/script.py userSubnets={subnets}
12:20:43 [ARP Scan] In script 
12:20:43 [ARP Scan] values.userSubnets: ["userSubnets=b'MTkyLjE2OC4xLjAvMjQgLS1pbnRlcmZhY2U9ZXRoMQ=='"]
12:20:43 [ARP Scan] userSubnetsParamBase64: 'MTkyLjE2OC4xLjAvMjQgLS1pbnRlcmZhY2U9ZXRoMQ=='
12:20:43 [ARP Scan] userSubnetsParam: 192.168.1.0/24 --interface=eth1
12:20:43 [Database] Opening DB
12:20:54 [ARP Scan] arpscan_output: Interface: eth1, type: EN10MB, MAC: XX:XX:XX:XX:XX:XX, IPv4: (none)
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)

0 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.10.0: 256 hosts scanned in 11.136 seconds (22.99 hosts/sec). 0 responded

12:20:54 [ARP Scan] Found: Devices without duplicates 0
12:20:54 Devices List len:0
12:20:54 Devices List:[]
17:20:54 [Plugins] No output received from the plugin ARPSCAN - enable LOG_LEVEL=debug and check logs
17:20:54 [Plugin utils] ---------------------------------------------
17:20:54 [Plugin utils] display_name: Internet-Check
17:20:54 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/internet_ip/script.py prev_ip={prev_ip} INTRNT_DIG_GET_IP_ARG={INTRNT_DIG_GET_IP_ARG}
12:20:54 [INTRNT] In script
12:20:54 [INTRNT] INTRNT_DIG_GET_IP_ARG: -4 myip.opendns.com @resolver1.opendns.com
12:20:54 [INTRNT] - Retrieving Internet IP
12:20:54 [INTRNT]  DIG result : XXX.XXX.XXX.XXX

12:20:54 [INTRNT]  Current internet_IP : XXX.XXX.XXX.XXX
12:20:54 [INTRNT]          previous_IP : 0.0.0.0
12:20:54 [INTRNT] Finished 
17:20:54 [Plugins] SUCCESS, received 1 entries
17:20:55 [API] Updating table_appevents.json file in /front/api
17:20:55 [API] Updating table_plugins_events.json file in /front/api
17:20:55 [API] Updating table_plugins_history.json file in /front/api
17:20:55 [API] Updating table_plugins_objects.json file in /front/api
17:20:55 [Process Scan]  Processing scan results
17:20:55 [Process Scan] Print Stats
17:20:55 [Scan Stats] Devices Detected.......: 2
17:20:55 [Scan Stats] New Devices............: 1
17:20:55 [Scan Stats] Down Alerts............: 0
17:20:55 [Scan Stats] New Down Alerts........: 0
17:20:55 [Scan Stats] New Connections........: 0
17:20:55 [Scan Stats] Disconnections.........: 0
17:20:55 [Scan Stats] IP Changes.............: 1
17:20:55 [Scan Stats] Scan Method Statistics:
17:20:55     INTRNT: 1
17:20:55     local_MAC: 1
17:20:55 [Process Scan] Stats end
17:20:55 [Process Scan] Sessions Events (connect / discconnect)
17:20:56 [Process Scan] Creating new devices
17:20:56 [Process Scan] Updating Devices Info
17:20:57 [Process Scan] Voiding false (ghost) disconnections
17:20:57 [Process Scan] Pairing session events (connection / disconnection) 
17:20:57 [Process Scan] Creating sessions snapshot
17:20:57 [Process Scan] Inserting scan results into Online_History
17:20:57 [Process Scan] Skipping repeated notifications
17:20:57 [Skip Repeated Notifications] Skip Repeated
17:20:57 [Plugin utils] ---------------------------------------------
17:20:57 [Plugin utils] display_name: NSLOOKUP (Name discovery)
17:20:57 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
12:20:58 [NSLOOKUP] In script
12:20:58 [Database] Opening DB
12:20:58 [NSLOOKUP] Unknown devices count: 1
12:20:58 [NSLOOKUP]No PTR record found for IP: 192.168.100.2
12:20:58 [NSLOOKUP] Script finished
17:20:58 [Plugins] No output received from the plugin NSLOOKUP - enable LOG_LEVEL=debug and check logs
17:20:58 [Update Device Name] Trying to resolve devices without name. Unknown devices count: 1
17:20:58 [Update Device Name] Pholus entries from prev scans: 0
17:20:58 [Update Device Name] Names Found (DiG/NSLOOKUP/Pholus): 0 (0/0/0)
17:20:58 [Update Device Name] Names Not Found         : 1
17:20:58 [Plugin utils] ---------------------------------------------
17:20:58 [Plugin utils] display_name: Pholus (Name discovery)
17:20:58 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/pholus_scan/script.py userSubnets={subnets} timeoutSec={timeout}
12:20:58 [PHOLUS] In script
12:20:58 [PHOLUS] Subnets: ["userSubnets=b'MTkyLjE2OC4xLjAvMjQgLS1pbnRlcmZhY2U9ZXRoMQ=='"]
12:20:58 [PHOLUS] len Subnets: 1
12:20:58 [PHOLUS] 'MTkyLjE2OC4xLjAvMjQgLS1pbnRlcmZhY2U9ZXRoMQ=='
12:20:58 [PHOLUS] 300
12:20:58 [PHOLUS] userSubnetsParam 192.168.1.0/24 --interface=eth1 
12:20:58 [PHOLUS] 300.0 
12:20:58 [PHOLUS] Scan: Pholus for 300.0s (5.0min)
12:20:58 [PHOLUS] Pholus scan on [interface] eth1 [mask] 192.168.1.0/24
12:21:38 [PHOLUS] Scan: Pholus SUCCESS
12:21:38 [PHOLUS] XXXXXXX
12:21:38 [PHOLUS] Pholus output number of entries:122
12:21:38 [PHOLUS] XXXXXXX
17:21:38 [Plugins] SUCCESS, received 122 entries
17:22:40 [API] Updating table_appevents.json file in /front/api
17:22:40 [API] Updating table_plugins_events.json file in /front/api
17:22:40 [API] Updating table_plugins_history.json file in /front/api
17:22:40 [API] Updating table_plugins_objects.json file in /front/api
17:22:40 [Notification] Check if something to report
17:22:40 [Notification] Included sections: ['new_devices', 'down_devices', 'events']
17:22:40 [Notification] Open text Template
17:22:40 [Notification] Open html Template
17:22:40 [Notification] Using template/back/report_template.html
17:22:40 [Notification] New Devices sections done.
17:22:40 [Notification] Down Devices sections done.
17:22:40 [Notification] Events sections done.
17:22:40 [Notification] Plugins sections done.
17:22:40 [Send API] Updating notification_* files in /home/pi/pialert/front/api/
17:22:40 [Notification] Udating API files
17:22:40 [Notification] Notifications changes: 123
17:22:40 [MAIN] Process: Wait
17:22:45 [API] Updating table_appevents.json file in /front/api
17:22:45 [API] Updating table_devices.json file in /front/api
17:22:45 [API] Updating table_plugins_events.json file in /front/api
17:22:45 [API] Updating table_notifications.json file in /front/api
17:22:45 [Plugin utils] ---------------------------------------------
17:22:45 [Plugin utils] display_name: NSLOOKUP (Name discovery)
17:22:45 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
12:22:46 [NSLOOKUP] In script
12:22:46 [Database] Opening DB
12:22:46 [NSLOOKUP] Unknown devices count: 1
12:22:46 [NSLOOKUP]No PTR record found for IP: 192.168.100.2
12:22:46 [NSLOOKUP] Script finished
17:22:46 [Plugins] No output received from the plugin NSLOOKUP - enable LOG_LEVEL=debug and check logs
17:22:46 [Update Device Name] Trying to resolve devices without name. Unknown devices count: 1
17:22:46 [Update Device Name] Pholus entries from prev scans: 0
17:22:46 [Update Device Name] Names Found (DiG/NSLOOKUP/Pholus): 0 (0/0/0)
17:22:46 [Update Device Name] Names Not Found         : 1
17:22:46 [Notification] Check if something to report
17:22:46 [Notification] Included sections: ['new_devices', 'down_devices', 'events']
17:22:46 [Notification] No changes to report
17:22:46 [MAIN] Process: Wait
17:23:46 [Plugin utils] ---------------------------------------------
17:23:46 [Plugin utils] display_name: NSLOOKUP (Name discovery)
17:23:46 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
12:23:47 [NSLOOKUP] In script
12:23:47 [Database] Opening DB
12:23:47 [NSLOOKUP] Unknown devices count: 1
12:23:47 [NSLOOKUP]No PTR record found for IP: 192.168.100.2
12:23:47 [NSLOOKUP] Script finished
17:23:47 [Plugins] No output received from the plugin NSLOOKUP - enable LOG_LEVEL=debug and check logs
17:23:47 [Update Device Name] Trying to resolve devices without name. Unknown devices count: 1
17:23:47 [Update Device Name] Pholus entries from prev scans: 0
17:23:47 [Update Device Name] Names Found (DiG/NSLOOKUP/Pholus): 0 (0/0/0)
17:23:47 [Update Device Name] Names Not Found         : 1
17:23:47 [Notification] Check if something to report
17:23:47 [Notification] Included sections: ['new_devices', 'down_devices', 'events']
17:23:47 [Notification] No changes to report
17:23:47 [MAIN] Process: Wait
17:24:47 [Plugin utils] ---------------------------------------------
17:24:47 [Plugin utils] display_name: NSLOOKUP (Name discovery)
17:24:47 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
12:24:47 [NSLOOKUP] In script
12:24:47 [Database] Opening DB
12:24:47 [NSLOOKUP] Unknown devices count: 1
12:24:48 [NSLOOKUP]No PTR record found for IP: 192.168.100.2
12:24:48 [NSLOOKUP] Script finished
17:24:48 [Plugins] No output received from the plugin NSLOOKUP - enable LOG_LEVEL=debug and check logs
17:24:48 [Update Device Name] Trying to resolve devices without name. Unknown devices count: 1
17:24:48 [Update Device Name] Pholus entries from prev scans: 0
17:24:48 [Update Device Name] Names Found (DiG/NSLOOKUP/Pholus): 0 (0/0/0)
17:24:48 [Update Device Name] Names Not Found         : 1
17:24:48 [Notification] Check if something to report
17:24:48 [Notification] Included sections: ['new_devices', 'down_devices', 'events']
17:24:48 [Notification] No changes to report
17:24:48 [MAIN] Process: Wait
17:25:48 [Plugin utils] ---------------------------------------------
17:25:48 [Plugin utils] display_name: Arp-Scan (Network scan)
17:25:48 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/arp_scan/script.py userSubnets={subnets}
12:25:48 [ARP Scan] In script 
12:25:48 [ARP Scan] values.userSubnets: ["userSubnets=b'MTkyLjE2OC4xLjAvMjQgLS1pbnRlcmZhY2U9ZXRoMQ=='"]
12:25:48 [ARP Scan] userSubnetsParamBase64: 'MTkyLjE2OC4xLjAvMjQgLS1pbnRlcmZhY2U9ZXRoMQ=='
12:25:48 [ARP Scan] userSubnetsParam: 192.168.1.0/24 --interface=eth1
12:25:48 [Database] Opening DB
12:26:00 [ARP Scan] arpscan_output: Interface: eth1, type: EN10MB, MAC: 90:09:d0:0e:ab:74, IPv4: (none)
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)

2 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.10.0: 256 hosts scanned in 11.106 seconds (23.05 hosts/sec). 0 responded

12:26:00 [ARP Scan] Found: Devices without duplicates 0
12:26:00 Devices List len:0
12:26:00 Devices List:[]
17:26:00 [Plugins] No output received from the plugin ARPSCAN - enable LOG_LEVEL=debug and check logs
17:26:00 [Plugin utils] ---------------------------------------------
17:26:00 [Plugin utils] display_name: Internet-Check
17:26:00 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/internet_ip/script.py prev_ip={prev_ip} INTRNT_DIG_GET_IP_ARG={INTRNT_DIG_GET_IP_ARG}
12:26:00 [INTRNT] In script
12:26:00 [INTRNT] INTRNT_DIG_GET_IP_ARG: -4 myip.opendns.com @resolver1.opendns.com
12:26:00 [INTRNT] - Retrieving Internet IP
12:26:00 [INTRNT]  DIG result : XXX.XXX.XXX.XXX

12:26:00 [INTRNT]  Current internet_IP : XXX.XXX.XXX.XXX
12:26:00 [INTRNT]          previous_IP : XXX.XXX.XXX.XXX
12:26:00 [INTRNT] Finished 
17:26:00 [Plugins] SUCCESS, received 1 entries
17:26:01 [API] Updating table_appevents.json file in /front/api
17:26:01 [API] Updating table_plugins_history.json file in /front/api
17:26:01 [API] Updating table_plugins_objects.json file in /front/api
17:26:01 [Process Scan]  Processing scan results
17:26:01 [Process Scan] Print Stats
17:26:01 [Scan Stats] Devices Detected.......: 2
17:26:01 [Scan Stats] New Devices............: 0
17:26:01 [Scan Stats] Down Alerts............: 0
17:26:01 [Scan Stats] New Down Alerts........: 0
17:26:01 [Scan Stats] New Connections........: 0
17:26:01 [Scan Stats] Disconnections.........: 0
17:26:01 [Scan Stats] IP Changes.............: 0
17:26:01 [Scan Stats] Scan Method Statistics:
17:26:01     INTRNT: 1
17:26:01     local_MAC: 1
17:26:01 [Process Scan] Stats end
17:26:01 [Process Scan] Sessions Events (connect / discconnect)
17:26:01 [Process Scan] Creating new devices
17:26:01 [Process Scan] Updating Devices Info
17:26:01 [Process Scan] Voiding false (ghost) disconnections
17:26:01 [Process Scan] Pairing session events (connection / disconnection) 
17:26:01 [Process Scan] Creating sessions snapshot
17:26:02 [Process Scan] Inserting scan results into Online_History
17:26:02 [Process Scan] Skipping repeated notifications
17:26:02 [Skip Repeated Notifications] Skip Repeated
17:26:02 [Plugin utils] ---------------------------------------------
17:26:02 [Plugin utils] display_name: NSLOOKUP (Name discovery)
17:26:02 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
12:26:02 [NSLOOKUP] In script
12:26:02 [Database] Opening DB
12:26:02 [NSLOOKUP] Unknown devices count: 1
12:26:03 [NSLOOKUP]No PTR record found for IP: 192.168.100.2
12:26:03 [NSLOOKUP] Script finished
17:26:03 [Plugins] No output received from the plugin NSLOOKUP - enable LOG_LEVEL=debug and check logs
17:26:03 [Update Device Name] Trying to resolve devices without name. Unknown devices count: 1
17:26:03 [Update Device Name] Pholus entries from prev scans: 0
17:26:03 [Update Device Name] Names Found (DiG/NSLOOKUP/Pholus): 0 (0/0/0)
17:26:03 [Update Device Name] Names Not Found         : 1
17:26:03 [Notification] Check if something to report
17:26:03 [Notification] Included sections: ['new_devices', 'down_devices', 'events']
17:26:03 [Notification] No changes to report
17:26:03 [MAIN] Process: Wait

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @ameer1234567890 ,

I optimized the startup sequence for the next release. If you can, please have a look at the `pi.alert_dev` docker image, as I think this should be fixed in it. 

Once you are on the dev image, clear the cache and refresh the cache:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/6c0b0392-5c26-4ea7-b031-3d730baff34b)

The error might be still logged, but there should be no 404. 

Please let me know if the issue was resolved.

Thanks in advance,
j

**Comment by ameer1234567890** [comment]
I tried `pi.alert_dev` and it works.

**Comment by jokob-sk** [comment]
Thanks for checking 👍

**Comment by jokob-sk** [comment]
released 🚀 -> closing
