### ISSUE TITLE
Alert Down should also include Alert Up

### ISSUE THREAD

**Issue by cyberbrix** [jokob-sk/NetAlertX#611]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I don't want all the notifications for my devices, such as IP changes, or whatever else may come up. But I do want to monitor up/down time.

### Describe the solution you'd like

When Alert Down is selected, Alert Up should also be the default action.  (if an item is down, I'd want to know when it is back up)

### Describe alternatives you've considered

I've gotten noisy alerts for other devices, but I'm only concerned for Down/Up.

### Anything else?

Nothing else, thank you

**Comment by jokob-sk** [comment]
This should be available in the next release. Please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/a05ef08f-a0b2-4640-ab39-acf497d0786a)

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/214355ef-05fb-41ab-bb94-050f3dceac06)


⚠If I don't get a confirmation that this is working I might pull out the feature to prevent bugs. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue/functionality is now working.

Thanks in advance,
j

**Comment by jokob-sk** [comment]
closing -> releasing in ~10min
