### ISSUE TITLE
Hide the Device Presence Graph at the Top

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/NetAlertX#612]
### Discussed in https://github.com/jokob-sk/Pi.Alert/discussions/610

<div type='discussions-op-text'>

<sup>Originally posted by **anjota80** March 31, 2024</sup>
On the original version of Pi.Alert, there was an option to remove the device presence graph at the top of the screen. Is there a way to remove the graph in this version? I have checked the settings and you can select what to show in the graph but cannot see an option to remove from the screen. If this is not an option, perhaps add this in for future development?
Thanks.</div>

**Comment by anjota80** [comment]
@jokob-sk Not sure if this was ready to test but I have tested. I downloaded the dev image this afternoon and tested the functionality. From what I can see, it does not work correctly. I tried to remove the buttons at the top, the device presence graph and both at the same time. Each test results in no changes to the screen layout. Both the buttons and graph are displayed.

![Uploading B.png…]()

![C](https://github.com/jokob-sk/Pi.Alert/assets/53611664/8a7f9f66-c756-407b-87a1-923423ead192)

**Comment by jokob-sk** [comment]
Thanks for checking!

It seems to be working fine on my end with these settings:

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/c9966efc-8039-4d70-800e-a208de44a0fb)

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/6ea17c6e-d059-46bf-b887-0e0ab271b42d)

Can you re-download the latest _dev image and test once more?

**Comment by jokob-sk** [comment]
released 🚀 -> closing
