### ISSUE TITLE
Auto Refresh Option

### ISSUE THREAD

**Issue by anjota80** [jokob-sk/NetAlertX#614]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When first starting the Pi.Alert instance, the screen refreshes automatically updating the device statuses. However, after a period of time, the auto refresh stops working. I have to manually press the refresh button to update the device statuses. The example image shows one of my Access Points as active but it had been switched off for over 30 minutes. Pressing the refresh button at the top updated the device status.

![D](https://github.com/jokob-sk/Pi.Alert/assets/53611664/3efb41c3-203c-4dc2-b3f3-a6303302727d)

### Describe the solution you'd like

An option in the settings to display the auto-refresh option and allow changes to the time interval. The Pucherot version of Pi.Alert used to have the option to switch auto refresh on/off with a 2-minute interval.

https://github.com/pucherot/Pi.Alert

### Describe alternatives you've considered

I have added an auto screen refresh extension to Chromium, however, this does not always work. I have Pi.Alert setup as a monitor that is always on so that I can see what is active on my network. Having to manually press the refresh button is not ideal. 

### Anything else?

Nothing

**Comment by jokob-sk** [comment]
![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/553102f9-b4cd-4e01-b04c-ca135208da88)

**Comment by anjota80** [comment]
Perfect - Thanks

**Comment by jokob-sk** [comment]
released 🚀 -> closing
