### ISSUE TITLE
Un-Discoverable Devices Set to Online

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/NetAlertX#617]
### Discussed in https://github.com/jokob-sk/Pi.Alert/discussions/615

<div type='discussions-op-text'>

<sup>Originally posted by **anjota80** April  3, 2024</sup>
I have several unmanaged switches (non-IP) added to my network. However, they show as offline in My Devices. I think it would be best to show Un-Discoverable devices as online rather than offline. Perhaps a future enhancement to the build?

![2024-04-02_22-42-12](https://github.com/jokob-sk/Pi.Alert/assets/53611664/8c066521-b693-4120-ae01-52ca5f1a0f5e)

![2024-04-02_22-40-52](https://github.com/jokob-sk/Pi.Alert/assets/53611664/97ec9086-c477-4c8a-b9e1-1b763c788649)
</div>

**Comment by jokob-sk** [comment]
![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/e2c532b8-1472-401f-b3f9-6252f9229cd8)
![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/90b61d27-e6c9-4891-86c5-77e1bc38d778)
This should be available in the next release. If you can, please have a look at the `pi.alert_dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/Pi.Alert/actions)) from now. 

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved.

Thanks in advance,
j

**Comment by jokob-sk** [comment]
see above @anjota80

**Comment by anjota80** [comment]
@jokob-sk Thanks for this. I am travelling tonight so I will test using the dev image tomorrow when I get home.

**Comment by anjota80** [comment]
@jokob-sk I downloaded the dev image and tested this functionality and it seems to work as expected. Both dummy devices I added are showing as Online. It took some time to test as there were a lot of issues with the table layout, refreshing etc. Assuming there is ongoing work being done to fix the issues.

![A](https://github.com/jokob-sk/Pi.Alert/assets/53611664/66ce9e81-a437-4c4f-ad32-11bee3a2603c)

**Comment by jokob-sk** [comment]
Glad it's working, and yes, it's the dev container so things will be broken :)

**Comment by jokob-sk** [comment]
released 🚀 -> closing

**Comment by Daditj** [comment]
Hello, 
I created non manageable switch, but how can I male them "online" on map ?

**Comment by jokob-sk** [comment]
Hi @Daditj - you need to configure ICMP to check their IP. If it doesn;t have an IP, use a loopback, e.g. 0.0.0.0 IP. You can change the IP via Multi-edit:

- https://jokob-sk.github.io/NetAlertX/REMOTE_NETWORKS/?h=icmp#manual-entry
- https://jokob-sk.github.io/NetAlertX/DEVICES_BULK_EDITING/?h=multi

**Comment by Daditj** [comment]
Hi, 
ty for the answer, but it doesnt work.
I Create a switch 👍 
IP : 127.0.0.1
MAC : 00:00:00:00:00:00
Type : Switch
Relationship : logical

He is all the time offline...

**Comment by Daditj** [comment]
<img width="332" height="217" alt="Image" src="https://github.com/user-attachments/assets/39127d03-e11e-44eb-a471-30e6d6e65b02" />

**Comment by jokob-sk** [comment]
Could you please show me a screenshot of your ICMP plugin configuration?

**Comment by Daditj** [comment]
Hi, 

<img width="1720" height="83" alt="Image" src="https://github.com/user-attachments/assets/aad83d6d-c4cd-4a87-a86f-9a2675b41a57" />

**Comment by jokob-sk** [comment]
Please share your ICMP settings, e.g.:

<img width="1963" height="599" alt="Image" src="https://github.com/user-attachments/assets/78962a10-9f3d-4cec-b626-0e2490ea82f6" />

**Comment by Daditj** [comment]
<img width="1721" height="340" alt="Image" src="https://github.com/user-attachments/assets/1cc7de2a-85da-4744-8647-71ee62db7649" />

**Comment by jokob-sk** [comment]
Please switch to schedule to enable the plugin

<img width="1101" height="178" alt="Image" src="https://github.com/user-attachments/assets/d84f312b-7e98-4272-8bf7-dcb133113c5a" />

**Comment by Daditj** [comment]
I Think it's OK now !
Thanks
Have a good day
