### ISSUE TITLE
Manual NMAP Scans with unknown IP values

### ISSUE THREAD

**Issue by zilvernet** [jokob-sk/NetAlertX#621]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior
On the Latest version: 24.3.19 

<img width="928" alt="Screenshot 2024-04-12 at 8 45 19 AM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/da131a1b-6695-4f20-b9f5-d17e4158e2e5">
<img width="1061" alt="Screenshot 2024-04-12 at 8 45 27 AM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/c8c133d6-2369-4e0e-84f4-311c78983d0a">

The manual NMAP option randomly show unknown values of ips.

### Expected Behavior

Any device on the tools section should have the matching ip for a manual nmap scan but im currently getting unknown value.

If I restart the container sometimes this will get fixed.

### docker-compose.yml

```python
version: "3"
services:
  pialert:
    container_name: alert
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/pi.alert_dev:latest" 
    image: "jokobsk/pi.alert:${PIALERT_TAG:-latest}"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - ${APP_DATA_LOCATION:-/docker_data}/pialert/config:/home/pi/pialert/config
      - ${APP_DATA_LOCATION:-/docker_data}/pialert/db:/home/pi/pialert/db     
      # (optional) useful for debugging if you have issues setting up the container
      - ${APP_DATA_LOCATION:-/docker_data}/pialert/log:/home/pi/pialert/front/log
    environment:
      - TZ=${TZ:-America/New_York}      
      - PORT=${PORT:-20211}
```

### What branch are you running?

Production

### app.log

08:59:11 [Update Device Name] Names Not Found         : 11
08:59:11 [Notification] Check if something to report
08:59:11 [Notification] Included sections: ['new_devices', 'down_devices', 'events']
08:59:11 [Notification] No changes to report
08:59:11 [MAIN] Process: Wait
09:00:13 [Plugin utils] ---------------------------------------------
09:00:13 [Plugin utils] display_name: Internet-Check
09:00:13 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/internet_ip/script.py prev_ip={prev_ip} INTRNT_DIG_GET_IP_ARG={INTRNT_DIG_GET_IP_ARG}
09:00:14 [Plugins] SUCCESS, received 1 entries
09:00:14 [API] Updating table_appevents.json file in /front/api
09:00:14 [API] Updating table_plugins_history.json file in /front/api
09:00:14 [Plugin utils] ---------------------------------------------
09:00:14 [Plugin utils] display_name: Arp-Scan (Network scan)
09:00:14 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/arp_scan/script.py userSubnets={subnets}
09:00:25 [Plugins] SUCCESS, received 93 entries
09:00:26 [API] Updating table_appevents.json file in /front/api
09:00:26 [API] Updating table_plugins_events.json file in /front/api
09:00:26 [API] Updating table_plugins_history.json file in /front/api
09:00:26 [API] Updating table_plugins_objects.json file in /front/api
09:00:26 [Plugin utils] ---------------------------------------------
09:00:26 [Plugin utils] display_name: DB cleanup
09:00:26 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/db_cleanup/script.py pluginskeephistory={pluginskeephistory} hourstokeepnewdevice={hourstokeepnewdevice} daystokeepevents={daystokeepevents} pholuskeepdays={pholuskeepdays}
09:00:26 [Plugins] No output received from the plugin DBCLNP - enable LOG_LEVEL=debug and check logs
09:00:26 [Process Scan]  Processing scan results
09:00:26 [Process Scan] Print Stats
09:00:26 [Scan Stats] Devices Detected.......: 95
09:00:26 [Scan Stats] New Devices............: 0
09:00:26 [Scan Stats] Down Alerts............: 1
09:00:26 [Scan Stats] New Down Alerts........: 0
09:00:26 [Scan Stats] New Connections........: 28
09:00:26 [Scan Stats] Disconnections.........: 0
09:00:26 [Scan Stats] IP Changes.............: 1
09:00:26 [Scan Stats] Scan Method Statistics:
09:00:26     INTRNT: 1
09:00:26     arp-scan: 93
09:00:26     local_MAC: 1
09:00:26 [Process Scan] Stats end
09:00:26 [Process Scan] Sessions Events (connect / discconnect)
09:00:26 [Process Scan] Creating new devices
09:00:26 [Process Scan] Updating Devices Info
09:00:26 [Process Scan] Voiding false (ghost) disconnections
09:00:26 [Process Scan] Pairing session events (connection / disconnection) 
09:00:26 [Process Scan] Creating sessions snapshot
09:00:26 [Process Scan] Inserting scan results into Online_History
09:00:26 [Process Scan] Skipping repeated notifications
09:00:26 [Skip Repeated Notifications] Skip Repeated
09:00:26 [Plugin utils] ---------------------------------------------
09:00:26 [Plugin utils] display_name: NSLOOKUP (Name discovery)
09:00:26 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
09:00:27 [Plugins] No output received from the plugin NSLOOKUP - enable LOG_LEVEL=debug and check logs
09:00:27 [Update Device Name] Trying to resolve devices without name. Unknown devices count: 11
09:00:27 [Update Device Name] Pholus entries from prev scans: 513
09:00:27 [Update Device Name] Names Found (DiG/NSLOOKUP/Pholus): 0 (0/0/0)
09:00:27 [Update Device Name] Names Not Found         : 11
09:00:27 [Notification] Check if something to report
09:00:28 [Notification] Included sections: ['new_devices', 'down_devices', 'events']
09:00:28 [Notification] Open text Template
09:00:28 [Notification] Open html Template
09:00:28 [Notification] Using template/back/report_template.html
09:00:28 [Notification] New Devices sections done.
09:00:28 [Notification] Down Devices sections done.
09:00:28 [Notification] Events sections done.
09:00:28 [Notification] Plugins sections done.
09:00:28 [Send API] Updating notification_* files in /home/pi/pialert/front/api/
09:00:28 [Notification] Udating API files
09:00:28 [Notification] Notifications changes: 1
09:00:28 [MAIN] Process: Wait
09:00:33 [API] Updating table_appevents.json file in /front/api
09:00:33 [API] Updating table_devices.json file in /front/api
09:00:33 [API] Updating table_plugins_events.json file in /front/api
09:00:33 [API] Updating table_plugins_history.json file in /front/api
09:00:33 [API] Updating table_notifications.json file in /front/api
09:00:33 [API] Updating table_custom_endpoint.json file in /front/api
09:01:14 [Plugin utils] ---------------------------------------------
09:01:14 [Plugin utils] display_name: NSLOOKUP (Name discovery)
09:01:14 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
09:01:15 [Plugins] No output received from the plugin NSLOOKUP - enable LOG_LEVEL=debug and check logs
09:01:15 [Update Device Name] Trying to resolve devices without name. Unknown devices count: 11
09:01:15 [Update Device Name] Pholus entries from prev scans: 513
09:01:15 [Update Device Name] Names Found (DiG/NSLOOKUP/Pholus): 0 (0/0/0)
09:01:15 [Update Device Name] Names Not Found         : 11
09:01:15 [Notification] Check if something to report
09:01:15 [Notification] Included sections: ['new_devices', 'down_devices', 'events']
09:01:15 [Notification] No changes to report
09:01:15 [MAIN] Process: Wait
09:02:18 [Plugin utils] ---------------------------------------------
09:02:18 [Plugin utils] display_name: NSLOOKUP (Name discovery)
09:02:18 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py
09:02:18 [Plugins] No output received from the plugin NSLOOKUP - enable LOG_LEVEL=debug and check logs
09:02:18 [Update Device Name] Trying to resolve devices without name. Unknown devices count: 11
09:02:18 [Update Device Name] Pholus entries from prev scans: 513
09:02:19 [Update Device Name] Names Found (DiG/NSLOOKUP/Pholus): 0 (0/0/0)
09:02:19 [Update Device Name] Names Not Found         : 11
09:02:19 [Notification] Check if something to report
09:02:19 [Notification] Included sections: ['new_devices', 'down_devices', 'events']
09:02:19 [Notification] No changes to report
09:02:19 [MAIN] Process: Wait
09:03:21 [Plugin utils] ---------------------------------------------
09:03:21 [Plugin utils] display_name: NSLOOKUP (Name discovery)
09:03:21 [Plugins] Executing: python3 /home/pi/pialert/front/plugins/nslookup_scan/nslookup.py

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by zilvernet** [comment]
I reverted to version: v24.2.17

and this bug is no longer present.

**Comment by jokob-sk** [comment]
The `unknown` bug should be fixed in the next release. The detailed scan #623 is still a work in progress. If you can, please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved.

Thanks in advance,
j

**Comment by jokob-sk** [comment]
released 🚀 -> closing
