### ISSUE TITLE
Manual Nmap Scans - Detailed Scan not longer works

### ISSUE THREAD

**Issue by zilvernet** [jokob-sk/NetAlertX#623]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

On the latest version: 24.3.19

This feature is broken:

<img width="824" alt="Screenshot 2024-04-12 at 9 50 11 AM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/6d25c003-74fc-4e43-b933-c813586a23ca">

It works on the previouse release version: 24.2.17

### Expected Behavior

it should display the result of a detailed scan.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thansk for the report - @vladaurosh, sorry to have to ping you again, but I think this might be Alpine related and I couldn't find a solution online. It seems like the `/usr/share/nmap/scripts/` directory is missing on Alpine. I also checked the Alpine package repository and the folder is missing there as well it seems: 

https://pkgs.alpinelinux.org/contents?file=&path=&name=nmap&branch=edge

To reproduce the issue, I run the `nmap  -A 192.168.1.86 ` command, which produces the below error:

```
Starting Nmap 7.94 ( https://nmap.org ) at 2024-04-13 07:49 AEST
NSE: failed to initialize the script engine:
could not locate nse_main.lua
stack traceback:
        [C]: in ?

QUITTING!
```
Will continue my research.

**Comment by zilvernet** [comment]
Hi @jokob-sk 

I tried the nmap -a on my docker image:

docker exec -it pialert bash
server:/# nmap  -A 192.168.1.86
Starting Nmap 7.94 ( https://nmap.org ) at 2024-04-12 22:09 UTC
NSE: failed to initialize the script engine:
could not locate nse_main.lua
stack traceback:
	[C]: in ?

QUITTING!

I got the same result.

**Comment by vladaurosh** [comment]
Hey @jokob-sk 
Just opened a PR to fix this 
https://github.com/jokob-sk/NetAlertX/pull/625

**Comment by jokob-sk** [comment]
@vladaurosh amazing - thanks a lot - you are amazingly fast 🙏- for the life of me, I wasn't able to find this - how did you? Just googling?

**Comment by vladaurosh** [comment]
Hey @jokob-sk 
Yeah, just searched for "could not locate nse_main.lua" and first result was the solution. 😄

**Comment by jokob-sk** [comment]
I am blind then 😅 thanks again for the help

**Comment by zilvernet** [comment]
i tested it on the dev version and it is working, thanks.

<img width="864" alt="Screenshot 2024-04-13 at 2 31 41 PM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/1fa86f29-17ce-447d-b67d-aa782d3f62f0">

**Comment by jokob-sk** [comment]
Glad to hear that! Thanks for taking the time to test the dev image.

**Comment by jokob-sk** [comment]
released 🚀 -> closing
