### ISSUE TITLE
Next or Previous host do not update the tools page button's ip address.

### ISSUE THREAD

**Issue by zilvernet** [jokob-sk/NetAlertX#626]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

This is happening in all the 24 release versions and some 23 latest that i was able to test so far.

In the details of a host the previous and forward do not update the tools buttons ip page.
The tools page get stuck with the ip value of the first host detail that was loaded:

On this example i clicked on the samsung washer from a device search screen.
Then it loaded the details.

<img width="1381" alt="Screenshot 2024-04-12 at 8 40 09 PM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/800cb468-996f-4a5a-8fb7-32670585ee70">

Then we go to the tools subpage.

<img width="1365" alt="Screenshot 2024-04-12 at 8 40 17 PM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/99ca3615-2da2-4758-b803-33d88abea878">

Then we skip and the ip : .131 from the samsung washer still on the tools page.

<img width="1373" alt="Screenshot 2024-04-12 at 8 40 56 PM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/67c20ee9-208c-42ac-bc95-4e92fffce132">

### Expected Behavior

The tools subpage should dinamically change the ip from the current selected host.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
This should be fixed in the next release. If you can, please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved.

Thanks in advance,
j

**Comment by zilvernet** [comment]
Hi @jokob-sk i tested the dev-version, but it seems very buggy.
when i entered to the tools page im not able to see the ip for any of my devices:

<img width="1107" alt="Screenshot 2024-04-13 at 11 21 42 AM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/22354d11-6ead-493e-91e3-687150626939">

**Comment by zilvernet** [comment]
when i first tested this, i noticed there was no ip on the buttons and when i pressed them i had an error.

Now after a while has passed after I scanned my hosts the buttons are now working.  It seems there is a background process that prepares the info for these buttons to be operational.  It would be great if the buttons are disabled until they are ready to use to avoid error messages.

**Comment by jokob-sk** [comment]
Thanks for testing! I think the old JS file cache had to expire because now it seems like the buttons are ready to be used instantly. I will improve this in the future if more users provide feedback related to this behavior.

**Comment by jokob-sk** [comment]
released 🚀 -> closing
