### ISSUE TITLE
Device Filtering on the Details Page is broken after version 23.7.22

### ISSUE THREAD

**Issue by zilvernet** [jokob-sk/NetAlertX#627]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

On the Devices section, any type of filter from the dashboard boxes or from the search box works to narrow the list of devices. But if you click on any device from the filtered list, you are no longer on the same list but on the global list.
So your total number of devices will equal to the total number of devices and not the total number of devices from your filter.

### Expected Behavior

On this example i will show how the filtering was working on the version: 23.7.22

We have a total of 110 devices

<img width="1361" alt="Screenshot 2024-04-12 at 9 38 13 PM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/4ec79f21-9cf4-49fe-87d3-5ed139207224">

Then if we search for extreme we narrow the list to 8 devices.

<img width="1347" alt="Screenshot 2024-04-12 at 9 38 31 PM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/6818daca-acfa-4a8a-9803-4162a1906506">

If we click on any of the devices from the list.

<img width="1362" alt="Screenshot 2024-04-12 at 9 38 46 PM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/e129a88a-a02f-46d7-8add-3be306587f33">

The filtered items remain and you can move between the filtered items of the list.

<img width="1370" alt="Screenshot 2024-04-12 at 9 38 55 PM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/13b51d1f-de1b-47af-bcc9-34cf6319f48e">

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
This should be fixed in the next release. If you can, please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved.

Thanks in advance,
j

**Comment by zilvernet** [comment]
HI @jokob-sk , thanks for the prompt update.
I downloaded the latest dev-version, it took me a while to get familiar with the changes.

However the fixes are not working.
I created a new DB and started from scratch.

<img width="1489" alt="Screenshot 2024-04-13 at 11 06 51 AM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/fe0a72fb-6c2b-4422-8731-076e19fc2c4e">

<img width="1495" alt="Screenshot 2024-04-13 at 11 06 18 AM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/50bdcec5-156b-4e30-8c4c-b4e13ec107df">

**Comment by zilvernet** [comment]
It seems there is a process in the background that normalizes something that has to do with these filters, after coming back for a walk a tested and now the filters are working as expected.

**Comment by jokob-sk** [comment]
Thanks for testing, appreciated!

**Comment by jokob-sk** [comment]
released 🚀 -> closing
