### ISSUE TITLE
new icon interfase do not show ok and cancel buttons

### ISSUE THREAD

**Issue by zilvernet** [jokob-sk/NetAlertX#629]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

on the latest dev version:

I was struggling with the new icon interfase.  It seems that there are two buttons that are not shown on my browser but then i was able to figure out and click them to save.

i tested on chrome and safari on MacOS 14 and they both have the buttons hidden.

safari:
<img width="682" alt="Screenshot 2024-04-13 at 12 20 20 PM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/32562c75-d843-44cf-ba6b-b58baf647bec">

chrome:
<img width="1020" alt="Screenshot 2024-04-13 at 12 21 24 PM" src="https://github.com/jokob-sk/NetAlertX/assets/75147745/8b2a4fd2-bee5-4fe9-9fc0-e6f687c7cec7">

### Expected Behavior

the buttons should be visible

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thanks for reporting this!

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/f290ff6f-70cc-40af-a25b-49c314186564)

Will be fixed in the next release.

**Comment by jokob-sk** [comment]
released 🚀 -> closing
