### ISSUE TITLE
Migrate error

### ISSUE THREAD

**Issue by PrzemekSkw** [jokob-sk/NetAlertX#632]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Pi alert don't work - loading
![image](https://github.com/jokob-sk/NetAlertX/assets/25219988/4c04bd44-e1af-4dc0-9208-3466dc76336a)

Logs:

### Expected Behavior

Start pi.alert

### app.conf

```python
I change container paths
```

### What branch are you running?

Production

### app.log

```
13:48:22 [Plugin utils] display_name: MQTT publisher
13:48:22 [Plugin utils] description: A plugin to publish a notification via the Apprise gateway.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: NTFY publisher
13:48:23 [Plugin utils] description: A plugin to publish a notification via the NTFY gateway.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Pushover publisher
13:48:23 [Plugin utils] description: A plugin to publish a notification via the pushover.net
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Pushsafer publisher
13:48:23 [Plugin utils] description: A plugin to publish a notification via the Pushsafer gateway.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Webhook publisher
13:48:23 [Plugin utils] description: A plugin to publish a notification via Webhooks.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Arp-Scan (Network scan)
13:48:23 [Plugin utils] description: This plugin is to execute an arp-scan on the local network
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: CSV backup
13:48:23 [Plugin utils] description: A plugin to auto-generate devices.csv backups.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: DB cleanup
13:48:23 [Plugin utils] description: A plugin to schedule database cleanup & upkeep tasks.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: DDNS update
13:48:23 [Plugin utils] description: A plugin update the DDNS record.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: DHCP Leases (Device import)
13:48:23 [Plugin utils] description: This plugin is to import devices from dhcp.leases files.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Rogue DHCP
13:48:23 [Plugin utils] description: This plugin is to use NMAP to monitor for rogue DHCP servers.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Internet-Check
13:48:23 [Plugin utils] description: A plugin to check your internet connectivity and IP.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Internet speedtest
13:48:23 [Plugin utils] description: A plugin to perform a scheduled internet speedtest.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Maintenance
13:48:23 [Plugin utils] description: A plugin for maintenance tasks.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: New Devices
13:48:23 [Plugin utils] description: The template used for new devices.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Services & Ports (NMAP)
13:48:23 [Plugin utils] description: This plugin shows all services discovered by NMAP scans.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Notification Processing
13:48:23 [Plugin utils] description: A plugin to for advanced notification processing.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: NSLOOKUP (Name discovery)
13:48:23 [Plugin utils] description: A plugin to discover device names.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Pholus (Name discovery)
13:48:23 [Plugin utils] description: This plugin is to execute a Pholus (name discovery) on the local network
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: PiHole (Device sync)
13:48:23 [Plugin utils] description: This plugin syncs devices from the PiHole database
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Set password
13:48:23 [Plugin utils] description: A simple plugin to set the web ui password on app start.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: SNMP discovery
13:48:23 [Plugin utils] description: This plugin is used to discover devices via the arp table(s) of a RFC1213 compliant router or switch.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Un-Discoverable Devices
13:48:23 [Plugin utils] description: This plugin is to import undiscoverable devices from a file.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: UniFi import
13:48:23 [Plugin utils] description: This plugin is used to import devices from an UNIFI controller.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Vendor update
13:48:23 [Plugin utils] description: A plugin to schedule vendor database updates for mac based vendor resolution.
13:48:23 [Plugin utils] ---------------------------------------------
13:48:23 [Plugin utils] display_name: Website monitor
13:48:23 [Plugin utils] description: This plugin is to monitor status changes of services or websites.
13:48:24 [Plugin utils] ---------------------------------------------
13:48:24 [Plugin utils] display_name: Workflows
13:48:24 [Plugin utils] description: A plugin to adjust behavior of workflows.
13:48:24 [API] Updating table_settings.json file in /front/api
13:48:24 [Config] Imported new config
13:48:24 [API] Updating table_appevents.json file in /front/api
13:48:24 [API] Updating table_devices.json file in /front/api
13:48:24 [API] Updating table_events_pending_alert.json file in /front/api
13:48:24 [API] Updating table_plugins_events.json file in /front/api
13:48:24 [API] Updating table_plugins_history.json file in /front/api
13:48:24 [API] Updating table_plugins_objects.json file in /front/api
13:48:24 [API] Updating table_plugins_language_strings.json file in /front/api
13:48:24 [Database] - SQL ERROR: no such table: Notifications
```

![image](https://github.com/jokob-sk/NetAlertX/assets/25219988/71a7dbe4-2120-4b91-8352-0540a72cbe23)

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thanks for the report,

Can you please try refresh your browser cache or try a different browser?

Can you check if there are any error in the Dev console of your browser? Usually opened by pressing F12:
https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_INVALID_JSON.md

Thanks in advance,
j

**Comment by PrzemekSkw** [comment]
> Thanks for the report,
> 
> Can you please try refresh your browser cache or try a different browser?
> 
> Can you check if there are any error in the Dev console of your browser? Usually opened by pressing F12: https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_INVALID_JSON.md
> 
> Thanks in advance, j

Thanks for fast response.
It works in other browser but have to wait until discover my devices.
Thanks for help.
Regards.

**Comment by PrzemekSkw** [comment]
Hi @jokob-sk it don't find any devices so I have to change also files names?
![image](https://github.com/jokob-sk/NetAlertX/assets/25219988/3cb6c2c3-69f1-4de0-a7c7-f3f532fbe77c)

**Comment by jokob-sk** [comment]
if you rename your old pialert.conf to app.conf it should work. But also check this thread: https://github.com/jokob-sk/NetAlertX/issues/633

**Comment by PrzemekSkw** [comment]
> if you rename your old pialert.conf to app.conf it should work. But also check this thread: #633

Hi, I rename all files and wait but it don't show any devices.
Only container IP device and external IP router.
![image](https://github.com/jokob-sk/NetAlertX/assets/25219988/610c6e18-d497-4a7a-959e-678d85f3f73f)


Regards

**Comment by jokob-sk** [comment]
Hi @PrzemekSkw ,

1. Can you post a screenshot from About > System info > Network hardware
2. Can you post a screenshot of your subnets setting?


If you are using the pihole DB, can you post the error log of the plugin execution, here is a guide how to find the relevant section: 

https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_PLUGINS.md


Thanks,
j

**Comment by PrzemekSkw** [comment]
> Hi @PrzemekSkw ,
> 
> 1. Can you post a screenshot from About > System info > Network hardware
![image](https://github.com/jokob-sk/NetAlertX/assets/25219988/089ca9aa-9106-4fb9-a271-09a1c815272d)

> 2. Can you post a screenshot of your subnets setting?
![image](https://github.com/jokob-sk/NetAlertX/assets/25219988/ecd5dcd0-7168-445e-98c3-d6f99d3cd774)

 
> If you are using the pihole DB, can you post the error log of the plugin execution, here is a guide how to find the relevant section:
> 
> https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_PLUGINS.md
> 
> Thanks, j

I don't use Pihole.
Regards.

**Comment by jokob-sk** [comment]
Hi @PrzemekSkw ,

Can you please verify you are running the container in host network mode? Check these examples for details: https://github.com/jokob-sk/NetAlertX/tree/main/dockerfiles#example-1

Thanks,
j

**Comment by PrzemekSkw** [comment]
> Hi @PrzemekSkw ,
> 
> Can you please verify you are running the container in host network mode? Check these examples for details: https://github.com/jokob-sk/NetAlertX/tree/main/dockerfiles#example-1
> 
> Thanks, j

Thanks, I change from bridge to host network and now start to find devices but I have to search names, icons etc all again :/

Regards.

**Comment by jokob-sk** [comment]
YOu can restore the devices.csv file as per the instructions here: https://github.com/jokob-sk/NetAlertX/blob/main/docs/BACKUPS.md#recovery-1

**Comment by PrzemekSkw** [comment]
> YOu can restore the devices.csv file as per the instructions here: https://github.com/jokob-sk/NetAlertX/blob/main/docs/BACKUPS.md#recovery-1

I try that way but when I try to import csv in Maintance I get error:
![image](https://github.com/jokob-sk/NetAlertX/assets/25219988/6dfb1109-f67e-4537-b52a-079c27441e8d)

as You can see it's in /config folder:

![image](https://github.com/jokob-sk/NetAlertX/assets/25219988/39cd28c6-d75b-4de3-a2c5-ad1b861f57a8)

Regards.

**Comment by PrzemekSkw** [comment]
When I install new NetAlertX container in unraid container paths are: `/home/pi/piaert/config`. When I change them to: `/app/config` I get error:
![image](https://github.com/jokob-sk/NetAlertX/assets/25219988/60cbd5ab-e615-4c89-85e7-f93a2490ec0b)

and NetAlertX don't works at all.
Regards.

**Comment by jokob-sk** [comment]
It looks like the DB file is malformed. I would recommend to start from a new install and restore the devices.csv file and the app.conf file.

**Comment by PrzemekSkw** [comment]
> It looks like the DB file is malformed. I would recommend to start from a new install and restore the devices.csv file and the app.conf file.

I install fresh, remove pialert, pihole and netalertx folders from /appdata/. I backup db.conf, app.conf and devices.csv files. 
Can You tell me do I have to change container paths?
![image](https://github.com/jokob-sk/NetAlertX/assets/25219988/e0ac0b6c-bc51-4a27-a605-7910400611e6)

**Comment by jokob-sk** [comment]
I'm really not familiar with this editing interface. The new internal paths are `/app/config` and `/app/db`. If you can, edit the docker-compose.yml file directly. Here are examples: https://github.com/jokob-sk/NetAlertX/tree/main/dockerfiles#-docker-composeyml-examples

**Comment by PrzemekSkw** [comment]
OK, it work now and I get my devices names etc.
Thanks for help.
Regards.

**Comment by jokob-sk** [comment]
Glad to hear that :)
