### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by Lungshot** [jokob-sk/NetAlertX#634]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

I have followed the instructions on the plugin in the web-ui and also tried running the command inside of the config folder. The password does not change.

### Expected Behavior

The password should change.

### Steps To Reproduce

sandbox-docker:/app/config# /app/back/pialert-cli set_password mynewpass@!!
/app/back/pialert-cli set_password mynewpass@/app/back/pialert-cli set_password 3uyTheseBoots@cd config
grep: /app/back/../config/${CONFFILENAME}: No such file or directory
sed: /app/back/../config/${CONFFILENAME}: No such file or directory
   The hashed password is:
   81a0a249cab171755ccfaea40c6d6323fb4a223c710cf2f45e9f62ba0152a366
grep: /app/back/../config/${CONFFILENAME}: No such file or directory
sed: /app/back/../config/${CONFFILENAME}: No such file or directory

The new password is set

### app.conf

```python
https://pasta.twistedx.tech/upload/falcon-dove-swan
```

### docker-compose.yml

```python
version: "3"
services:
  netalertx:
    container_name: netalertx
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/netalertx-dev:latest" 
    image: "jokobsk/netalertx:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - /mnt/docker_volumes_local/netalertx/config:/app/config
      - /mnt/docker_volumes_local/netalertx/db:/app/db      
      # (optional) useful for debugging if you have issues setting up the container
      - /mnt/docker_volumes_local/netalertx/log:/app/front/log
    environment:
      - TZ=America/Chicago
      - PORT=20211
```

### What branch are you running?

Production

### app.log

https://pasta.twistedx.tech/upload/falcon-fly-parrot

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by Lungshot** [comment]
What I did to workaround:
Run the command to get the hashed password - "/app/back/pialert-cli set_password thepassword"
Stop container
on docker host edit the app.conf - added the password hash. 
Start container
Password changed

**Comment by JackD-01** [comment]
I have the same problem.
Did also try the password pluging in the settings menu.
This also did not change the password.
I am not a programmer so I can not help much, but Lungshot is not the only one with the password problem

**Comment by TheCBiker** [comment]
That didn't work for me using the plugin either and then manually entered the hash into the app.conf

**Comment by mariushosting** [comment]
Same issue here as @JackD-01

**Comment by Mocusolvan** [comment]
I also have the same issue as @JackD-01

**Comment by TheCBiker** [comment]
just tested and works. very good

**Comment by jokob-sk** [comment]
Thank you, @TheCBiker for testing!

**Comment by jokob-sk** [comment]
released -> closing for now
