### ISSUE TITLE
[bug] PiAlert > NetAletX string rename missed

### ISSUE THREAD

**Issue by D3SOX** [jokob-sk/NetAlertX#637]
On the login page it still says Pi-Alert
https://github.com/jokob-sk/NetAlertX/blob/277cfd3a03f29c604165201faea8392054757646/front/index.php#L81

**Comment by jokob-sk** [comment]
Thanks @D3SOX !

Will be fixed in the next release.

**Comment by jokob-sk** [comment]
released -> closing for now
