### ISSUE TITLE
Configuration and DB lost on upgrade

### ISSUE THREAD

**Issue by JumpmanJunior** [jokob-sk/NetAlertX#641]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

I was running NetAlertX with the latest image from 10 days ago. Today I wanted to upgrade to the new latest image. After pulling the new image and restarting the container with the new image all my devices and settings are lost. It looks like the config and DB were reintialized. I was not able to reproduce it with further restarts of the container, so this seems to be caused by the upgrade to the new version.

### Expected Behavior

Keepinh existing configuration and DB.

### What branch are you running?

Dev

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @JumpmanJunior ,

If you have access to the devices.csv and config file you can still recover most of your setup.

Please carefully check these links:

https://github.com/jokob-sk/NetAlertX/blob/main/docs/BACKUPS.md
https://github.com/jokob-sk/NetAlertX/blob/main/docs/MIGRATION.md

If you didn't wipe the volumes you could still have access to the content of those volumes. I recommend ssh into the container and inspecting the old locations.

Please also check this thread for edge cases: #641

I hope this helps.
J

**Comment by JumpmanJunior** [comment]
Luckily it was just a test setup but because of that I do not have a backup or devices.csv.
But the migration instructions seem not to be relevant in my case. 10 days ago I initially installed NetAlertX, so I was already using the new mount points /app/config and /app/db.

**Comment by JumpmanJunior** [comment]
So I think I now know what caused that issue. I configured the docker conatiner with the new mappings but the image I used 10 days ago still used the old paths and therefore the configuration and DB were only saved within the container and got lost when restarting the container.

**Comment by jokob-sk** [comment]
Ah, I see, sorry to hear that - still, if you didn't clean the temporary volumes when removing the container then the files might be still recoverable. I recommend to ssh into the container and inspecting the old locations. It's worth a try I guess. 

Also, the devices.csv file is auto-generated once a week so it might be in the /config folder too. It's worth a shot.

**Comment by cyberbrix** [comment]
I had a similar issue. I cloned my config, made a volume mapping change. When loaded the new container, all my devices were gone.  If I load the old container, the devices and configuration remain. Switch back to the new container, no luck with the devices. I may just rebuild from scratch

**Comment by jokob-sk** [comment]
@cyberbrix 

Please make sure you read the following resources carefully:

https://github.com/jokob-sk/NetAlertX/blob/main/docs/BACKUPS.md
https://github.com/jokob-sk/NetAlertX/blob/main/docs/MIGRATION.md

Please also check this thread for edge cases: https://github.com/jokob-sk/NetAlertX/issues/641

If you have a `devices.csv` and `app.conf` (formerly pialert.conf) files, you can rebuild almost the whole setup without losing any configuration data.

**Comment by jokob-sk** [comment]
Closing the thread - all migration-specific issues will be collated in this thread: https://github.com/jokob-sk/NetAlertX/issues/641
