### ISSUE TITLE
Is it possible to merge / group multiple IPs to one device?

### ISSUE THREAD

**Issue by andreklug** [jokob-sk/NetAlertX#643]
Hi @jokob-sk , I just started testing NetAlertX, this looks impressive! 

In my network there are multiple VLANs, and some devices have interfaces in several VLANs. This leads to many duplicates, so I am wondering if it is possible to merge these together?
Example: My OPNSense Server has an IP in 7 VLANs (192.168.1.1, 192.168.2.1, ... ). Is it possible to have all IP addresses in one device ("gateway")?

Thank you!

**Comment by jokob-sk** [comment]
Hi @andreklug ,

Thanks for using this app!

The devices are identified by MAC so it theoretically doesn't matter how many IPs a device has. All the IPs should be then visible in the respective plugin section (e.g. for ARP-SCAn it would be Device > Plugins> Arp Scan). 

Let me know if you meant something else,
Thanks,
j

**Comment by andreklug** [comment]
Hi @jokob-sk 

I think what you write absolutely makes sense for many setups, especially those not heavily relying on virtualisation. 

I am running dozens of internatl services from diffferent VM hosts. This leads to 130 (currently) interfaces in my network. And NEtAlertX seems the perfect solution to be the single source of truth :) 

![grafik](https://github.com/jokob-sk/NetAlertX/assets/13343357/901ab195-8279-418c-9ae5-4ddd72efe326)

This is an example from my frigate container. There is one interface assigned though Proxmox, and each of them goes into a different VLAN, resulting in different modes / possibilities of access based on network and Firewall routes: 
- end device network (Camera Event)
- proxy backend
- admin network
- IoT / MQTT network
- Camera network

For now, I am naming all devices and add their network, but that feels cumberdsome and I believe that the network view will not be very useful this way once I get there.
From a technical perspective I think the current organisation is fine, and maybe the only thing missing is an organisational entity to group these interface. While we are looking at names (devices) in NetAlertX now, maybe you can add an addition entity "host" that can group them?

Anyway, keep up the great work!

**Comment by jokob-sk** [comment]
Thanks for the additional context!

Maybe I'm missing something and the following doesn't solve your issue. This is how I "group" VMs together, I "attach them" to the host PC. 

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/f68f09f7-0c37-4529-8652-ea4da587a7d8)

If the Host is just a parent "device", then that would still work. 


If the grouping is purely a filtering requirement, you could use the Group field to store any information you want to group your devices under? It's essentially a free-form field so you can ignore the values in the dropdown. 

For context, it's pretty difficult to add a new field into the devices table (I'd have to adjust the column order, CSV export/Import, possibly mapping in the plugins, multi-edit, newdev plugin to name a few places). So if instead it's possible to reuse an existing one to get the desired functionality, then that would be preferred.

**Comment by andreklug** [comment]
Thank you for the explaination. For now I went ahead and added each device individually, adding VLAN information to each name. I will test your approach, and get back if needed.
