### ISSUE TITLE
Special character (#) in Device name returns error on save

### ISSUE THREAD

**Issue by SirAfino** [jokob-sk/NetAlertX#644]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

When updating a Device information, if the name contains a # character (in the example, the name was "Smart Plug (VR #2)"), the save process fails with the following error:

> `Error updating device
>
> UPDATE Devices SET
>                  dev_Name                   = "Smart Plug (VR ",
>                  dev_Owner                  = "",
>                  dev_DeviceType             = "",
>                  dev_Vendor                 = "",
>                  dev_Icon                   = "",
>                  dev_Favorite               = "",
>                  dev_Group                  = "",
>                  dev_Location               = "",
>                  dev_Comments               = "",
>                  dev_Network_Node_MAC_ADDR  = "",
>                  dev_Network_Node_port      = "",
>                  dev_StaticIP               = "",
>                  dev_ScanCycle              = "",
>                  dev_AlertEvents            = "",
>                  dev_AlertDeviceDown        = "",
>                  dev_SkipRepeated           = "",
>                  dev_NewDevice              = "",
>                  dev_Archived               = ""
>           WHERE dev_MAC="**.**.**.**.**.**" 
>
> CHECK constraint failed: dev_Favorite IN (0, 1)`

### Expected Behavior

Device information should be correctly saved

### Steps To Reproduce

1. Edit a Device name adding a # character in the name.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
This should be available in the next release. If you can, please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved.

Thanks in advance,
j

**Comment by jokob-sk** [comment]
released -> closing for now
