### ISSUE TITLE
Add Telegram notification

### ISSUE THREAD

**Issue by PrzemekSkw** [jokob-sk/NetAlertX#647]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I use telegram for notifications for many services. I try to get some notifications in pialert (email, mqtt-homeassistant) but they don't work. I failed with configuration.

### Describe the solution you'd like

Add telegram settings.
Make telegram bot
Set telegram bot token
Set telegram chatID

### Describe alternatives you've considered

mqtt, email

### Anything else?

https://support.crowdin.com/custom-notifications-telegram/#creating-telegram-bot

**Comment by jokob-sk** [comment]
Hi there,

Telegram notifications are supported via Apprise: https://github.com/caronc/apprise/wiki/Notify_telegram

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/07660b11-e8aa-4af3-80b7-22a0a2ae9ded)

Here are also some guides for Gmail/Gmx if you use those for emails: https://github.com/jokob-sk/NetAlertX/blob/main/docs/SMTP.md

Hope this helps,
j

**Comment by PrzemekSkw** [comment]
> Hi there,
> 
> Telegram notifications are supported via Apprise: https://github.com/caronc/apprise/wiki/Notify_telegram
> 
Thanks but that looks too difficult to me. It will be better to add regular telegram notification.
I will try with email one more time.
Regards

**Comment by PrzemekSkw** [comment]
Hi @jokob-sk , I make email notification trough gmail work but it send me unnessesery notifications every 5m to my email about devices change IP or devices are disconnected but don't show me notifications I need - that new device is in my wifi network.
Regards.

**Comment by jokob-sk** [comment]
Hi there,

Glad to hear your notifications are working. 

I wrote up a notification guide to explain how notifications work. Please check it to adjust your settings accordingly:

https://github.com/jokob-sk/NetAlertX/blob/main/docs/NOTIFICATIONS.md

Hope this helps,
j

**Comment by jokob-sk** [comment]
closing as resolved
