### ISSUE TITLE
Question: about online devices showing as offline

### ISSUE THREAD

**Issue by hansw1204** [jokob-sk/NetAlertX#651]
Hi, 
I installed NetAlertX in docker on my Raspberry Pi5 and it works well. However, at all times it shows devices as offline that are clearly online and working as expected. Did I do something wrong with my setup or do I need to change some settings?
Many thanks for any help.
Hans

**Comment by jokob-sk** [comment]
Hi,

Please provide more information so I can help.

1. What scanners do you have enabled?
2. Is the schedule aligned?
3. Is there anything common on devices showing as offline?

Thanks,
j

**Comment by hansw1204** [comment]
Hi,
Thank you for your help!

I have not changed any of the default settings. I am scanning 192.168.7.0/22 on eth0
I have not changed any of the default schedules
All devices that show offline are connected via WiFi (I have an eero setup with 3 eero Pro 6 devices)

Maybe these devices do go offline and reconnect on demand?  The affected IOT devices are always accessible via the Home App.

Thank you again,

Hans

From: jokob-sk ***@***.***>
Date: Wednesday, April 24, 2024 at 17:39
To: jokob-sk/NetAlertX ***@***.***>
Cc: HaWi ***@***.***>, Author ***@***.***>
Subject: Re: [jokob-sk/NetAlertX] Question: about online devices showing as offline (Issue #651)

Hi,

Please provide more information so I can help.

  1.  What scanners do you have enabled?
  2.  Is the schedule aligned?
  3.  Is there anything common on devices showing as offline?

Thanks,
j

**Comment by jokob-sk** [comment]
Could you please share a screenshot of your devices and the app.log for the given scan you enabled? This is the type of output I need to help further: https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_PLUGINS.md

**Comment by jokob-sk** [comment]
Thanks for the logs, this helps a lot.

It seems that you are only using arp-scan and most devices are detected. The issue with arp-scan is that it relies on the arp-scan cache which can be out-of-date. 

To get more accurate results you can try switching to a different scan method. Check the settings for any scan method you'd be able to substitute or complement the correct arp-scan detection, such as PiHole import, SNMP or dhcp.leases. Check the respective settings for details.  

I'm also working on an NMAP device scan #645 which may be more accurate and you can test it in the `netalertx-dev` image.

**Comment by jokob-sk** [comment]
no update for a week > closing for now
