### ISSUE TITLE
vlan entry formatting

### ISSUE THREAD

**Issue by aries223** [jokob-sk/NetAlertX#653]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

1. Documentation shows this:
`['...', '...']`
`SCAN_SUBNETS    = ['192.168.1.0/24 --interface=eth0', '192.168.1.0/24 --interface=eth1 -vlan=107']`
Both of those have a <space> in-between the subnet entries.

These entries from the gui get written to "/config/app.conf" as:
`SCAN_SUBNETS=['192.168.1.0/24 --interface=eth0','192.168.1.0/24 --interface=eth1 -vlan107']`
This does not have a space between the entries.

Which should it be?

Also, in the documentation you show "-vlan107" but in the referenced Issue 170 the screen caps show "--vlan107".

Should it be 1 or 2 dashes?

### Expected Behavior

Gui should write exacty what is entered to the app.conf file.

### Steps To Reproduce

1. Add subnets to GUI
2. Review app.conf

### app.conf

```python
SCAN_SUBNETS=['192.168.1.0/24 --interface=eth0','192.168.20.0/24 --interface=eth0 -vlan20']
```

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi there,

If you use the UI it will correctly auto-format the app.conf file. 

I did a quick test and it seems like both `--vlan=` and `-vlan=` work, plainly using `vlan=` doesn't:

```bash
Synology-NAS:/# sudo arp-scan 192.168.1.0/24 --interface=eth0 -vlan=107
Interface: eth0, type: EN10MB, MAC: 00:11:32:ef:a5:6b, IPv4: 111.111.39.252
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)

0 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.10.0: 256 hosts scanned in 2.035 seconds (125.80 hosts/sec). 0 responded
Synology-NAS:/# sudo arp-scan 192.168.1.0/24 --interface=eth0 --vlan=107
Interface: eth0, type: EN10MB, MAC: 00:11:32:ef:a5:6b, IPv4: 111.111.39.252
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)

0 packets received by filter, 0 packets dropped by kernel
Ending arp-scan 1.10.0: 256 hosts scanned in 2.047 seconds (125.06 hosts/sec). 0 responded
Synology-NAS:/# sudo arp-scan 192.168.1.0/24 --interface=eth0 vlan=107
Interface: eth0, type: EN10MB, MAC: 00:11:32:ef:a5:6b, IPv4: 111.111.39.252
WARNING: get_host_address failed for "vlan=107": Name does not resolve - target ignored
Starting arp-scan 1.10.0 with 256 hosts (https://github.com/royhills/arp-scan)
```

I will update the documentation to remove the space between `['...','...']` to remove confusion.

Hope this helps,
j

**Comment by aries223** [comment]
I cannot get it to scan vlans no matter what I do..

**Comment by jokob-sk** [comment]
I would suggest to ssh into the container and try arp-scan directly, then once you verify which parameters work, replicate them in settings.

Make sure:

1. Your container runs in host network mode
2. You use the correct network masks
3. You use the correct network interface/adapter

I don't use vlans so I can't provide more specific examples. However, you might find some closed issues where people setup vlan scans successfully.

Hupe this helps a bit,
j

**Comment by aries223** [comment]
I created a Discussion for this. Would appreciate if you could help me there.. and you can close this

#654
