### ISSUE TITLE
Bind mounts end up owned by systemd-resolve

### ISSUE THREAD

**Issue by tomkessler** [jokob-sk/NetAlertX#656]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

I'm just getting started with NetAlertX.  I've used the basic docker compose from the docs.  Strangely, the bind mounted folders are getting owned by "systemd-resolve" (UID=101 on my Ubuntu 20.04 system) when I start the container.  That doesn't seem right.  When I exec into the container, it seems to be running as root (UID=0).

<img width="444" alt="image" src="https://github.com/jokob-sk/NetAlertX/assets/20233788/bb034519-8c8d-4f8f-9910-24a67042c7df">

### Expected Behavior

I'd expect the folders to be owned by root.

### docker-compose.yml

```python
version: "3"
services:
  netalertx:
    container_name: netalertx
    image: jokobsk/netalertx:latest
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    volumes:
      - ./netalertx/db:/app/db
      - ./netalertx/config:/app/config
      - ./netalertx/etc/resolv.conf:/etc/resolv.conf
      # (optional) useful for debugging if you have issues setting up the container
      - ./netalertx/logs:/app/front/log
    network_mode: host
```

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by vladaurosh** [comment]
Those files are owned by nginx:www-data inside the container, as web server is nginx. id of that user is 101 and group id is 82.

**Comment by jokob-sk** [comment]
probably duplicate: #652

**Comment by jokob-sk** [comment]
closing as duplicate
