### ISSUE TITLE
Database] - SQL ERROR: no such table: Notifications

### ISSUE THREAD

**Issue by brunomgrocha** [jokob-sk/NetAlertX#658]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Deploying error with the message. Database] - SQL ERROR: no such table: Notifications

### Expected Behavior

No error

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi there,

1. Could you please double-check check you have a database mapped in the correct location?
2. If yes, can you try to restart the container?
3. If above doesn't work, can you provide the app.log in debug mode?

Thanks,
j

**Comment by brunomgrocha** [comment]
Ok i restart the container and it works, but for somehow the network scanner is not find anything on the network, only the machine itself

**Comment by jokob-sk** [comment]
Please reread the setup instructions. You are probably not running the container in host mode or subnets are not specified correctly.

**Comment by jokob-sk** [comment]
Original issue solved so closing for now
