### ISSUE TITLE
UniFi Import plugin settings are not reflected in UI overview of Enabled Scanners

### ISSUE THREAD

**Issue by curt7000** [jokob-sk/NetAlertX#663]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Disabling Plugin doesn't remove from Enabled Scanners in UI.

When using the plugin, settings changed in plugin are not reflected in UI overview of Enabled Scanners.  For example, changing UniFi Import plugin to "Schedule" is not reflected in UI overview of Enabled Scanners, still lists as "Always After Scan".

### Expected Behavior

Disabling the Plugin should remove from list of Enabled Scanners.  Changing the plugin settings should be reflected in list of Enabled Scanners.

### Steps To Reproduce

1. Enable/Disable UniFi Import plugin
2. Save
3. Plugin is not removed from UI overview of Enabled Scanners

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
This should be available in the next release. If you can, please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved.

Thanks in advance,
j

**Comment by curt7000** [comment]
> This should be available in the next release. If you can, please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now.
> 
> It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved.
> 
> Thanks in advance, j

Gave it a go, but there doesn't appear to be any settings available to change in the Plugin Settings.

**Comment by jokob-sk** [comment]
This should happen automatically after you safe the settings. If you have
issues displaying setting, please post a screenshot and the dev console log.

Try also refreshing the page with the button in the top right corner.

**Comment by jokob-sk** [comment]
released -> closing for now
