### ISSUE TITLE
It would be nice to have a snap version

### ISSUE THREAD

**Issue by sbe-arg** [jokob-sk/NetAlertX#666]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

N/A

### Describe the solution you'd like

Installing as snap package/app

### Describe alternatives you've considered

Continue using the docker version.

### Anything else?

I have a bunch of snaps with auto backups and this would be a nice addition.

**Comment by jokob-sk** [comment]
Hey @sbe-arg ,

I'm happy for someone to submit a PR, but I don't have currently the bandwidth to support 3 installation methods. Sometimes, it's already overwhelming with the current amount of work, feature requests, and continuous improvements.  It would be different if I had at least one day to dedicate to this project, but currently it's not making me any money 😅 

Hope that makes sense,
thanks, 
j

**Comment by sbe-arg** [comment]
Yes totally understandable. I just opened the issue for the future in case any contributors want to do a snap.

**Comment by jokob-sk** [comment]
Backlog item
