### ISSUE TITLE
Settings Page Submenus are broken after release 24.4 for jokobsk/netalertx repo

### ISSUE THREAD

**Issue by zilvernet** [jokob-sk/NetAlertX#668]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

The Expand option for example on Devices Scanners is empty, so you can't configure anything.

![image](https://github.com/jokob-sk/NetAlertX/assets/75147745/e4bd3fb1-7022-413b-9e6e-b7c6455fa714)

### Expected Behavior

This is on version 24.4

![image](https://github.com/jokob-sk/NetAlertX/assets/75147745/7c81d772-5019-4e71-bb8c-c470e36bb933)

### docker-compose.yml

```python
version: "3"
services:
  netalertx:
    container_name: alert
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/netalertx-dev:latest"
    image: "jokobsk/netalertx:${NETALERTX_TAG:-latest}"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - ${APP_DATA_LOCATION:-/docker_data}/netalertx/config:/app/config
      - ${APP_DATA_LOCATION:-/docker_data}/netalertx/db:/app/db     
      # (optional) useful for debugging if you have issues setting up the container
      - ${APP_DATA_LOCATION:-/docker_data}/netalertx/log:/app/front/log
    environment:
      - TZ=${TZ:-America/New_York}      
      - PORT=${PORT:-20211}


NETALERTX_TAG = latest
```

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi there,

Could you please try to download the latest version and clear the browser cache and it's the refresh button in the top right corner?

**Comment by jokob-sk** [comment]
I will try to automate it, but yes, if you encounter similar issues, try refreshing the cache. Thanks for your patience.
