### ISSUE TITLE
[MQTT] Presence sensor type not set correctly

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/NetAlertX#671]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

The sensor type setting is not taken into account

### Expected Behavior

Be able to change the sensor type and for it to be reflected

### Steps To Reproduce

1. Save settings
2. Sensor type will be blank

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Possible workaround (to be confirmed):

Insert 

`PRESENCE_SENSOR_TYPE='device_tracker'`

or 

`PRESENCE_SENSOR_TYPE='binary_sensor'`

into your `app.config`, alternatively, try to download the `netalertx-dev` image and re-save the settings.

**Comment by iLeoLion** [comment]
Switched to the netalertx-dev image, re-applied settings and now it created the binary_sensor.
HomeAssistant picked up the data.


Thanks!

**Comment by jokob-sk** [comment]
closing -> releasing in ~10min
