### ISSUE TITLE
No web interface...

### ISSUE THREAD

**Issue by adm2k** [jokob-sk/NetAlertX#674]
Just installed and can't seem to get the web interface to show. 

docker ps show the container running but no port information.

The log file show no issues

here is my .yaml
services:
   netalertx:
      container_name: netalertx
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/netalertx-dev:latest" 
    image: "jokobsk/netalertx:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - ./netalert/config:/app/config
      - ./netalert/db:/app/db      
      # (optional) useful for debugging if you have issues setting up the container
      #- local/path/logs:/app/front/log
    environment:
      - TZ=America/New-York      
      - PORT=20211

any help is appreciated!

**Comment by jokob-sk** [comment]
Hi there,

Please double check your timezone or try to use the default value or a default compose file

Thanks,
J

**Comment by adm2k** [comment]
@jokob-sk 

I checked the time zone a couple of times it is America/New-York

The compose file is one of the samples on your site.

Any other ideas?

**Comment by jokob-sk** [comment]
I think it's an underscore https://en.m.wikipedia.org/wiki/America/New_York

Can you please point me where you copied it from if that's the case?

**Comment by adm2k** [comment]
I just checked and it is with an underscore America/New_York

I have tried every example for the yaml at this location and none seem to work 
https://github.com/jokob-sk/NetAlertX/blob/main/dockerfiles/README.md

**Comment by adm2k** [comment]
Update...

I was able to get it running this:
docker run -d --rm --network=host   -v "/$(pwd)/netalertx/config:/app/config"   -v "/$(pwd)/netalertx/db:/app/db"   -e TZ=America/New_York   -e PORT=20211   jokobsk/netalertx:latest

**Comment by adm2k** [comment]
@jokob-sk 

Well now that it is running I guess my next question is where are all my connections? I have been reading thought the assorted documentation and can't seem to find the answer.

I am seeing only the IP for the Internet and this is the IP of the Proxmox Container that I am running this on.

**Comment by adm2k** [comment]
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/3d641bc4-7dd6-49bc-85bf-4945f26de4c1)

@jokob-sk 

This is from the config file:
SCAN_SUBNETS=['192.168.1.0/24 --interface=eth1','192.168.1.0/24 --interface=vmbr0','192.168.1.0/24 --interface=eth0']
SCAN_SUBNETS__metadata="{}"

Sorry to be such trouble...

**Comment by jokob-sk** [comment]
I highly recommend to configure the app via the UI as it links to corresponding docs. For subnets it seems you don't have the correct mask,potentially the interface. Please read this for details: https://github.com/jokob-sk/NetAlertX/blob/main/docs/SUBNETS.md

**Comment by jokob-sk** [comment]
Hey, 

Can you post a screenshot from here?

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/7add1f8c-da3b-48db-97bf-d782f4330db6)

This should give you the right interface and network mask.

**Comment by adm2k** [comment]
here is my current:
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/e8ea3ae8-299b-4e8d-8ade-9fea62d60fe2)

**Comment by adm2k** [comment]
192.168.86.24 is the IP of the Proxmox container I am running this on

**Comment by jokob-sk** [comment]
this means that your mask probably is `192.168.86.0/24`, and interface `eth0` , not `SCAN_SUBNETS=['192.168.1.0/24 --interface=eth1','192.168.1.0/24 --interface=vmbr0','192.168.1.0/24 --interface=eth0']`

**Comment by adm2k** [comment]
OK, updated to 192.168.86.0/24 with eth0 and it is working! But, when I look I see it is getting changed to 192.168.86.24/24

![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/d39541c9-69da-4afe-814f-82b6defade5a)

**Comment by jokob-sk** [comment]
Make sure you clear your browser cache - use the 🔃 button in the top right corner - or try a different browser. You can double-check the app.conf file what gets saved.

**Comment by adm2k** [comment]
Cleared the cash and checked the config file as well. Seems like it somehow is changing back to 192.16.86.24/24

![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/0c368d73-7eb2-4a21-93e6-a478339fcac8)

**Comment by jokob-sk** [comment]
In that case that might be related with something going on on your file system - not sure if you are running some backup scripts or similar. I'm unaware of any function updating the config file other than the SAVE button in the settings. 

You can always post the full app.log with debug enabled as described here: https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_TIPS.md

**Comment by adm2k** [comment]
I think we can close this for now. Many thanks for your help! It is appreciated...

**Comment by joel72265** [comment]
Thank you for the reply.

I used the -e variable 'ALWAYS_FRESH_INSTALL' before to cleanup my previous install but now did a clean install and ran the command without this variable, 

1) the install path is valid
2) nginx is running (screenshot attached)
3) the browser console does not show any errors (Chrome > Developer tools)
4) logs attached


![netalertx-01](https://github.com/jokob-sk/NetAlertX/assets/118885352/0ea261f7-32d9-4c5c-b995-45dc78d6708a)
[docker logs netalertx-11June.txt](https://github.com/user-attachments/files/15782985/docker.logs.netalertx-11June.txt)

**Comment by joel72265** [comment]
netalertx is the only container running on the box with its unique IP :( 

I should've thought of trying another port myself but still nothing (screenshot attached), I will keep testing at my end
![netalertx-02](https://github.com/jokob-sk/NetAlertX/assets/118885352/574364c6-f09f-4ad4-893c-32ea7a4eeb13)
