### ISSUE TITLE
Icons gone after import of csv

### ISSUE THREAD

**Issue by killtux** [jokob-sk/NetAlertX#675]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

why i import the csv the devices show up but has some strange values for icon names - no icons show up.

### Expected Behavior

devices get imported with the icons the used before.

### Steps To Reproduce

![image](https://github.com/jokob-sk/NetAlertX/assets/36768145/9e57ef52-7624-4af8-98e0-56782be78e70)

### docker-compose.yml

```python
services:
  pialert:
    container_name: netalertx
    image: "jokobsk/netalertx:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./db:/app/db
      # (optional) useful for debugging if you have issues setting up the container
      - ./log:/app/front/log
#      - ./api:/app/front/api
    environment:
      - TZ=Europe/Berlin
#      - HOST_USER_ID=1000
#      - HOST_USER_GID=1000
      - PORT=20211
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @killtux ,

Thanks for filling in the details.

I don't see any error in your screenshot, the icon seems to be displayed correctly:

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/737802ce-63e9-4d0a-8ccb-5625330729ce)

The way icons are handled has changed 2 releases ago. Please read more in the updated icons docs: https://github.com/jokob-sk/NetAlertX/blob/main/docs/ICONS.md

**Comment by killtux** [comment]
> I don't see any error in your screenshot, the icon seems to be displayed correctly:
> 

no the notebook icon is the standard icon that shows up. but at the overview no icons are displayed. the printed hat the printer icon.

also all devices appear as offline and the last ip is also a strange negative value:
![image](https://github.com/jokob-sk/NetAlertX/assets/36768145/3eda5bbd-aec8-4a3c-b145-51272eac873a)

i think something happend when importing the csv.

i updated today and wanted to access the backup. then i noticed paths were changed as the app got renamed. i changed it but i cannot access the folders without sudo (so i cant pull a backup via winscp). somehow the db got messed up and all my devices (100+) where gone. also there wasnt an option to import from backup (i made before). but the import csv worked - but devices offline, parent nodes gone and icons are not showing up.

**Comment by jokob-sk** [comment]
Sorry to hear that,

As per https://github.com/jokob-sk/NetAlertX/blob/main/docs/MIGRATION.md#migration-form-pialert-to-netalertx have you tried the following?

> If you have troubles accessing past backups, config or database files you can copy them into the newly mapped directories, for example by running this command in the container: cp -r /app/config /home/pi/pialert/config/old_backup_files. This should create a folder in the config directory called old_backup_files conatining all the files in that location. Another approach is to map the old location and the new one at the same time to copy things over.

Since you have the devices.csv most of your device config should be fine. You will also need the app/pialert.conf to get the scanners up. 

If you have only the devices.csv file you can always remove the icons manually and import the csv file without the icons. Use nano or notepad++ to preserve file endings. 

Hope the above helps.

**Comment by killtux** [comment]
yeah i changed directories to the new format but i got some problems accessing them. is it possible that the app changes the permission so i can't access it from the user thats part of the docker group?

i also cant access over winscp the files to upload the devices.csv
![image](https://github.com/jokob-sk/NetAlertX/assets/36768145/960cc906-e52d-45a8-9fc9-9df25665d820)

the version in the config dir is from feb last year, so maybe thats the reason it got messed up.

would be could if there would be a upload/download option in the webif instead of only writing it into the container.

**Comment by jokob-sk** [comment]
Glad to hear you solved the issue! I'll consider the feature request for the future. 

See this for a discussion about permissions https://github.com/jokob-sk/NetAlertX/issues/652 

For now I'm closing this as resolved.
