### ISSUE TITLE
Add option to execute script on_notification

### ISSUE THREAD

**Issue by Floo33R** [jokob-sk/NetAlertX#677]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [ ] Yes
- [X] No

### Is your feature request related to a problem? Please describe

I want to get the notifications via Gotify without any workarounds.

### Describe the solution you'd like

Either a native Gotify support would be great or the option to execute a script, when a new device is added. Then everybody is able to create any action out of it.

### Describe alternatives you've considered

Switch to a different notification provider, but i use Gotify for everything.

### Anything else?

The option to execute something like this:
```
GOTIFY_URL=xxxxxx
GOTIFY_TOKEN=xxxxxx

title="Netalertx New Device Notification"
message="Device xxx was added...."

curl_http_result=$(curl "${GOTIFY_URL}/message?token=${GOTIFY_TOKEN}" -F "title=${title}" -F "message=${message}" -F "priority=5" --output /dev/null --silent --write-out %{http_code})
```

**Comment by jokob-sk** [comment]
Hi there,

NetAlertX supports apprise, which has a gotify plugin. Could you please give it a go?

https://github.com/caronc/apprise/wiki/Notify_gotify

**Comment by Floo33R** [comment]
Hi, 
the thing is i do not want to have several services running, which are doing the same in the end. That's why the idea with the script came up. 
If this is not possible, i have to do it over the apprise of course :D

**Comment by jokob-sk** [comment]
Hi,

Thanks for the reply. 

I have to be selective about feature requests and certainly can't implement every notification service that's out there. I am single person and supporting this app is already taking a lot of time, so I need to focus on core functionality. 

You can always submit new plugins and I can accept a PR, but I would expect some level of ongoing support for the PR, for example when people report bugs. 

Check out how to create a custom plugin if you are interested: https://github.com/jokob-sk/NetAlertX/blob/main/front/plugins/README.md

Hope this makes sense,
Thanks,
j

**Comment by jokob-sk** [comment]
Workaround provided -> Closing for now (might revisit in the future)

**Comment by Floo33R** [comment]
Hi,
i totally understand that. 
I will give it a shot, for now I am using the SMTP Version.

Thanks!
