### ISSUE TITLE
On HW script fails on Pi Zero 2

### ISSUE THREAD

**Issue by bobybobybob** [jokob-sk/NetAlertX#679]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

it does not install the programm

### Expected Behavior

it install the program

### Steps To Reproduce

1. Pi Zero 2 with current PI-OS 
2. curl -o install.debian.sh https://raw.githubusercontent.com/jokob-sk/NetAlertX/main/install/install.debian.sh && sudo chmod +x install.debian.sh && sudo ./install.debian.sh

root@zero2:/home/pipi# curl -o install.debian.sh https://raw.githubusercontent.com/jokob-sk/NetAlertX/main/install/install.debian.sh && sudo chmod +x install.debian.sh && sudo ./install.debian.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1054  100  1054    0     0   2873      0 --:--:-- --:--:-- --:--:--  2871
---------------------------------------------------------
[INSTALL]                           Run install.debian.sh
---------------------------------------------------------
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://archive.raspberrypi.com/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
sudo is already the newest version (1.9.13p3-1+deb12u1).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.39.2-1.1).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
rm: cannot remove '/app/': No such file or directory
Cloning into '/app'...
remote: Enumerating objects: 30390, done.
remote: Counting objects: 100% (1504/1504), done.
remote: Compressing objects: 100% (409/409), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 21124 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
./install.debian.sh: line 34: /app/front/buildtimestamp.txt: No such file or directory
./install.debian.sh: line 38: /app/install/start.debian.sh: No such file or directory

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi there,

I haven't tested the install script for a while. The recommended installation approach is docker.

I'll try to have a look at the script in a couple of weeks, but it's mostly a feature supported by the community. I'm happy for you to submit a PR if you can help out.

Thanks in advance,
J

**Comment by bobybobybob** [comment]
OK i try docker on the little pi zero 2

example does not work

root@zero2:/home/pi# docker run -d --rm --network=host -v local/path/config:/app/config -v local/path/db:/app/db  -e TZ=Europe/Berlin   -e PORT=20211   jokobsk/netalertx:latest
docker: Error response from daemon: create local/path/config: "local/path/config" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

that have worked

root@zero2:/home/pi# docker run -d --rm --network=host -v ./local/path/config:/app/config -v ./local/path/db:/app/db  -e TZ=Europe/Berlin   -e PORT=20211   jokobsk/netalertx:latest
6023cc214e4703a0d66bbc2136031585484ae530baeab683608abb1004c0457e
root@zero2:/home/pi#


A Pi Zero 2 is probably not powerful (512 MB RAM) enough for the programme + docker. I don't like Docker. Tried it with Docker anyway. Everything is very slow and the message loading constantly. It also can't find any other network devices, probably due to my incorrect settings with Docker. I'll leave it, I was just curious whether the programme is something for me or whether it's too complicated.
