### ISSUE TITLE
Help with down_alerts...

### ISSUE THREAD

**Issue by adm2k** [jokob-sk/NetAlertX#680]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

The values displayed for down & offline **is correct**:
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/7d1f3970-645b-4eff-8e65-338321d05ff5)

The issue seems to be with the Homepage widget (which they say they have nothing to do with as far as getting values).
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/e68f9c9b-1438-408e-94a6-dd01b8d95aeb)

The value is never displayed. According to the widget configuration the values it is collecting are:
Allowed fields: ["total", "connected", "new_devices", "down_alerts"].

I don't see any of those values in the 192.168.xx.xx:20211/api/table_devices.json

So, where are they coming from? What can be done to correct?

Many thanks!

### Expected Behavior

display a Down value

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi there,
I'm not sure what api the widget is using. - please contact the developer of the Homepage application as I'm not the author of the plugin.

**Comment by leiweibau** [comment]
I think, it is this request
https://github.com/gethomepage/homepage/blob/main/src/widgets/netalertx/widget.js

**Comment by adm2k** [comment]
@leiweibau 

Thank you for the response. Unfortunately my skills in this are limited. What is {url} referring to? On my server? 
 api: "{url}/php/server/devices.php?action=getDevicesTotals",

**Comment by leiweibau** [comment]
This was meant more as a help for @jokob-sk.

**Comment by adm2k** [comment]
Sorry...

For what it's worth, sometime I will see a value of 1 in down alerts, most of the time 0 yet in NetAlertx I have 6 or 7

**Comment by leiweibau** [comment]
You can try to open this url in your browser and see, what netalertx will return
ˋhttp://192.168.xx.xx:20211/php/server/devices.php?action=getDevicesTotalsˋ (or maybe https)

**Comment by leiweibau** [comment]
First of all, one thing in advance. "Offline" does not mean "down" here. "Down" are devices for which a "Down" notification is configured.

If I have skimmed through this correctly, then we have the following situation. The "API" returns the correct data for the individual statuses. However, the frontend shows "Down" and "Offline" together in the field.

I don't see this as a classic bug. It would certainly be easier if the adjustment were made on the widget side.

**Comment by adm2k** [comment]
@leiweibau 

Thanks for the clarification, this makes sense now.

**Comment by jokob-sk** [comment]
I'll think about moving the offline count somewhere else as it's causing confusion. Thanks @leiweibau for helping explain this 🙏

Closing as resolved now
