### ISSUE TITLE
PHOLUS_DAYS_DATA error causes reboot

### ISSUE THREAD

**Issue by cyberbrix** [jokob-sk/NetAlertX#681]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

NetAlertX restarts every 30 minutes

17:02:03 [Settings] ⚠ ERROR - setting_missing - Setting not found for key: PHOLUS_DAYS_DATA in file /app/front/api/table_settings.json

### Expected Behavior

Should not reboot every 30 minutes

### Steps To Reproduce

No specific actions

### app.conf

```python
app.conf was causing errors posting
```

### docker-compose.yml

```python
docker run -d --network=host --name=netalertx \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/internet_ip/ignore_plugin \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/_publisher_email/ignore_plugin \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/ddns_update/ignore_plugin \
-v /volume1/docker/netalertx/db:/app/db \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/_publisher_webhook/ignore_plugin \
-v /volume1/docker/netalertx/config:/app/config \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/dhcp_servers/ignore_plugin \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/_publisher_apprise/ignore_plugin \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/dhcp_leases/ignore_plugin \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/_publisher_ntfy/ignore_plugin \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/csv_backup/ignore_plugin \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/_publisher_mqtt/ignore_plugin \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/internet_speedtest/ignore_plugin \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/_publisher_pushsafer/ignore_plugin \
-v /volume1/docker/netalertx/logs:/app/front/log \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/website_monitor/ignore_plugin \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/unifi_import/ignore_plugin \
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/pholus_scan/ignore_plugin
-e TZ=America/New_York \
-e PORT=20212 \
jokobsk/netalertx:latest
```

### What branch are you running?

Production

### app.log

[app.log](https://github.com/jokob-sk/NetAlertX/files/15417432/app.log)

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi there,

I think there is a dependency between Pholus and the DB Cleanup plugin - I will try to remove it in the future. For now, removing this line from your compose should fix it:

```
-v /volume1/docker/netalertx/ignore_plugin:/app/front/plugins/pholus_scan/ignore_plugin
```

**Comment by jokob-sk** [comment]
This should be available in the next release. Please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the issue was resolved.

Thanks in advance,
j

**Comment by cyberbrix** [comment]
So it looks like it corrected the reboot, but the Pholus plugin is still enabled even though I put an ignore file.

**Comment by jokob-sk** [comment]
You need to switch it do `disabled`, only then it will get removed.

**Comment by jokob-sk** [comment]
closing -> releasing in ~10min
