### ISSUE TITLE
Sorry for what may be a simple question

### ISSUE THREAD

**Issue by adm2k** [jokob-sk/NetAlertX#682]
When selecting an item if it is highlighted is it selected? In the screenshot below Tile Cards are not selected but Device Presence is?  

![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/64bd7922-e9b3-486f-b6ff-4e3d4cc699a1)

Having some issues getting things working and want to make sure.

Thanks!

**Comment by jokob-sk** [comment]
Yes, that is correct.
