### ISSUE TITLE
Not getting email

### ISSUE THREAD

**Issue by adm2k** [jokob-sk/NetAlertX#683]
I have NetAlertX configured to send email on New and Down alerts. In testing I have a device that has been down for close to 45 minutes and no email. I have tested email before and it works correctly.

![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/4264d8e4-c5bd-41eb-8bb6-15f7c6a837ba)

![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/10af7ec7-30fc-4878-9938-176971eee0d5)

![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/35f85a37-bb68-477d-8760-fcf58e820202)

Any help is appreciated!

**Comment by jokob-sk** [comment]
Try setting Alert Down after to multiplies of your scan cycle, e.g. I have 5 minutes scan cycles and have ALrt DOwn After set to 10:

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/4b374a1e-a80d-4ed1-a4ad-e443171eb450)

**Comment by adm2k** [comment]
Here is the latest...

1 - Per your suggestion I set Alert Down After to 10
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/e8daef22-aa61-4fb1-9405-6c3d208b22b3)

2 - Shut down server at 08:20AM

3 - NetAlertX device page for this device shows down
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/c380e10d-4060-41aa-865b-d57ca62d060a)

4 - ...20211/php/server/devices.php?action=getDevicesTotals
show this [35,25,0,0,**1**,0] shows down

5 - As of 9:00AM  no email

**Comment by jokob-sk** [comment]
The down alert it sent only first time the device is detected as down, not continuously. I have a Down device alert configured which triggers every day without issues, here is the setup:
![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/5b2d468c-c197-40b4-9935-7ce4278f2992)
![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/d1e495a0-d859-435f-b7d9-eb9c524b298a)

Presence

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/1ab12a75-0a14-4be1-a5f4-77de09d16a36)

Example down alert:

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/d2be691c-ebae-4afa-8ee1-046f181628b1)

**Comment by adm2k** [comment]
OK, I think the issue is resolved. Seems like checking the box is the key.
![image](https://github.com/jokob-sk/NetAlertX/assets/120423301/65798769-55f1-47cd-a4fd-524951d3fca8)

Thanks for your help and patience!

**Comment by jokob-sk** [comment]
Glad it's resolved -> Closing
