### ISSUE TITLE
[NOTE] Check regex processing in python in alpine 3.20

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/NetAlertX#691]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

netalertx-1  | /app/server/helper.py:391: SyntaxWarning: invalid escape sequence '\.'
netalertx-1  |   ipRegex = "^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$"
netalertx-1  | /app/server/helper.py:667: SyntaxWarning: invalid escape sequence '\s'
netalertx-1  |   input = bytes_to_string(re.sub('[^a-zA-Z0-9-_\s]', '', str(input)))
netalertx-1  | /app/server/helper.py:699: SyntaxWarning: invalid escape sequence '\s'
netalertx-1  |   value = bytes_to_string(re.sub('[^a-zA-Z0-9-_\s]', '', str(input)))

20:18:29 [PHOLUS]/app/front/plugins/pholus_scan/pholus/pholus3.py:79: SyntaxWarning: invalid escape sequence '\s'
  value = b_to_str(re.sub('[^a-zA-Z0-9-_\s]', '', str(input)))
20:18:29 [PHOLUS] ⚠ ERROR - Pholus Scan - check logs
20:18:29 [PHOLUS] Scan: Pholus FAIL - check logs
20:18:29 [PHOLUS] [['eth0 [192.168.1.0/24](http://192.168.1.0/24)', ...
20:18:30 [Plugins] SUCCESS, received 6 entries

### Expected Behavior

No errors

### What branch are you running?

Dev

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by vladaurosh** [comment]
Just a note here @jokob-sk , python version inAlpine 3.20 is 3.12.x, was 3.11.x in 3.19, so these warnings could be related to that.

**Comment by jokob-sk** [comment]
Should be working fine, couldn't reproduce after rebase > closing
