### ISSUE TITLE
Add samba name to device discovery

### ISSUE THREAD

**Issue by frazei** [jokob-sk/NetAlertX#693]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [ ] Yes
- [X] No

### Is your feature request related to a problem? Please describe

Many devices on my network are marked as '(name not found)', while in other network scans (such as Debookee and Fing), they are identified via NetBIOS/WINS/SMB.

### Describe the solution you'd like

Use **nbstat** script for nmap or **nmblookup** to get device name

### Describe alternatives you've considered

Don't know

### Anything else?

https://nmap.org/nsedoc/scripts/nbstat.html
https://unix.stackexchange.com/questions/170431/how-to-get-netbios-name-from-ip

**Comment by jokob-sk** [comment]
Hi there,

Thansk for teh sugegstion.  Have you checked this guide?

https://github.com/jokob-sk/NetAlertX/blob/main/docs/REVERSE_DNS.md

**Comment by jokob-sk** [comment]
Hi @frazei ,

I looked into this briefly and according to this article the equivalent to `nbstat` is `nslookup`, which is already available as a plugin: https://www.geeksforgeeks.org/nbtstat-commnd-in-linux/

However, it makes probably sense to support NetBIOS lookup. 

I create a NBTSCAN plugin taht should be available in the next release. Please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

👉If I don't get a confirmation that this is working I might pull out the feature to prevent bugs. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

It would be great if you could test this (backup everything first or use a new container) on your end by switching to the above image and letting me know if the new feature is working.

⭐ This feature took 2h ⏳ to implement - consider becoming a sponsor or sharing the app on socials⭐

Thanks in advance,
j

**Comment by frazei** [comment]
Hi @jokob-sk, I am testing the netalertx-dev image and the NBTSCAN plugin as you suggested. So far, it seems to be working correctly. I'll let it run for a while to see if it can detect new devices.

**Comment by jokob-sk** [comment]
Releasing -> closing
