### ISSUE TITLE
Error install on server hardware (debian 12 proxmox container)

### ISSUE THREAD

**Issue by eriklysoe** [jokob-sk/NetAlertX#694]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

root@NetAlertX:~# wget https://raw.githubusercontent.com/jokob-sk/NetAlertX/main/install/install.debian.sh -O install.debian.sh && chmod +x install.debian.sh && ./install.debian.
sh
--2024-06-03 10:24:23--  https://raw.githubusercontent.com/jokob-sk/NetAlertX/main/install/install.debian.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1054 (1.0K) [text/plain]
Saving to: 'install.debian.sh'

install.debian.sh                            100%[============================================================================================>]   1.03K  --.-KB/s    in 0s      

2024-06-03 10:24:24 (14.3 MB/s) - 'install.debian.sh' saved [1054/1054]

---------------------------------------------------------
[INSTALL]                           Run install.debian.sh
---------------------------------------------------------
Hit:1 http://security.debian.org bookworm-security InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
sudo is already the newest version (1.9.13p3-1+deb12u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.39.2-1.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
rm: cannot remove '/app/': No such file or directory
Cloning into '/app'...
remote: Enumerating objects: 30846, done.
remote: Counting objects: 100% (1960/1960), done.
remote: Compressing objects: 100% (635/635), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 588 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
./install.debian.sh: line 34: /app/front/buildtimestamp.txt: No such file or directory
./install.debian.sh: line 38: /app/install/start.debian.sh: No such file or directory
root@NetAlertX:~# 

### Expected Behavior

I removed sudo in installation script since there is no sudo in debian root.
wget https://raw.githubusercontent.com/jokob-sk/NetAlertX/main/install/install.debian.sh -O install.debian.sh && chmod +x install.debian.sh && ./install.debian.sh

Something wrong with the /app directory?

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by eriklysoe** [comment]
> > Hi there,
> > I haven't tested the install script for a while. The recommended installation approach is docker.
> > I'll try to have a look at the script in a couple of weeks, but it's mostly a feature supported by the community. I'm happy for you to submit a PR if you can help out.
> > Thanks in advance, J
> 
> See this for details:
> 
> [#679 (comment)](https://github.com/jokob-sk/NetAlertX/issues/679#issuecomment-2120403843)

I would be glad to help, but unfortunately I can’t code. I install  it using docker 😁

**Comment by vladaurosh** [comment]
> > > Hi there,
> > > I haven't tested the install script for a while. The recommended installation approach is docker.
> > > I'll try to have a look at the script in a couple of weeks, but it's mostly a feature supported by the community. I'm happy for you to submit a PR if you can help out.
> > > Thanks in advance, J
> > 
> > 
> > See this for details:
> > [#679 (comment)](https://github.com/jokob-sk/NetAlertX/issues/679#issuecomment-2120403843)
> 
> I would be glad to help, but unfortunately I can’t code. I install it using docker 😁

Then why not just use netalertx docker image?

**Comment by eriklysoe** [comment]
> > > > Hi there,
> > > > I haven't tested the install script for a while. The recommended installation approach is docker.
> > > > I'll try to have a look at the script in a couple of weeks, but it's mostly a feature supported by the community. I'm happy for you to submit a PR if you can help out.
> > > > Thanks in advance, J
> > > 
> > > 
> > > See this for details:
> > > [#679 (comment)](https://github.com/jokob-sk/NetAlertX/issues/679#issuecomment-2120403843)
> > 
> > 
> > I would be glad to help, but unfortunately I can’t code. I install it using docker 😁
> 
> Then why not just use netalertx docker image?

I will, but since there is an option to install on bare metal, I would like to inform that this did not work

**Comment by jokob-sk** [comment]
FYI I implemented some improvements and I was able to get the app installed (nginx didn't start, but the backend seems to be running fine). More work will probably required if someone wants to have a look. -> closing for now
