### ISSUE TITLE
A view under "Devices" like "Not online for xx days"

### ISSUE THREAD

**Issue by AdmiralRaccoon** [jokob-sk/NetAlertX#696]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [X] Yes
- [ ] No

### Is your feature request related to a problem? Please describe

-

### Describe the solution you'd like

I would like to have a view under Devices that sounds like "Not online for XX days", where XX is a number which can be defined in the settings (15 days, 30 days, etc.)
Such a view would help finding legacy devices not active on the network anymore.

### Describe alternatives you've considered

-

### Anything else?

-

**Comment by jokob-sk** [comment]
Hey @AdmiralRaccoon ,

I assume #697 takes care of this request?

**Comment by jokob-sk** [comment]
Great, for now closing as a workaround is available, and will revisit if more feedback comes on something like this in the future.
