### ISSUE TITLE
First Session / Last Session as MQTT Sensor

### ISSUE THREAD

**Issue by AdmiralRaccoon** [jokob-sk/NetAlertX#697]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [X] Yes
- [ ] No

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

Two more Sensors would be nice, which are providing the first & last session dates to work with in Home Assistant

![image](https://github.com/jokob-sk/NetAlertX/assets/41727850/6a96ebae-499d-4902-99f8-a2514ff20fa9)

### Describe alternatives you've considered

A sensor template would be an option from the "last update" Attribute within Home Assistant, but that would require much more work. :-D

### Anything else?

-

**Comment by jokob-sk** [comment]
This should be available in the next release. Please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

👉If I don't get a confirmation that this is working I might pull out the feature to prevent bugs. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

Thanks in advance,
j

**Comment by AdmiralRaccoon** [comment]
seems to work, thanks.
I guess the date/time formating is a home assistant thing then?

![image](https://github.com/jokob-sk/NetAlertX/assets/41727850/510bfcd4-8497-445e-b3d9-6a8cb281eb05)

**Comment by AdmiralRaccoon** [comment]
great, my previous response with a screenshot vanished. Or maybe i just forgot to submit.

Anyway, just wanted to say that it worked and the two new sensors appeared in home assistant.
Although the formatting seems a little weird, but I guess that is a home assistant thing then? (2024-06-07 07:25:46+02:00)

**Comment by AdmiralRaccoon** [comment]
Okay, i can still see it in the HA history:

![image](https://github.com/jokob-sk/NetAlertX/assets/41727850/a0d7ecbb-bf6d-498a-8c57-6a6c41c88545)

**Comment by jokob-sk** [comment]
Thanks for testing. Does that mean it works as expected?

**Comment by AdmiralRaccoon** [comment]
Short answer: Yes

**Comment by jokob-sk** [comment]
😅👍

**Comment by jokob-sk** [comment]
closing -> releasing in ~10min
