### ISSUE TITLE
[Cache] Setting Page Not Loaded - manual cache refresh with 🔄 is needed

### ISSUE THREAD

**Issue by corasaniti** [jokob-sk/NetAlertX#698]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [X] Yes
- [ ] No

### Is your feature request related to a problem? Please describe

With Version: v24.6.8
![Cattura](https://github.com/jokob-sk/NetAlertX/assets/5001932/68a813af-8af4-4e2e-9869-72468afef294)

### Describe the solution you'd like

load setting page

### Describe alternatives you've considered

load setting page

### Anything else?

.

**Comment by corasaniti** [comment]
This is my Javascript Console in Firefox but I tried with same error with Chrome and Opera

![Cattura](https://github.com/jokob-sk/NetAlertX/assets/5001932/c4a03f18-21d7-41bc-a612-37a72bb76223)

**Comment by broodslawns** [comment]
Same. It is broken for me as well. I just set it up from scratch yesterday and it was working great, then updated about an hour ago and now everything is gone. Made a bunch of custom notes too but didn't back up before update, but that's my fault for sure. Live and learn.

I'm using Unraid's Docker management to run this.

**Comment by naamah75** [comment]
Same for me, I'm running the docker image over raspberry bullseye

**Comment by jokob-sk** [comment]
Hi there,

Thanks for the reports. Have you tried refreshing the cache? Usually Shift + refresh and the 🔄 refresh button in the header?

I still have to make the cache expiration / reloading more robust so if anyone is willing to help I would be super thankful.

**Comment by jokob-sk** [comment]
@broodslawns Sorry to hear that - check the backup strategies guide - you might be able to recover some of your configuration: https://github.com/jokob-sk/NetAlertX/blob/main/docs/BACKUPS.md

**Comment by jokob-sk** [comment]
I'm trying to fix this in the -dev image. If someone can, please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

It would be great if you could test this.
Thanks in advance,
j

**Comment by broodslawns** [comment]
> @broodslawns Sorry to hear that - check the backup strategies guide - you might be able to recover some of your configuration: https://github.com/jokob-sk/NetAlertX/blob/main/docs/BACKUPS.md

No worries. I took a look at the article and made an attempt, but I'm early enough in and learning the tool that I'm just starting over. I need to get better at backing up before making changes, regardless.

**Comment by corasaniti** [comment]
@jokob-sk 
Hi, I tried the dev branch and it seems to work. I noticed that when the settings page loads, the cache is forced to update

`jokobsk/netalertx-dev`

When do you plan to push the dev branch into the latest and tag new version?
Thank you

**Comment by jokob-sk** [comment]
@corasaniti You can clear the cache manually in the 24.6.8 build with this button. 

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/2fe0d1c7-542c-494d-948a-9dc754f66da7)

Unless other bugs surface, I will probably release a new version in about ~3 weeks.

**Comment by corasaniti** [comment]
@jokob-sk 

What is the difference between offline device and downdevice ? I'm noticing that the down device down counter is at zero. 
In versions prior to `24.6.8`, did the down device counter report the number of offline devices?
It would be nice to have another tile with offline devices in another color.
Thank you

![Cattura](https://github.com/jokob-sk/NetAlertX/assets/5001932/cdd6f0b7-6e3a-42d8-bc93-20867f362c33)

**Comment by jokob-sk** [comment]
@corasaniti Mixing offline and down devices was causing confusion as per this thread: https://github.com/jokob-sk/NetAlertX/issues/676

Also having 7 tiles would complicate mobile view. There is an Offline list in the left navigation to see offline only devices. 
![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/0dbe9732-258f-4983-8987-4275752a7a42)

**Comment by corasaniti** [comment]
@jokob-sk 
Ok!! So when is a device considered and tagged as down?

**Comment by jokob-sk** [comment]
@corasaniti When a device that has Alert Down selected is offline. See this guide for details: https://github.com/jokob-sk/NetAlertX/blob/main/docs/NOTIFICATIONS.md

**Comment by jokob-sk** [comment]
Releasing -> closing
