### ISSUE TITLE
Visual bug and SyntaxWarning

### ISSUE THREAD

**Issue by vladaurosh** [jokob-sk/NetAlertX#700]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Just updated to the latest version (v24.6.8) which has in-app notifications.
In my case notification bubble is in wrong place:
![image](https://github.com/jokob-sk/NetAlertX/assets/47857324/9cdf5534-74f4-4e5b-b209-a8c44476a9d7)

Probably related to resolution, in my case it's 1366x768.

Second thing is probably just a warning. In docker log I see these warnings:
```
netalertx  | /app/server/helper.py:394: SyntaxWarning: invalid escape sequence '\.'
netalertx  |   ipRegex = "^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$"
netalertx  | /app/server/helper.py:670: SyntaxWarning: invalid escape sequence '\s'
netalertx  |   input = bytes_to_string(re.sub('[^a-zA-Z0-9-_\s]', '', str(input)))
netalertx  | /app/server/helper.py:702: SyntaxWarning: invalid escape sequence '\s'
netalertx  |   value = bytes_to_string(re.sub('[^a-zA-Z0-9-_\s]', '', str(input)))
```

I think this was covered in one of the previous issues, so surprised to see it again. 

### Expected Behavior

Notification bubble in correct position.
No syntax warning expected in docker log.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thanks for the report - forgot to fix this. Regarding the visual bug, can you try to refresh your browser cache with shift + reload or try an incognito window?

**Comment by vladaurosh** [comment]
Just refreshed the browser, and notification bubble has completely disappeared.

**Comment by jokob-sk** [comment]
The notifications are only displayed if there are Unread notifications of level `alert` or `interrupt` in the notifications log. The log is cleared with application restart and there is a 3seconds loop checking for unread notifications. If above is true and the notification count is not shown, then can you post the console log of the browser?

**Comment by vladaurosh** [comment]
Hey @jokob-sk 

Here's screenshot
![image](https://github.com/jokob-sk/NetAlertX/assets/47857324/d0d8a380-2750-400e-b06a-6f1142b165f2)

**Comment by jokob-sk** [comment]
Thbaks! I think this is correct, if there are no unread alert or interrupt notifications.

**Comment by vladaurosh** [comment]
Ok. So that first screenshot with notification bubble showing 0 notifications is ok? Is it was a bug?

**Comment by jokob-sk** [comment]
Yes, that first screenshot was probably a bug - but I think it was shown because there were some older JS files cached on your browser. Maybe from testing the -dev image beforehand? I didn't encounter it on the production build.

**Comment by vladaurosh** [comment]
Not a big deal for sure. I'll report if it happens again.

**Comment by jokob-sk** [comment]
Thanks for the ongoing help 🙏🙂

**Comment by jokob-sk** [comment]
Releasing -> closing
