### ISSUE TITLE
Settings does not load

### ISSUE THREAD

**Issue by kazulk** [jokob-sk/NetAlertX#709]
I have done a new setup with docker. I go into settings in the UI and it sits at loading and never finishes.
<img width="860" alt="netalertx" src="https://github.com/jokob-sk/NetAlertX/assets/103392514/263dc94e-e60a-4ddc-bc77-81344a703fed">

**Comment by kazulk** [comment]
Not sure what I did, but it started working now.  Sorry for the wasted post.

**Comment by jokob-sk** [comment]
All good, glad it's working, usually it's a caching issue after an update and clicking 🔃 in the app and the browser fixes it

**Comment by joel72265** [comment]
I would agree the Settings page does not load, even on a fresh install.
I would like to confirm that by clicking (Refresh) suggested by jokob-sk the page does load. Sometimes even clicking the Save button does work.

Suggestion: to have the page split into static and cached parts so at the page would load immediately and the cached parts takes it time to load.
