### ISSUE TITLE
add sorting per columns options to unassigned devices on the network screen

### ISSUE THREAD

**Issue by FlyingToto** [jokob-sk/NetAlertX#713]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [ ] Yes
- [X] No

### Is your feature request related to a problem? Please describe

not a problem

### Describe the solution you'd like

on the network screen, it would be easier if we had the option to sort the columns of unassigned devices (by ip in particular)

### Describe alternatives you've considered

for the time being, I have been using a control-F to seach and find specific IP which works but is not as elegant.

### Anything else?

n/a

**Comment by jokob-sk** [comment]
This should be available in the next release. Please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 
![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/e6f4c9a4-68bb-49a3-8484-527d7d3d1e30)

**Comment by jokob-sk** [comment]
Releasing -> closing
