### ISSUE TITLE
Copy details from device does not work

### ISSUE THREAD

**Issue by vladaurosh** [jokob-sk/NetAlertX#721]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Using latest stable version (v24.6.8) and seems that 'Copy details from device' does not work. 
Initially nothing happens but after ~30 seconds I get notification:
`Error executing query (attempts: 10), query: DROP TABLE temp_devices`

More details from app log provided.

### Expected Behavior

Expecting to copy details from chosen device

### What branch are you running?

Production

### app.log

PHP Warning:  SQLite3::query(): Unable to prepare statement: no such table: temp_devices in /app/front/php/server/db.php on line 88
Attempting to write '1|2024-07-01 21:05:15|d6c0b8c52de62d2b132baf70c00f82eb|DROP TABLE temp_devices ' to execution log file after failed query: DROP TABLE temp_devices 
Execution log file content after failed query attempt: 1|2024-07-01 21:05:15|d6c0b8c52de62d2b132baf70c00f82eb|DROP TABLE temp_devices 

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thank @vladaurosh for reporting this. 

This should be available in the next release. Please have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now.

**Comment by vladaurosh** [comment]
Looks to be working in dev image. Thanks @jokob-sk

**Comment by jokob-sk** [comment]
Thanks for testing @vladaurosh ! 🙂

**Comment by jokob-sk** [comment]
Releasing -> closing
