### ISSUE TITLE
[Core] Set plugin execution order

### ISSUE THREAD

**Issue by jokob-sk** [jokob-sk/NetAlertX#722]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [X] Yes
- [ ] No

### Is your feature request related to a problem? Please describe

1. Start with plugins which look at the physical layer (like the omada plugin which gets access to the switch/ports)
2. Do layer 2 with (arp-scan)
3. Do layer 3 (IP) with ping, DNS, traceroute
4. Layer 4 and above (nmap, tcping, udp pnp etc…)

### Describe the solution you'd like

config.json property

### Describe alternatives you've considered

user setting - re-ordering of individual plugins

### Anything else?

no

**Comment by jokob-sk** [comment]
Releasing -> closing

**Comment by stanelie** [comment]
Hello. How do you set the plugin order? Thanks!

**Comment by jokob-sk** [comment]
Hi @stanelie , this is done internally by the config.json of individual plugins. Changing the order manually might lead to unpredictable behaviors - I haven't tested it. With the release of #826 - where you can order plugins in the settings, it might be possible, but I haven't tested it.
