### ISSUE TITLE
Customize the Telegram notification for new device

### ISSUE THREAD

**Issue by iptvcld** [jokob-sk/NetAlertX#727]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [X] Yes
- [ ] No

### Is your feature request related to a problem? Please describe

Customize the Telegram notification for new device - the current layout seems too complicated
- Remove Server
- If no Comments, remove Comments: at the bottom as its blank
- Device Name: Would be nice to just display the hostname without (IP match)
- Datetime is redundant as its already shown at the top
- The spacing is not the best as for Example IP:     192.168.2.9

Is there a way to customize this currently?
Thank you!

### Describe the solution you'd like

Customize the Telegram notification for new device - the current layout seems too complicated
- Remove Server
- If no Comments, remove Comments: at the bottom as its blank
- Device Name: Would be nice to just display the hostname without (IP match)
- Datetime is redundant as its already shown at the top
- The spacing is not the best as for Example IP:     192.168.2.9

Is there a way to customize this currently?
Thank you!

### Describe alternatives you've considered

NA

### Anything else?

NA

**Comment by jokob-sk** [comment]
Hi @iptvcld ,

You can map a custom template file: `/app/front/report_templates/report_template.txt` in your `docker-compose.yml` file. This will allow you to remove some basic information:

The current template is:

```
Report Date: <REPORT_DATE>
Server:      <SERVER_NAME>

<NEW_DEVICES_TABLE>
<DOWN_DEVICES_TABLE>
<DOWN_RECONNECTED_TABLE>
<EVENTS_TABLE>
<PLUGINS_TABLE>

```

I don't plan to allow for more customization as it would require much work, and my priority is now to extend the plug functionality. If you want to further customize the notifications you could add a middle layer application and use webhooks. In that midllelayer application you are free to adjust the format of the notifications. For example, I tested it with n8n + email notifications. Here is a basic example:

https://github.com/jokob-sk/NetAlertX/blob/main/docs/WEBHOOK_N8N.md

n8n supports telegram notifications as well. So your setup would be:

NAX webhook -> n8n (here you adjust the JSON to form the telegram message to your needs) -> Telegram

Hope the above makes sense.

**Comment by iptvcld** [comment]
Hmm, would you happen to have a sample json on how to even start with the custom telegram message? I wanted to keep it lean as I already need an apprise docker. Would this docker not be required if I go with the method you listed above?  I just would know what field vars I would use to even get a working telegram body going.

**Comment by jokob-sk** [comment]
Regrettably I have not spent that much time in n8n. You can find the json
of any message under Monitoring - Sent Reports - change message type to
Json in the drop down.

Hope this helps.

**Comment by iptvcld** [comment]
Ok, I will play around with it. Do you think if I move over to discord alert it will have the same alert template?

**Comment by iptvcld** [comment]
I added a custom template file; but the <NEW_DEVICES_TABLE> still brings the entire fields over.  I  tried to edit it as the 2nd code below but the field mappings are not correct..

```
Report Date: <REPORT_DATE>
Server: <SERVER_NAME>

New Device Detected
-----------------------
<NEW_DEVICES_TABLE>
```

```
NetAlertX Notification
Report Date: <REPORT_DATE>
New Device Detected
-----------------------
MAC: <MAC>
IP: <IP>
Device name: <NAME>
```

**Comment by jokob-sk** [comment]
You can only remove existing variables, adding custom ones is not supported, so e.g. you could probably use:

```
<NEW_DEVICES_TABLE>
<DOWN_DEVICES_TABLE>
<DOWN_RECONNECTED_TABLE>
<EVENTS_TABLE>
<PLUGINS_TABLE>
```

I didn't test those though.

**Comment by iptvcld** [comment]
I tried <NEW_DEVICES_TABLE> and it just displays the normal new device fields as standard. I tried to look for mac, IP, etc. but no go.. I like a nice clean alert.

**Comment by jokob-sk** [comment]
As mentioned, currently adjusting the body of individual alerts is not supported. I might spend some time on it in the future, but I have other priorities right now.

**Comment by mormegil6** [comment]
Hi,
I would like to mention that I would also like to customize the Telegram notification. However, I found out that now there's a dedicated [Telegram publisher plugin](https://github.com/jokob-sk/NetAlertX/tree/main/front/plugins/_publisher_telegram), which does not require Apprise (so it is slightly simpler to set up). This Telegram publisher sends a better formatted notifications - good enough for me :) I thought I'd mention it here, in case someone would find this thread looking for such customization, as I did.

**Comment by smithbill17** [comment]
> I thought I'd mention it here, in case someone would find this thread looking for such customization, as I did.

I've found my way here (some 4 years later) as I too wanted to customise the Telegram notification. I've discovered the built-in Telegram plugin, which is great, but the notification sent contains too much 'fluff' for me. My Telegram notifications are converted to speech & also sent to my WearOS SmartWatch, so all the extra 'fluff' results in a VERY long 'speech' for every connecting/disconnecting device. All I wanted was 'Event Type' & 'Device Name'.

**Comment by smithbill17** [comment]
I thought I could 'post-process' the Telegram notification from NetAlertX & extract the relevant parts from the notification (event-type & device-name) to then subsequently apply text-to-speech on them. However, I've now discovered that NetAlertX doesn't actually send a single notification per event, but instead batches them up into a single notification (see attached image). That means there's no way I can easily apply post-processing to the notification ☹️

![Image](https://github.com/user-attachments/assets/ce3ba9a0-eb64-48cd-b552-720189f2d759)
