### ISSUE TITLE
Clean found name to remove domain

### ISSUE THREAD

**Issue by iptvcld** [jokob-sk/NetAlertX#728]
I have looked around but not able to locate. Is it possible to clean the found names? Remove .example.com (IP match)

Device name: IPhone15.example.com (IP match)

Enjoying the project!

**Comment by iptvcld** [comment]
i have watched your YT video and saw you making a plugin for this - have you released such a thing?

**Comment by CRi83** [comment]
Hi,

I had the same issue and after toggling this setting in app.conf it now cleans the domain name:
`NEWDEV_LESS_NAME_CLEANUP=True`

**Comment by CRi83** [comment]
I don't really know if that's possible in the gui, I edited app.conf directly.
The parameter was already there but it was set to false by default.

**Comment by iptvcld** [comment]
Excellent, thank you.

**Comment by jokob-sk** [comment]
Hi there,

All settings are accessible via the UI:

![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/9c5dab44-a6d9-4575-ae34-ef238150f27c)

**Comment by iptvcld** [comment]
I checked that option but the devices still all contain the .domain

**Comment by CRi83** [comment]
> Hi there,
> 
> All settings are accessible via the UI:
> 
> ![image](https://private-user-images.githubusercontent.com/96159884/346309461-9c5dab44-a6d9-4575-ae34-ef238150f27c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMzI5ODIsIm5iZiI6MTcyMDMzMjY4MiwicGF0aCI6Ii85NjE1OTg4NC8zNDYzMDk0NjEtOWM1ZGFiNDQtYTZkOS00NTc1LWFlMzQtZWYyMzgxNTBmMjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDA2MTEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkOWVhM2E5M2MyMWY2YTg5ZTEzOGNjZTQwYTYwMDU5ZWQzYmRjYTdhZjQ4MGFjODgyZTI4NjJmZGUyNjc3ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZN5jysnPBawjuuHnkGs_479IFPd3P8s-x2cViiBq3ns)

Woops sorry I didn't know that 😉
