### ISSUE TITLE
[Permission issue] Save Button does not work (Rasperry Docker Installation)

### ISSUE THREAD

**Issue by DRIV3R78** [jokob-sk/NetAlertX#729]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

The Save Button on the Settings Page does not work on a Raspberry Pi (Docker Installation).
It has no function. Several Errors in Nginx Log

[nginx error.log](https://github.com/user-attachments/files/16116446/nginx.error.log)

### Expected Behavior

When I click the save Button the Settings should be saved.

### docker-compose.yml

docker run -d --rm --network=host \
  -v /NetAlertX/config:/app/config \
  -v /NetAlertX/db:/app/db \
  -e TZ=Europe/Berlin \
  -e PORT=20211 \
  jokobsk/netalertx:latest

### What branch are you running?

Production

### app.log

[app.log](https://github.com/user-attachments/files/16116443/app.log)

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi there, could you please check if this is related?

https://github.com/jokob-sk/NetAlertX/issues/698

**Comment by DRIV3R78** [comment]
Unfortunately clearing the cache manualy or with the reload button does not work.
There are so many errors in the nginx log. I think that could be the problem. Maybe a directory problem with my installation.
When I click the nginx log button I get a not found page. So something seems to be broken.

**Comment by jokob-sk** [comment]
Could you please try not mounting any folders to rule out permission issues?

Please post screenshots of your dev console from the browser and from your settings page. 

Could you please check the following docs:

https://github.com/jokob-sk/NetAlertX/blob/main/docs/FILE_PERMISSIONS.md

https://github.com/jokob-sk/NetAlertX/blob/main/docs/DEBUG_TIPS.md

The nginx log and app log do not contain anything relevant to debug this :/

**Comment by DRIV3R78** [comment]
Starting the container without mapping the volumes does not change anything at all.
It seems to be the same issue. I cant use the save button.

I dont know which part of the dev console ism imortant fpr you but here is a screenshot just after trying to click the save button.

![dev](https://github.com/jokob-sk/NetAlertX/assets/31596145/1a3a2c96-612e-4dc8-8431-30a195623132)

I'm working through the Debug Tips atm

**Comment by DRIV3R78** [comment]
Of course!

![console](https://github.com/jokob-sk/NetAlertX/assets/31596145/cc7b06ec-4bc6-435d-ad5c-dda5e77b6c5d)

**Comment by jokob-sk** [comment]
Thanks for that, the output seems correct (although you are missing the --interface=int_ID parameter for your 10.0.1.0 subnet. Can you check if your app.conf file got updated after clicking "save"?

**Comment by DRIV3R78** [comment]
Sorry for the late reply.
The save button still dont work. I can add 10.0.1.99/24 --interface eth0 to the list, but I can't save it.
When I leave the settings page my browser asks me if i want to discard the inputs

Where exactly ist the app.conf located. Could you sent me the path?
I will than have a look.

**Comment by jokob-sk** [comment]
Hey,

All good, I'm busy too :)

it's under `/app/config/app.conf`

**Comment by DRIV3R78** [comment]
After investigating some more things i probably have to say.

mea culpa, mate.

I discovered some "rights" issues on my raspberry. I create my docker volumes in /opt/* but from time to time I lose the assigned 755 rights and I don´t  know why, atm.

So please mark this issue as resolved because it seems to be on my side.

By the way.
Great work, great effort, mate

**Comment by jokob-sk** [comment]
Haha, thanks, for the nice words :) spread the word on socials so I can make this potentially my main job in future 😅
