### ISSUE TITLE
quick disk space check?

### ISSUE THREAD

**Issue by hs6666** [jokob-sk/NetAlertX#730]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [ ] Yes
- [ ] No

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Hi,

Would love having a plugin that could ssh in to a device, returning the available free space, and then sending an email notification if it goes over 90% (same for cpu usage going OTT)

I am using netalertx to monitor devices over several tailscale overlay vpn networks, and have found these two simple metrics the most common problem that crops up

thanks

Harry

### Describe alternatives you've considered

nagios etc ... to "heavy" for such a scenario

### Anything else?

No

**Comment by jokob-sk** [comment]
Hey @hs6666 ,

I'm happy to approve a PR if you are interested. I'm currently pretty busy and won't be able to implement this in the next few months properly. Here is a quick video on how to create plugins, if you are interested (you can ignore the mapping to the CurrentScan table and check e.g. the https://github.com/jokob-sk/NetAlertX/tree/07164429d5e38f8517b3e761b65c14371cada028/front/plugins/website_monitor plugin for inspiration):

[![Watch the video](https://raw.githubusercontent.com/jokob-sk/NetAlertX/main/docs/img/YouTube_thumbnail.png)](https://youtu.be/cdbxlwiWhv8)

![🎥Watch the video](https://youtu.be/cdbxlwiWhv8)

An in-depth guide for plugins can be found here: 

https://github.com/jokob-sk/NetAlertX/blob/main/docs/PLUGINS_DEV.md

Once you have the basic plugin I'd have to implement a "greater-than" condition in the core app. 
 🙂

**Comment by vladaurosh** [comment]
That sounds like going into the direction of monitoring application.

**Comment by jokob-sk** [comment]
@vladaurosh I was also on the fence, however, if the plugin is universal enough it could allow for specifying custom commands that could be used to monitor network-related insights. E.g. if there is a setting to change the command itself. I definitely don't have time to focus on it myself, but if someone from the community has then that's a nice middle ground in my opinion, with me focusing my time on the core network capabilities. 

Still thinking about how to make the plugin management more robust though, so they don;t have to be looped thru every save. 😅

Anyway, let me hear your thoughts.

**Comment by vladaurosh** [comment]
Hey @jokob-sk 
Problem I see here, is how to handle one or multiple disks and how to present that data in current UI.

**Comment by jokob-sk** [comment]
Yes, was thinking the same at first, but OP said it would be an SSH and not an in-container check. UI presentation - there is already a WEBMON plugin showing plugin data, so basic display is already supported. I wouldn't show it anywhere else though:
![image](https://github.com/jokob-sk/NetAlertX/assets/96159884/15214775-ac63-4cd2-945f-5b0124d509ec)

**Comment by jokob-sk** [comment]
Keeping in the backlog -> closing for now
