### ISSUE TITLE
[Caching issue] Settings Page not shows (not working ) 302 error -img/manifest.json

### ISSUE THREAD

**Issue by masterwishx** [jokob-sk/NetAlertX#734]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Using latest version in docker in unraid 
Trying to get to setting page :  

![image](https://github.com/jokob-sk/NetAlertX/assets/28630321/38553f2f-4830-4808-8c7b-171370050499)

![image](https://github.com/jokob-sk/NetAlertX/assets/28630321/74a1673c-7a28-412f-8fd7-0d23229ec3bb)

![image](https://github.com/jokob-sk/NetAlertX/assets/28630321/6808a848-de8b-49d4-a76a-b8ebb3c4e567)

### Expected Behavior

..

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi there!

Thanks for the screenshots. Can you please try to switch to the `netalertx-dev` image to see if the issue is resolved? Make sure you create backups.

Also, have you tried to refresh the cache with the 🔄 button at the top of the page and in the browser? 

Thanks in advance,
J

**Comment by masterwishx** [comment]
> Also, have you tried to refresh the cache with the 🔄 button at the top of the page and in the browser?

Thnks, it seems refresh button + when f12 (no cache) seems fixed the issue , sould be filter always avalible , cant close it?

**Comment by jokob-sk** [comment]
Glad it's resolved, closing 👍

**Comment by masterwishx** [comment]
> Glad it's resolved, closing 👍

sould be filter always avalible , cant close it?

**Comment by masterwishx** [comment]
![image](https://github.com/user-attachments/assets/4cf72094-d7ac-4b31-bdc6-aae6c0757c27)

**Comment by jokob-sk** [comment]
Yes, not closable by design.

**Comment by masterwishx** [comment]
Will be cool to have option to disable/enable it in future

**Comment by jokob-sk** [comment]
Hummm, I'll think about it. If you have an idea where to put the save
button you can share a rough sketch.
