### ISSUE TITLE
extract default interfaces and subnet automatically

### ISSUE THREAD

**Issue by FlyingToto** [jokob-sk/NetAlertX#744]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [X] Yes
- [ ] No

### Is your feature request related to a problem? Please describe

not a problem - just making things easier

### Describe the solution you'd like

At startup time, extract the list of interfaces and associated subnets from the OS  to prepopulate: SCAN_SUBNETS

One important things to consider: should they be be left listed but disabled by default? (similar to the list of plugins to run)
For most people, it would make sense to scan as many interfaces as possible from a given host. However, this could be counterproductive if NAX is installed on a firewall or if some attached LAN devices have specific counter scan features. 
For instance, if NAX runs on my gateway and starts NMAP scan on the subnet, my bitdefender antivirus will detect the suspicious port scan and disable all traffic from the source IP.... this will prevent the host from reaching outside the LAN.

it might also be worth, highlighting in red (or removing from the list) interfaces which could be problematic like: loopbacks or containers private class B...

### Describe alternatives you've considered

currently entering it manually... subnets are easy but interfaces are less so...

### Anything else?

I don't mind testing it and submitting the pr... I just need to know which line in which file would be the best strategy. 
I tested with this code on my countainer... 

```

import netifaces
import ipaddress

def get_interfaces_and_subnets():
    result = []
    for interface in netifaces.interfaces():
        addrs = netifaces.ifaddresses(interface)
        if netifaces.AF_INET in addrs:
            for addr in addrs[netifaces.AF_INET]:
                ip = addr['addr']
                mask = addr['netmask']
                try:
                    network = ipaddress.IPv4Network(f"{ip}/{mask}", strict=False)
                    result.append((interface, str(network)))
                except ValueError:
                    pass
    return result

# Example usage:
interfaces_and_subnets = get_interfaces_and_subnets()
for interface, subnet in interfaces_and_subnets:
    print(f"interface={interface}, subnet={subnet}")


'''
interface=lo, subnet=127.0.0.0/8
interface=enp6s0, subnet=192.168.0.0/24
interface=br-ba0070d71f2a, subnet=172.16.0.16/29
interface=br-bc4a4c4e0f93, subnet=172.16.0.40/29
interface=br-e043e0ae9c8c, subnet=172.16.0.72/29
interface=br-6acc3945cfba, subnet=172.16.0.48/29
interface=br-6f931807e709, subnet=172.16.0.80/29
interface=docker0, subnet=172.17.0.0/16
interface=br-9ce2cb7c38c3, subnet=172.16.0.24/29
interface=br-eec81501f666, subnet=172.16.0.32/29
interface=br-1064712a4791, subnet=172.16.0.56/29
interface=br-a93ebdba2a28, subnet=172.16.0.8/29
interface=br-d8fa7a3015e2, subnet=172.16.0.64/29
interface=br-e7cdd041d3d3, subnet=172.16.0.0/29
'''
```

**Comment by jokob-sk** [comment]
Hi @FlyingToto ,

Thanks for the suggestion!

Currently, I will put this into the backlog. The issue is that there is not a suitable Setting type that would handle predefined input + selection + enable editing of entered values. 

I spent 30+h on refactoring settings last month and don't want to dive into that part of the code for a while so as not to burn out.
