### ISSUE TITLE
Unifi (UNFIMP) plugin authentication - 2 factor required by unifi

### ISSUE THREAD

**Issue by DavidFederX** [jokob-sk/NetAlertX#754]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

can't connect to unifi due to the forced 2 factor auth. 

### Expected Behavior

need to login to sync with unifi

### Steps To Reproduce

activate UNFIMP
settings, ip, user, pw etc
save
get the 2 factor code in mail (since no 2 factor app setup at unifi)
--> no sync

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi there @DavidFederX !

Thanks for using NetAlertX!

I've just tried and the plugin seems to work just fine. Please make sure you are logging into your UNIFI controller. A 2-factor challenge is not required when logging into the controller on your local network. 

![image](https://github.com/user-attachments/assets/beaa44a2-7db8-4126-93cf-fba9b520d2e8)

![image](https://github.com/user-attachments/assets/7e5cc5c3-9309-4e95-9d60-c63cec73ce82)

**Comment by jokob-sk** [comment]
No reply for a week -> Closing

**Comment by DavidFederX** [comment]
Hello, 
sorry for the (very) late reply. 
I've well set the parameters and got the login failed in the logs. 
![image](https://github.com/user-attachments/assets/0209f4a8-6e51-4f3f-8c91-5aaa1a9b6802)
![image](https://github.com/user-attachments/assets/3cbb5507-13cc-4c4e-8653-987e2820b595)
100% sure of my ip, username and pw. Unifi forced using 2 factors a few months ago.
Do you indeed have latest version of unifi?

**Comment by DavidFederX** [comment]
sorry, I realize I did a mistake. 
it actually works :)
