### ISSUE TITLE
Latest tag DEV branch keep loading

### ISSUE THREAD

**Issue by corasaniti** [jokob-sk/NetAlertX#755]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Latest tag DEV branch keep loading for evergy page
Thanks

![Cattura](https://github.com/user-attachments/assets/d4d61845-fe45-4114-8167-c83038d026df)

### Expected Behavior

Not loading pages

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi there,

Have you tried refreshing the cache with the 🔄 button and clear the browser cache?

**Comment by corasaniti** [comment]
@jokob-sk 
I can't see any page because it keeps loading. I can't even see the refresh button 🔄
All pages are still loading
Thanks again

**Comment by corasaniti** [comment]
@jokob-sk 
Ok I apologize. I forced the cache refresh and everything worked fine
Thanks for the support
PC

**Comment by jokob-sk** [comment]
Thansk for testing! :)
