### ISSUE TITLE
Remove or handle github outages

### ISSUE THREAD

**Issue by redge76** [jokob-sk/NetAlertX#763]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Netalerx does not start while github is down because the outtage page does not pass JSON validation.
https://www.githubstatus.com/incidents/kz4khcgdsfdv

(the pink unicor if cute though :-P )

### Expected Behavior

Netalerx should handle the JSONDecodeError exception.

### What branch are you running?

Production

### app.log

08/15/202401:20:06 AM
all values are hidden
08/15/202401:20:06 AM
08/15/202401:20:07 AM
Traceback (most recent call last):
08/15/202401:20:07 AM
File "<frozen runpy>", line 198, in _run_module_as_main
08/15/202401:20:07 AM
File "<frozen runpy>", line 88, in _run_code
08/15/202401:20:07 AM
File "/app/server/__main__.py", line 209, in <module>
08/15/202401:20:07 AM
sys.exit(main())
08/15/202401:20:07 AM
^^^^^^
08/15/202401:20:07 AM
File "/app/server/__main__.py", line 85, in main
08/15/202401:20:07 AM
updateState("Initializing")
08/15/202401:20:07 AM
^^^^^^^^^^^^^^^^^^^^^^^^^^^
08/15/202401:20:07 AM
File "/app/server/helper.py", line 133, in updateState
08/15/202401:20:07 AM
state = app_state_class(newState, settingsSaved, settingsImported, showSpinner)
08/15/202401:20:07 AM
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
08/15/202401:20:07 AM
File "/app/server/helper.py", line 89, in __init__
08/15/202401:20:07 AM
self.isNewVersion = checkNewVersion()
08/15/202401:20:07 AM
^^^^^^^^^^^^^^^^^
08/15/202401:20:07 AM
File "/app/server/helper.py", line 921, in checkNewVersion
08/15/202401:20:07 AM
data = json.loads(text)
08/15/202401:20:07 AM
^^^^^^^^^^^^^^^^
08/15/202401:20:07 AM
File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
08/15/202401:20:07 AM
return _default_decoder.decode(s)
08/15/202401:20:07 AM
^^^^^^^^^^^^^^^^^^^^^^^^^^
08/15/202401:20:07 AM
File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
08/15/202401:20:07 AM
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
08/15/202401:20:07 AM
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
08/15/202401:20:07 AM
File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
08/15/202401:20:07 AM
raise JSONDecodeError("Expecting value", s, err.value) from None
08/15/202401:20:07 AM
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thanks for the report!

This should be available in the next release. You can have a look at the `netalertx-dev` docker image, in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

Thanks in advance,
j

**Comment by jokob-sk** [comment]
Releasing -> closing
