### ISSUE TITLE
Setting menu keep looping saying "outdated cache"

### ISSUE THREAD

**Issue by 9M2PJU** [jokob-sk/NetAlertX#766]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

![image](https://github.com/user-attachments/assets/6bb62960-2f9b-4cb9-bc49-6e3830b9c294)

### Expected Behavior

it should not

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi there,

Did you try to click the 🔁 button in the header and refreshing the browser cache (usually shift + browser reload page button)?

J

**Comment by 9M2PJU** [comment]
Tried. but nothing works. still showing outdated cache. this is fresh install from docker.

**Comment by jokob-sk** [comment]
Could you please try the `netalertx-dev` image if the issue persists? 

What browser are you using? I tested the latest image in Firefox and Chrome and it seems to work fine. 

Did you modify the settings or the app.conf file directly?

**Comment by jokob-sk** [comment]
Try the default `app.conf` file and modify the settings via the UI.

**Comment by 9M2PJU** [comment]
![image](https://github.com/user-attachments/assets/aa5c0701-5952-47a7-b8c5-61861007efe5)
![image](https://github.com/user-attachments/assets/723a902d-2d8b-4db8-a32b-a2e7448f2e58)

![image](https://github.com/user-attachments/assets/5166701b-35a9-462f-b840-8209b4d5ee51)

**Comment by jokob-sk** [comment]
Could you please post a screenshot of the dev console in the browser (usually accessible F12 -> Console) if there are any errors?

Also, please post your app.conf file if you have modified the default values.

**Comment by 9M2PJU** [comment]
> Try the default `app.conf` file and modify the settings via the UI.

i cannot access the setting menu even with fresh install without editing app.conf. same outdated cache error

**Comment by 9M2PJU** [comment]
> Could you please post a screenshot of the dev console in the browser (usually accessible F12 -> Console) if there are any errors?
> 
> Also, please post your app.conf file if you have modified the default values.

![image](https://github.com/user-attachments/assets/583e99db-e7b9-49be-a8cb-16dd1b546ebe)

**Comment by jokob-sk** [comment]
Could you please try to follow this guide to rule out permission issues?  

https://github.com/jokob-sk/NetAlertX/blob/main/docs/FILE_PERMISSIONS.md

Please post your current app.conf file and docker-compose.yml

**Comment by 9M2PJU** [comment]
already did 

docker run -d --rm --network=host \
-e TZ=Europe/Berlin \
-e PORT=20211 \
jokobsk/netalertx:latest

i remove everything and run that command and i dont use any compose yml,i didnt adjust any config. still error.

**Comment by jokob-sk** [comment]
Could you please try to open the page in an incognito/private window, and:

1.  click the 
![image](https://github.com/user-attachments/assets/67e34713-a476-4bc6-9fbd-51df934f1e1e)
2. Hold shift + refresh the browser cache: 
![image](https://github.com/user-attachments/assets/c316bd38-f4a2-4110-a805-bbaf7654549a)

**Comment by 9M2PJU** [comment]
> Could you please try to open the page in an incognito/private window, and:
> 
> 1. click the
>    ![image](https://private-user-images.githubusercontent.com/96159884/359075888-67e34713-a476-4bc6-9fbd-51df934f1e1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjQ5MzksIm5iZiI6MTcyNDA2NDYzOSwicGF0aCI6Ii85NjE1OTg4NC8zNTkwNzU4ODgtNjdlMzQ3MTMtYTQ3Ni00YmM2LTlmYmQtNTFkZjkzNGYxZTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDEwNTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNjU4Y2Y3ZTBkODVjNTczZTc0NTA5YjM4NmM1YmJkYWQxMDVkZWZmMGI4OTNmYjJkNGE5YWZjNzEwNDAwZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EhScD0b82TRT4nWHQqTe-AO-NKY7l1Ivv5kNtHnzSBE)
> 2. Hold shift + refresh the browser cache:
>    ![image](https://private-user-images.githubusercontent.com/96159884/359076040-c316bd38-f4a2-4110-a805-bbaf7654549a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjQ5MzksIm5iZiI6MTcyNDA2NDYzOSwicGF0aCI6Ii85NjE1OTg4NC8zNTkwNzYwNDAtYzMxNmJkMzgtZjRhMi00MTEwLWE4MDUtYmJhZjc2NTQ1NDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDEwNTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMjUzNGRjMWY0ODhkNTQxMThkOTQ4NzMxNGMxZWE3MTcwNzg1N2RiNDA1YzAyN2QwNDRhMDE1YjAyZmI0MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FvBzM1Ss4WFav_rQZxLNM5-s2BD2x4_KTVsbRGSzmjE)

dont that before posting here. i even restart pc, clear cache, run in incognito,

**Comment by jokob-sk** [comment]
Are the following URLs accessible?

`<your IP:port>/api/table_settings.json`
`<your IP:port>/api/plugins.json`

Could you please post your `app.log` contents?

**Comment by jokob-sk** [comment]
> > Could you please try to open the page in an incognito/private window, and:
> > 
> > 1. click the
> >    ![image](https://private-user-images.githubusercontent.com/96159884/359075888-67e34713-a476-4bc6-9fbd-51df934f1e1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjQ5MzksIm5iZiI6MTcyNDA2NDYzOSwicGF0aCI6Ii85NjE1OTg4NC8zNTkwNzU4ODgtNjdlMzQ3MTMtYTQ3Ni00YmM2LTlmYmQtNTFkZjkzNGYxZTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDEwNTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNjU4Y2Y3ZTBkODVjNTczZTc0NTA5YjM4NmM1YmJkYWQxMDVkZWZmMGI4OTNmYjJkNGE5YWZjNzEwNDAwZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EhScD0b82TRT4nWHQqTe-AO-NKY7l1Ivv5kNtHnzSBE)
> > 2. Hold shift + refresh the browser cache:
> >    ![image](https://private-user-images.githubusercontent.com/96159884/359076040-c316bd38-f4a2-4110-a805-bbaf7654549a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNjQ5MzksIm5iZiI6MTcyNDA2NDYzOSwicGF0aCI6Ii85NjE1OTg4NC8zNTkwNzYwNDAtYzMxNmJkMzgtZjRhMi00MTEwLWE4MDUtYmJhZjc2NTQ1NDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDEwNTAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMjUzNGRjMWY0ODhkNTQxMThkOTQ4NzMxNGMxZWE3MTcwNzg1N2RiNDA1YzAyN2QwNDRhMDE1YjAyZmI0MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FvBzM1Ss4WFav_rQZxLNM5-s2BD2x4_KTVsbRGSzmjE)
> 
> dont that before posting here. i even restart pc, clear cache, run in incognito,

Could you please try once more even if you tried this in the beginning?

**Comment by jokob-sk** [comment]
> Are the following URLs accessible?
> 
> `<your IP:port>/api/table_settings.json` `<your IP:port>/api/plugins.json`
> 
> Could you please post your `app.log` contents?

**Comment by 9M2PJU** [comment]
9m2pju@raspi-100:~ $ docker logs e37f4134e537
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service SetupOneshot: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
---------------------------------------------------------
[INSTALL]                                    Run setup.sh
---------------------------------------------------------
[INSTALL] Copy starter app.db and app.conf if they don't exist
s6-rc: info: service legacy-cont-init successfully started
[INSTALL] Setup timezone
[INSTALL] Setup NGINX
Setting webserver to address (0.0.0.0) and port (20211)
[INSTALL] Run the hardware vendors update
The file ieee-oui.txt exists. Skipping update_vendors.sh...
[INSTALL] Fixing permissions after copied starter config & DB
[INSTALL] Starting crond service...

            [ENV] PATH                      is /command:/opt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            [ENV] PORT                      is 20211
            [ENV] TZ                        is Asia/Kuala_Lumpur
            [ENV] LISTEN_ADDR               is 0.0.0.0
            [ENV] ALWAYS_FRESH_INSTALL      is

s6-rc: info: service SetupOneshot successfully started
s6-rc: info: service php-fpm: starting
s6-rc: info: service php-fpm successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service netalertx: starting
s6-rc: info: service netalertx successfully started
s6-rc: info: service legacy-services: starting

            [INSTALL] 🚀 Starting app (:20211)


s6-rc: info: service legacy-services successfully started
19:54:55 [MAIN] Setting up ...
19:54:55 [conf.tz] Setting up ...
19:54:55

19:54:55 The backend restarted (started). If this is unexpected check https://bit.ly/NetAlertX_debug for troubleshooting tips.
19:54:55

19:54:55 Permissions check (All should be True)
19:54:55 ------------------------------------------------
19:54:55   /config/app.conf |  READ  | True
19:54:55   /config/app.conf |  WRITE | True
19:54:55   /db/app.db       |  READ  | True
19:54:55   /db/app.db       |  WRITE | True
19:54:55 ------------------------------------------------
19:54:55 [Setup] Attempting to fix permissions.
19:54:55 [Setup] Attempting to fix permissions.
19:54:55 [Database] Opening DB
19:54:55 [upgradeDB] Adding dev_Network_Node_MAC_ADDR to the Devices table
19:54:55 [upgradeDB] Adding dev_Network_Node_port to the Devices table
19:54:55 [upgradeDB] Adding dev_Icon to the Devices table
19:54:55 [upgradeDB] Adding dev_GUID to the Devices table
19:54:55 [upgradeDB] Adding dev_NetworkSite to the Devices table
19:54:55 [upgradeDB] Adding dev_SSID to the Devices table
19:54:55 [upgradeDB] Adding dev_SyncHubNodeName to the Devices table
19:54:55 [upgradeDB] Re-creating Settings table
19:54:55 [upgradeDB] Re-creating Pholus_Scan table
19:54:55 [upgradeDB] Re-creating Parameters table
19:54:55 [upgradeDB] Adding SyncHubNodeName to the Plugins_Objects table
19:54:55 [upgradeDB] Adding SyncHubNodeName to the Plugins_Events table
19:54:55 [upgradeDB] Adding SyncHubNodeName to the Plugins_History table
19:54:57 [Version check] Running the latest version.
19:54:58 [Config] reading config file
19:54:59 [Config] Plugins: Number of all plugins (including not loaded): 34
19:54:59 [Plugin utils] ---------------------------------------------
19:54:59 [Plugin utils] display_name: OMADA SDN import
19:54:59 [Plugin utils] description: Plugin to import data from OMADA SDN.
19:54:59 [Plugin utils] ---------------------------------------------
19:54:59 [Plugin utils] display_name: SNMP discovery
19:54:59 [Plugin utils] description: This plugin is used to discover devices via the arp table(s) of a RFC1213 compliant router or switch.
19:54:59 [Plugin utils] ---------------------------------------------
19:54:59 [Plugin utils] display_name: UniFi import
19:54:59 [Plugin utils] description: This plugin is used to import devices from an UNIFI controller.
19:54:59 [Plugin utils] ---------------------------------------------
19:54:59 [Plugin utils] display_name: Arp-Scan (Network scan)
19:54:59 [Plugin utils] description: This plugin is to execute an arp-scan on the local network
19:55:00 [Plugin utils] ---------------------------------------------
19:55:00 [Plugin utils] display_name: PiHole (Device sync)
19:55:00 [Plugin utils] description: This plugin syncs devices from the PiHole database
19:55:00 [Plugin utils] ---------------------------------------------
19:55:00 [Plugin utils] display_name: DHCP Leases (Device import)
19:55:00 [Plugin utils] description: This plugin is to import devices from dhcp.leases files.
19:55:00 [Plugin utils] ---------------------------------------------
19:55:01 [Plugin utils] display_name: Rogue DHCP
19:55:01 [Plugin utils] description: This plugin is to use NMAP to monitor for rogue DHCP servers.
19:55:01 [Plugin utils] ---------------------------------------------
19:55:01 [Plugin utils] display_name: Internet-Check
19:55:01 [Plugin utils] description: A plugin to check your internet connectivity and IP.
19:55:02 [Plugin utils] ---------------------------------------------
19:55:02 [Plugin utils] display_name: NBTSCAN (Name discovery)
19:55:02 [Plugin utils] description: A plugin to discover device names via NetBIOS.
19:55:02 [Plugin utils] ---------------------------------------------
19:55:02 [Plugin utils] display_name: NMAP Device discovery
19:55:02 [Plugin utils] description: This plugin is to execute an NMAP scan for device discovery on the local network
19:55:03 [Plugin utils] ---------------------------------------------
19:55:03 [Plugin utils] display_name: Services & Ports (NMAP)
19:55:03 [Plugin utils] description: This plugin shows all services discovered by NMAP scans.
19:55:03 [Plugin utils] ---------------------------------------------
19:55:03 [Plugin utils] display_name: NSLOOKUP (Name discovery)
19:55:03 [Plugin utils] description: A plugin to discover device names.
19:55:03 [Plugin utils] ---------------------------------------------
19:55:03 [Plugin utils] display_name: Apprise publisher
19:55:03 [Plugin utils] description: A plugin to publish a notification via the Apprise gateway.
19:55:03 [Plugin utils] ---------------------------------------------
19:55:04 [Plugin utils] display_name: Email publisher (SMTP)
19:55:04 [Plugin utils] description: A plugin to publish a notification via Email (SMTP) gateway.
19:55:05 [Plugin utils] ---------------------------------------------
19:55:05 [Plugin utils] display_name: MQTT publisher
19:55:05 [Plugin utils] description: A plugin to publish a notification via MQTT to Home Assistant.
19:55:05 [Plugin utils] ---------------------------------------------
19:55:05 [Plugin utils] display_name: NTFY publisher
19:55:05 [Plugin utils] description: A plugin to publish a notification via the NTFY gateway.
19:55:05 [Plugin utils] ---------------------------------------------
19:55:05 [Plugin utils] display_name: Pushover publisher
19:55:06 [Plugin utils] description: A plugin to publish a notification via the pushover.net
19:55:06 [Plugin utils] ---------------------------------------------
19:55:06 [Plugin utils] display_name: Pushsafer publisher
19:55:06 [Plugin utils] description: A plugin to publish a notification via the Pushsafer gateway.
19:55:06 [Plugin utils] ---------------------------------------------
19:55:06 [Plugin utils] display_name: Webhook publisher
19:55:06 [Plugin utils] description: A plugin to publish a notification via Webhooks.
19:55:06 [Plugin utils] ---------------------------------------------
19:55:06 [Plugin utils] display_name: CSV backup
19:55:06 [Plugin utils] description: A plugin to auto-generate devices.csv backups.
19:55:07 [Plugin utils] ---------------------------------------------
19:55:07 [Plugin utils] display_name: DB cleanup
19:55:07 [Plugin utils] description: A plugin to schedule database cleanup & upkeep tasks.
19:55:08 [Plugin utils] ---------------------------------------------
19:55:08 [Plugin utils] display_name: DDNS update
19:55:08 [Plugin utils] description: A plugin update the DDNS record.
19:55:08 [Plugin utils] ---------------------------------------------
19:55:08 [Plugin utils] display_name: Internet speedtest
19:55:08 [Plugin utils] description: A plugin to perform a scheduled internet speedtest.
19:55:08 [Plugin utils] ---------------------------------------------
19:55:08 [Plugin utils] display_name: Maintenance
19:55:08 [Plugin utils] description: A plugin for maintenance tasks.
19:55:09 [Plugin utils] ---------------------------------------------
19:55:09 [Plugin utils] display_name: New Devices
19:55:09 [Plugin utils] description: The template used for new devices.
19:55:11 [Plugin utils] ---------------------------------------------
19:55:11 [Plugin utils] display_name: Notification Processing
19:55:11 [Plugin utils] description: A plugin to for advanced notification processing.
19:55:11 [Plugin utils] ---------------------------------------------
19:55:11 [Plugin utils] display_name: Pholus (Name discovery)
19:55:11 [Plugin utils] description: This plugin is to execute a Pholus (name discovery) on the local network
19:55:12 [Plugin utils] ---------------------------------------------
19:55:12 [Plugin utils] display_name: Set password
19:55:12 [Plugin utils] description: A simple plugin to set the web ui password on app start.
19:55:12 [Plugin utils] ---------------------------------------------
19:55:12 [Plugin utils] display_name: Sync Hub
19:55:12 [Plugin utils] description: Plugin to synchronize multiple NetAlertX instances.
19:55:13 [Plugin utils] ---------------------------------------------
19:55:13 [Plugin utils] display_name: UI settings
19:55:13 [Plugin utils] description: Plugin to adjust UI settings.

logs looks OK.

> api/table_settings.json

![image](https://github.com/user-attachments/assets/d92ef28b-014c-4773-8994-8c5bc9bcbba3)
![image](https://github.com/user-attachments/assets/e73e1d45-6d13-46e5-9246-a0566cec2111)

but it still showing outdated cache

**Comment by gioxx** [comment]
Same problem here. I used docker compose to pull up the container (stack via portainer). Configured it, got it working, all perfect. I reopened the Macbook to resume work and find that the settings page shows this bug. Only this page, all others work perfectly. 
I have already tried everything that has been suggested within the discussion. I will remain available if more is needed.

> Can you please send me the full:
>     * app.log
>     * /api/plugins.json
>     * /api/table_settings.json
>     * app.conf
> 

https://gist.cerbero.cc/gioxx/5c3c72c9556a4e8fae1345cde296522b
https://gist.cerbero.cc/gioxx/f904678cdc4c4c33b6155e31d6237e72

Please let me know how I can get and give to you app.log file. I can also give you app.conf but I prefer to send you the link to the file in private. If you agree, I would send you an e-mail (I need a contact e-mail address though).

**Comment by jokob-sk** [comment]
Hi @gioxx ,

Thanks a lot for the files. 

I couldn't spot anything out of the ordinary. I implemented some changes to the settings page which might resolve this issue. 

 Can you please switch to the `netalertx-dev` docker image (backup everything at first), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now and let me know if the issue persists.

If the issue persists, could you please supply the following?

1. Could you please let me know what browser are you using? If you are not using Firefox or Chrome, could you please try one of those instead?
2. Are there any errors in the console of the browser?

Thanks in advance,
j

**Comment by gioxx** [comment]
Ciao @jokob-sk 👋 
With the dev image things seem to be going much better than with the stable image. Right now the settings page is working perfectly and finally allowed me to change some settings I wanted. I will continue to keep an eye on it over the next few hours and days and get back to you with news if there is any.
Meanwhile, thank you very much for what you have done.

**Comment by jokob-sk** [comment]
Hi @gioxx,

Glad to hear that and thanks for checking!

J

**Comment by gioxx** [comment]
Ciao @jokob-sk.
Just to tell you that, unfortunately, the problem has happened again. Since you asked me to use the development image I have continued to keep that one. Today, after several days of not returning to the console on NAX, I found myself with the expired cache problem looping through the Settings page. I have already tried recreating the stack but to no avail 😞

**Comment by jokob-sk** [comment]
Hey @gioxx 👋

Thanks for the continuous support and testing!

I just pushed out an optimization which selectively loads only the used language files which might improve this as well. Previously all 12 files were loaded, and now only 1 (or 2 if you have another language selected than English) are loaded. This should help with the loading dialog in Settings. 🤞

If you can, can you stop your container, delete old images, and re-pull the `netalertx-dev` image in about 15 min from now?

Also - if someone reading can help me debug the issue / fix it, if you are a developer, that would be amazing. 🙏

Thanks for the ongoing support,
j

**Comment by gioxx** [comment]
Ciao @jokob-sk, no problem, it seems the least I can do to give you feedback.
In the meantime I can tell you that it is now working again (I almost always leave the language in English where I can), I hope it stays that way!

Thanks 😄

**Comment by jokob-sk** [comment]
Thanks for the update! :)

**Comment by jokob-sk** [comment]
Releasing -> closing
