### ISSUE TITLE
[Mobile UI] Dialog to add custom icon in device details is not shown on mobile

### ISSUE THREAD

**Issue by XxAcielxX** [jokob-sk/NetAlertX#772]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

When making different settings through the UI, when on a mobile browsers, the confirmation pop-ups do not appear. The page turns slightly greyed out, and user is unable to do anything.

### Expected Behavior

Confirmation pop-ups should appear as they do on desktop browsers, and allow the user to Accept/Save/Proceed with them.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi there,

Thanks for the report.

This should be fixed in the next release. You can check the `netalertx-dev` container, where now a loading dialog should be displayed on the top of the page after you click the save button.

Thanks,
J

**Comment by jokob-sk** [comment]
Releasing -> closing

**Comment by jokob-sk** [comment]
Thansk for the video! That clears things up. This should be fixed in the next release. You can check the netalertx-dev container in 15 min from now.

Thanks,
J

**Comment by XxAcielxX** [comment]
Just for the info, this affects all dialogues that appears on different areas.

**Comment by jokob-sk** [comment]
I think this should fix it everywhere. Did you test it?

**Comment by XxAcielxX** [comment]
I have tested `netalertx-dev`, and the popup display of Device Icon appears properly now. Thanks

A quick question, can I go from `netalertx-dev` to `latest` tag when new release is out?

**Comment by jokob-sk** [comment]
Great! Yes you can switch from dev to production once the next release
comes out.

**Comment by jokob-sk** [comment]
released -> closing
