### ISSUE TITLE
Need some extra eyes please...

### ISSUE THREAD

**Issue by adm2k** [jokob-sk/NetAlertX#778]
**_When I run Netalertx using the following I see all of my devices:_**

docker run -d --rm --network=host   -v "/$(pwd)/netalertx/config:/app/config"   -v "/$(pwd)/netalertx/db:/app/db"   -e TZ=America/New_York   -e PORT=20211   jokobsk/netalertx:latest

**_I converted the above to a docker-compose.yml and only see one device, my internet connections._**

name: netalertx
services:
    netalertx:
        network_mode: host
        volumes:
            - /$(pwd)/netalertx/config:/app/config
            - /$(pwd)/netalertx/db:/app/db
        environment:
            - TZ=America/New_York
            - PORT=20211
        image: jokobsk/netalertx:latest
		  
Any suggestions?

Many thanks!
al

**Comment by adm2k** [comment]
Can anyone help?

Thanks

**Comment by FlyingToto** [comment]
not sure if it helps but...  
1) yes it looks like your docker compose match your docker command...  (I never used $pwd in my file, so you might want to try to hardcode the path and see if it helps)
2) did you double-check your interface name and subnet inside netalertX after starting from compose? maybe the config got reset and it is not parsing the whole subnet... as when you start it from the docker command...

**Comment by adm2k** [comment]
@FlyingToto 

Thanks for the response. I removed the $pwd and use /root/NetAlertx and it worked!

Thanks again!

**Comment by jokob-sk** [comment]
Thank you @FlyingToto for your help here 🙏 closing as resolved.
