### ISSUE TITLE
Map doesn't render correctly in Safari

### ISSUE THREAD

**Issue by LunarJetman0** [jokob-sk/NetAlertX#781]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Map renders lines correctly but blank spaces where the labels should be. Label appears in top right corner but may also be a stack of labels

### Expected Behavior

Map renders with labels next ot each connecting line

### Steps To Reproduce

OS: MacOS 14.6.1
Safari: Version 17.6 (19618.3.11.11.5)

Configure nodes as per NETWORK.md and click onto the Network map

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by LunarJetman0** [comment]
<img width="1660" alt="image" src="https://github.com/user-attachments/assets/57d49618-f507-4286-98ad-d275aa2689db">

**Comment by jokob-sk** [comment]
Hi there,

Regrettably I don't have a Mac system and the bandwidth to support Safari. The primary supported browsers are Firefox and Chrome. Happy for someone to submit a PR with a fix though.

Thanks,
J

**Comment by JackD-01** [comment]
Have the same problem on my Apple iPad(gen7). The Network does not render correctly, same as image from LunarJetman0. Does not render correctly in Safari but also not in Mozilla Firefox for iPad. I am not a programmer just a happy user of NetAlertX, so I can not help you much.

**Comment by jokob-sk** [comment]
I regrettably don't have any Apple devices to test this. So if someone can help, that would be great, but I will have to rely on someone from the community.

**Comment by LunarJetman0** [comment]
Sorry, also not a developer so unable to help with the code, but happy to test/help any other way I can.

I suspect the issue is with WebKit though as it renders OK on a Mac on other browsers e.g. Brave/Chrome/Firefox, but not on an iPad with any browser (all iOS browsers are WebKit regardless of brand)

**Comment by jokob-sk** [comment]
Closing for now -> will re-open if someone is able to help

**Comment by Stationary-1** [comment]
Which debug information would you need, can’t get the information from the iOS devices, I guess, but the Safari on the MacBook might give away details.

**Comment by jokob-sk** [comment]
Hi @Stationary-1,

Regrettably I need someone to help me fix this by submitting a PR. Debug information is not sufficient as I can't test a fix. From experience, developing or trying to fix something without being able to test it is almost impossible.

Hope this makes sense.

**Comment by Stationary-1** [comment]
Sure that makes sense. If any developer out there at some point in time with access to Safari wants to look at it, I enclose the console output Safari 17.6 marks in red as error on the page.
[Safari_error_Network.txt](https://github.com/user-attachments/files/17510926/Safari_error_Network.txt)
