### ISSUE TITLE
Omada Plugin fails to connect if it is using a self signed certificate

### ISSUE THREAD

**Issue by thefunkygibbon** [jokob-sk/NetAlertX#785]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Set up connecting to my Omada, 
see this in the logs
09:10:34 [OMDSDN] callomada:-t myomada target --url https://192.168.0.2:8043/ --user xxxxx --password xxxxxxxx --site Default --set-default
09:10:34 [OMDSDN] login to omada result is: Could not connect to controller with provided credentials: Cannot connect to host 192.168.0.2:8043 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')]
Target has not been added.

09:10:34 [OMDSDN] callomada:-t myomada clients
09:10:34 [OMDSDN] ERROR WHILE CALLING callomada:-t myomada clients
 <_io.StringIO object at 0x7fb242eb5780>
09:10:34 [OMDSDN] clients found:"0"

### Expected Behavior

to ignore the cert issue since most self hosted omada controllers will be used without a cert. 

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by thefunkygibbon** [comment]
ok ignore, I've found that you can configure omada to be accessed on http.   would be still better to have it to ignore the certificate so can use https only though, don't hugely like cleartext protocols being open

**Comment by FlyingToto** [comment]
Any particular reason to use a self-signed certificate?   

I would agree with OP that you don't want to expose your omada SDN over plain http; nor use their cloud frontend based on the recent reports from the US department of defense, but you should really install  a standard cert like the free letsencrypt. 

in theory, you should be able to export your self-signed cert CA into a pem file and add it as an environment variable: 
export REQUESTS_CA_BUNDLE=/path/to/your/certificate.pem

**Comment by thefunkygibbon** [comment]
because it's a home based internal system. I can't be arsed to faff around getting a certificate created for that.  I do use let's encrypt for my external based systems like home assistant but that's all done automatically via swag. 

but that's just me being lazy though.  realistically speaking I can survive with http seeings as it's just internally accessed.  thanks
