### ISSUE TITLE
Notification about it having been updated constantly re-appears 

### ISSUE THREAD

**Issue by thefunkygibbon** [jokob-sk/NetAlertX#791]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Clicking on ok on the notification 
![image](https://github.com/user-attachments/assets/98d2714f-4917-4c10-b10a-af7c79b074cc)
it just re-appears after a short few seconds.  
I've obviously done what it suggests and even tried opening it in a new browser which i've never used netalertx on before.

any ideas how to suppress it?

### Expected Behavior

click ok.  it goes away

### Steps To Reproduce

already said

### app.conf

```python
can provide if its really needed
```

### docker-compose.yml

```python
can provide if its really needed
```

### What branch are you running?

Production

### app.log

can provide if its really needed

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thank you for the report.

Could you please try to:

- click OK
- clear the cache as per instructions


If the pop up still appear can double check if the app is not restarting unexpectedly?

Can you please try to save settings to see if it disappears afterwards?

**Comment by jokob-sk** [comment]
@Dan-Sun thanks for the confirmation - I will add those steps into the message as well for clarity

**Comment by thefunkygibbon** [comment]
not sure how it worked for @Dan-Sun , but as i said in my post, I've done all that, I've just tried on a completely different computer where I have never used it before and it still continuously pops up.  used, linux, windows, chrome, opera, firefox now. 

just tried to save the settings again but it makes no difference.

**Comment by franbri** [comment]
I have the same issue in the last update, i can fix it temporally going to notifications and marking all the interrupt level notifications in that page, but it only works until the next network scan is triggered.

**Comment by jokob-sk** [comment]
@franbri Thanks for the log, this helps! I just pushed some safety checks in that piece of code and the fix should be available in the `netalertx-dev` image in about 15 min from now. You can switch to it to test it. Hope this will fix the issue on your setup 🤞

@thefunkygibbon I think there is restart for you happening or some error might be logged in the logs for your instance as well. Can you check the log to see if there are any errors?

**Comment by The1Waterman** [comment]
Sampe issue, I have the following error apperaing:

09:58:51 [Plugin utils] display_name: Un-Discoverable Devices
09:58:51 [Plugin utils] description: This plugin is to import undiscoverable devices from a file.
09:58:51 [Plugin utils] ---------------------------------------------
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/server/__main__.py", line 209, in <module>
    sys.exit(main())       
             ^^^^^^
  File "/app/server/__main__.py", line 105, in main
    pluginsState = check_and_run_user_event(db, all_plugins, pluginsState)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/server/plugin.py", line 856, in check_and_run_user_event
    pluginsState = handle_run(param, db, all_plugins, pluginsState)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/server/plugin.py", line 885, in handle_run
    pluginsState = execute_plugin(db, all_plugins, plugin, pluginsState) 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/server/plugin.py", line 182, in execute_plugin
    tempParam = plugin_param(param, plugin, db)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/server/plugin.py", line 87, in __init__
    resolved = str(base64.b64encode(resolved.encode('ascii')))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 87: ordinal not in range(128)
09:58:51 [Plugin utils] display_name: Vendor update
09:58:51 [Plugin utils] description: A plugin to schedule vendor database updates for mac based vendor resolution.

**Comment by jokob-sk** [comment]
@The1Waterman Can you please post the value of the `UNDIS_devices_to_import` setting? It might contain an non-ASCII character. From the looks of it it might be an em dash (—) - try to replace it with a hyphen (-).

**Comment by The1Waterman** [comment]
Thanks, I'm struggling to find this setting, I assume you are talking from
the web browers debugger, ie F12 in chrome ?

**Comment by jokob-sk** [comment]
Hi @The1Waterman,

You should be able to search for it in the Settings page in NAX, otherwise you should be able to find it under " Device scanners " -> "Un-Discoverable Devices" -> "UnDiscoverable Devices".

**Comment by itsmemac** [comment]
Tried above mentioned fixes, still can't get into the page
same popup
no errors in container log
![image](https://github.com/user-attachments/assets/7c7e6e60-6f5c-41fe-980c-5e9e0b75a06b)

**Comment by itsmemac** [comment]
Switching to dev image doesn't show any devices and just the popup shows now and then
![image](https://github.com/user-attachments/assets/06a2fdc0-e38f-4ac3-9e75-415f8ee2bb71)

**Comment by jokob-sk** [comment]
Hi @itsmemac,

Can you please post your app.log after enabling debug?

**Comment by thefunkygibbon** [comment]
> @thefunkygibbon I think there is restart for you happening or some error might be logged in the logs for your instance as well. Can you check the log to see if there are any errors?

I see nothing in my docker logs which indicate any kind of restarting of the container or crashing.   I cannot access the netalert logs as I don't seem to have a log file contained within the persistent storage folders. 

the only thing i see in my docker logs show the following


`09:30:36 [Config] Number of Plugins to load: 18
09:30:36 [Config] Plugins to load: ['OMDSDN', 'ARPSCAN', 'PIHOLE', 'INTRNT', 'NMAP', 'NSLOOKUP', 'SMTP', 'CSVBCKP', 'DBCLNP', 'MAINT', 'NEWDEV', 'NTFPRCS', 'PHOLUS', 'SETPWD', 'SYNC', 'UI', 'VNDRPDT', 'WORKFLOWS']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/server/__main__.py", line 209, in <module>
    sys.exit(main())       
             ^^^^^^
  File "/app/server/__main__.py", line 139, in main
    process_scan(db)
  File "/app/server/networkscan.py", line 41, in process_scan
    update_devices_data_from_scan (db)
  File "/app/server/device.py", line 428, in update_devices_data_from_scan
    dev_Icon = guess_icon(device['dev_Vendor'], device['dev_MAC'], device['dev_LastIP'], device['dev_Name'], default_icon)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/server/device.py", line 640, in guess_icon
    vendor = vendor.lower()
             ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
09:30:36 [API] Updating table_settings.json file in /front/api
09:30:36 [Config] Imported new config`

**Comment by thefunkygibbon** [comment]
also 
`
09:30:34 [Process Scan] Updating Devices Info
            [INSTALL] 🚀 Starting app (:20211)
        
08:30:35 [MAIN] Setting up ...
08:30:35 [conf.tz] Setting up ...

 
08:30:35 The backend restarted (started). If this is unexpected check https://bit.ly/NetAlertX_debug for troubleshooting tips.

 
08:30:35 Permissions check (All should be True)
`

**Comment by thefunkygibbon** [comment]
but , if those events don't seem to tie in to me testing the popup notification.   and i can refresh the page multiple times and it doesn't "restart"

**Comment by itsmemac** [comment]
> Hi @itsmemac,
> 
> Can you please post your app.log after enabling debug?

Now it wierdly seems to work but the popup keeps popping up now and then
 only errors in app.log

Traceback (most recent call last):
  File "/app/front/plugins/pholus_scan/pholus/pholus3.py", line 1190, in <module>
    main()
  File "/app/front/plugins/pholus_scan/pholus/pholus3.py", line 1060, in main
    ipn = ipaddress.ip_network(values.rdns_scanning)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ipaddress.py", line 74, in ip_network
    return IPv4Network(address, strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ipaddress.py", line 1544, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: 192.168.0.1/24 has host bits set

16:10:07 [PHOLUS] ⚠ ERROR - Pholus Scan - check logs
16:10:07 [PHOLUS] Scan: Pholus FAIL - check logs

**Comment by jokob-sk** [comment]
@thefunkygibbon 
> 
> I see nothing in my docker logs which indicate any kind of restarting of the container or crashing. I cannot access the netalert logs as I don't seem to have a log file contained within the persistent storage folders.
> 
> the only thing i see in my docker logs show the following
> 
> `09:30:36 [Config] Number of Plugins to load: 18 09:30:36 [Config] Plugins to load: ['OMDSDN', 'ARPSCAN', 'PIHOLE', 'INTRNT', 'NMAP', 'NSLOOKUP', 'SMTP', 'CSVBCKP', 'DBCLNP', 'MAINT', 'NEWDEV', 'NTFPRCS', 'PHOLUS', 'SETPWD', 'SYNC', 'UI', 'VNDRPDT', 'WORKFLOWS'] Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/app/server/__main__.py", line 209, in <module> sys.exit(main()) ^^^^^^ File "/app/server/__main__.py", line 139, in main process_scan(db) File "/app/server/networkscan.py", line 41, in process_scan update_devices_data_from_scan (db) File "/app/server/device.py", line 428, in update_devices_data_from_scan dev_Icon = guess_icon(device['dev_Vendor'], device['dev_MAC'], device['dev_LastIP'], device['dev_Name'], default_icon) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/app/server/device.py", line 640, in guess_icon vendor = vendor.lower() ^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'lower' 09:30:36 [API] Updating table_settings.json file in /front/api 09:30:36 [Config] Imported new config`
> 
> :edit: actually there is this but gives zero clue as to whats causing it..
> 
> `09:30:34 [Process Scan] Updating Devices Info [INSTALL] 🚀 Starting app (:20211)
> 
> 08:30:35 [MAIN] Setting up ... 08:30:35 [conf.tz] Setting up ... �
> 
> 08:30:35 The backend restarted (started). If this is unexpected check https://bit.ly/NetAlertX_debug for troubleshooting tips. �
> 
> 08:30:35 Permissions check (All should be True)`

This seems to be the same issue @franbri was experiencing. I pushed a fix in the `netalertx-dev` image. Can you try to switch over after creating backups of your setup? (backup at least the app.conf and devices.csv files)

**Comment by jokob-sk** [comment]
@itsmemac I just pushed a fix for this to the  `netalertx-dev` image. Can you try to switch over in about 15 minutes after the above build finishes - after creating backups of your setup? (backup at least the app.conf and devices.csv files)

**Comment by BambamNZ** [comment]
@jokob-sk just deployed the dev image as new container from a backup and it is working as expected, the pop-up showed up once, cleared cache and refreshed and pop-up did not return.

**Comment by BambamNZ** [comment]
> @jokob-sk just deployed the dev image as new container from a backup and it is working as expected, the pop-up showed up once, cleared cache and refreshed and pop-up did not return.

Mmmh may have said it is solved a bit quickly, closing and opening the browser / window and the pop-up re-appears

![image](https://github.com/user-attachments/assets/6d66c19c-5015-4ceb-950b-8faf8d7ec7ed)

With this log entry 

`16:01:10 The backend restarted (started). If this is unexpected check https://bit.ly/NetAlertX_debug for troubleshooting tips.`

**Comment by thefunkygibbon** [comment]
just installed dev,  been running for half hour now and the pop up has not occurred and i've not seen the restarting in the logs since either.     so looks positive, but will keep checking over the next day or so.  

thanks.

let me know when i should pop back to the maintrain release code.

**Comment by jokob-sk** [comment]
@thefunkygibbon glad to hear that - I might push out a hotfix over the weekend - let's see

@BambamNZ Can you post the app.log error that is shown before the restart? You might need to check the docker logs (e.g. via Portainer)

**Comment by BambamNZ** [comment]
> @thefunkygibbon glad to hear that - I might push out a hotfix over the weekend - let's see
> 
> @BambamNZ Can you post the app.log error that is shown before the restart? You might need to check the docker logs (e.g. via Portainer)

@jokob-sk 

Couple of lines earlier are these error messages

> 15:31:01 [Plugin utils] display_name: Un-Discoverable Devices
15:31:01 [Plugin utils] description: This plugin is to import undiscoverable devices from a file.
15:31:01 [Plugin utils] ---------------------------------------------
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/server/__main__.py", line 209, in <module>
    sys.exit(main())       
             ^^^^^^
  File "/app/server/__main__.py", line 139, in main
    process_scan(db)
  File "/app/server/networkscan.py", line 37, in process_scan
    create_new_devices (db)
  File "/app/server/device.py", line 252, in create_new_devices
    sql.execute(sqlQuery, (startTime, startTime))
sqlite3.OperationalError: near "L": syntax error
15:31:01 [Plugin utils] display_name: Vendor update
15:31:01 [Plugin utils] description: A plugin to schedule vendor database updates for mac based vendor resolution.
15:31:01 [Plugin utils] ---------------------------------------------
15:31:01 [Plugin utils] display_name: Website monitor
15:31:01 [Plugin utils] description: This plugin is to monitor status changes of services or websites.
15:31:01 [Plugin utils] ---------------------------------------------
15:31:01 [Plugin utils] display_name: Workflows
15:31:01 [Plugin utils] description: A plugin to adjust behavior of workflows.

I have loaded the latest Dev image since and prompted me once again to Clear Cache etc. and has been stable since then

**Comment by thefunkygibbon** [comment]
i wanted to make a change to the settings and it no longer seems to want to save/apply them now!?

**Comment by thefunkygibbon** [comment]
no worries, I think i noticed it updating overnight on my watchtower... but i'll re-pull it now

**Comment by thefunkygibbon** [comment]
yep that works now.  cheers.  no need to apologise :-)

**Comment by jokob-sk** [comment]
@BambamNZ hummm, the error message is interesting. There might be a character passed to a sql query breaking it. Can you please try to enable debug or trace and post the log if there's more useful information? Please disable trace shortly after as it produces big log files.

Thanks for the help in advance,
J

**Comment by jokob-sk** [comment]
@thefunkygibbon glad to hear that 🙂

**Comment by BambamNZ** [comment]
> @BambamNZ hummm, the error message is interesting. There might be a character passed to a sql query breaking it. Can you please try to enable debug or trace and post the log if there's more useful information? Please disable trace shortly after as it produces big log files.
> 
> Thanks for the help in advance, J

Hey @jokob-sk  

I've been unable to replicate the error messages at this point, if I see it again will update.

**Comment by ca1986** [comment]
The same popup issue as described above is happening to me regardless of emptying the cache, refreshing, different browser, different computer etc.  The application is essentially unusable.

**Comment by jokob-sk** [comment]
Hi @ca1986,

As per the previous messages, can you please check and post the app.log to see if the app restarts? The backed is probably in a restart loop.

Thanks in advance,
J

**Comment by jokob-sk** [comment]
Thanks for the report  and help everyone - the underlying issues from this thread should be fixed in the latest release in ~15 min from now -> Closing

**Comment by thefunkygibbon** [comment]
FYI i've just checked again this morning and i'm getting the same issue.  (still on dev channel)

**Comment by jokob-sk** [comment]
@thefunkygibbon could you please open a new issue with the necessary details to debug your problem further?

**Comment by jokob-sk** [comment]
Locking this as the reappearing notification is a symptom only. If you experience it, please check your log. Likely the application is restarting in the background. Open a new issue so that I can help you to resolve the problem.
