### ISSUE TITLE
SETPWD plugin does not correctly set the password

### ISSUE THREAD

**Issue by metril** [jokob-sk/NetAlertX#793]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Setting the password via the web interface results in the unhashed password written to the app.conf. When the SETPWD is enabled, you cannot login to the webui even if the password is correct.

### Expected Behavior

The sha256 hash of the password should be written to the app.conf as described in the conf file and as the transformer dictates.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thanks a lot for the report and details.

This should be fixed in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

Thanks in advance,
j

**Comment by metril** [comment]
With the most recent dev version, the SAVE button doesn't work. I can check the box and type in a password, but now I cannot SAVE the settings.

**Comment by jokob-sk** [comment]
Ah...sorry - can you please re-pull in ~15 min - I forgot to remove some debugging code 🤦‍♂️

**Comment by metril** [comment]
It works now with the most recent dev version.

**Comment by jokob-sk** [comment]
Thanks for checking! I might push out a new release soon as there are some bugs I'd like to fix in production.

**Comment by jokob-sk** [comment]
Thanks for the report  @metril - this should be fixed in the latest release in ~15 min from now -> Closing
