### ISSUE TITLE
Docker setup fails with error response from daemon: create local/path/config: "local/path/config" includes invalid characters for a local volume name

### ISSUE THREAD

**Issue by BreakfastSerial** [jokob-sk/NetAlertX#794]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Attempting to set up NetAlertX, as documented in the quick start guide fails with the following error message:

```
localhost:~/netalertx# docker run -d --rm --network=host \
>   -v local/path/config:/app/config \
>   -v local/path/db:/app/db \
>   -e TZ=Europe/Berlin \
>   -e PORT=20211 \
>   jokobsk/netalertx:latest
docker: Error response from daemon: create local/path/config: "local/path/config" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```

I'm on an Alpine Linux (3.20) VM.

### Expected Behavior

I expected the docker container to start and expose the service.

### Steps To Reproduce

1. On Alpine Linux 3.20
2.  Execute `localhost:~/netalertx# docker run -d --rm --network=host \
>   -v local/path/config:/app/config \
>   -v local/path/db:/app/db \
>   -e TZ=Europe/Berlin \
>   -e PORT=20211 \
>   jokobsk/netalertx:latest`

### app.conf

```python
-
```

### docker-compose.yml

```python
-
```

### What branch are you running?

Production

### app.log

-

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @BreakfastSerial ,

Pleas note that these two lines are examples and you have to supply a correct local path:

```
>   -v local/path/config:/app/config \
>   -v local/path/db:/app/db \
```

Please replace `local/path/` with an existing path on your server with a `config` and `db` folder.

**Comment by BreakfastSerial** [comment]
Oh wow, that was dumb of me. So sorry for wasting your time and thanks for your civil answer! I was hastily comparing NetAlertX and WatchYourLan and just copy/pasted the docker quick setup commands without thinking. It works now just fine. Thanks!

**Comment by jokob-sk** [comment]
Haha all good!
