### ISSUE TITLE
NetAlertX error: "no such table: main.AppEvents"

### ISSUE THREAD

**Issue by theincredibleman** [jokob-sk/NetAlertX#797]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

NetAlertX does not start

### Expected Behavior

NetAlertX starts without errors

### Steps To Reproduce

Running docker compose up -d

### docker-compose.yml

```python
version: "3.6"
services:
  pialert:
    container_name: "pialert"
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: "unless-stopped"
    volumes:
      - "pialert-config:/app/config"
      - "pialert-data:/app/db"
volumes:
  pialert-config:
  pialert-data:
```

### What branch are you running?

Production

### app.log

11:25:20 The backend restarted (started). If this is unexpected check https://bit.ly/NetAlertX_debug for troubleshooting tips.
11:25:20 

11:25:20 Permissions check (All should be True)
11:25:20 ------------------------------------------------
11:25:20   /config/app.conf |  READ  | True
11:25:20   /config/app.conf |  WRITE | True
11:25:20   /db/app.db       |  READ  | True
11:25:20   /db/app.db       |  WRITE | True
11:25:20 ------------------------------------------------
11:25:20 [Setup] Attempting to fix permissions.
11:25:20 [Setup] Attempting to fix permissions.
11:25:20 [Database] Opening DB

            [INSTALL] 🚀 Starting app (:20211)

        
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/server/__main__.py", line 209, in <module>
    sys.exit(main())       
             ^^^^^^
  File "/app/server/__main__.py", line 76, in main
    db.upgradeDB()
  File "/app/server/database.py", line 188, in upgradeDB
    self.sql.execute(f'''
sqlite3.OperationalError: no such table: main.AppEvents
11:25:21 [MAIN] Setting up ...
11:25:21 [conf.tz] Setting up ...
11:25:21 

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by theincredibleman** [comment]
Looked like a corrupt database, tried removing and recreating volumes and importing database which gave me the error that the database was corrupt. So I bit the bullet and started over with a fresh database, fortunately I was able to use my old config file.

**Comment by jokob-sk** [comment]
Hey @theincredibleman ,

Sorry to hear that. You can restore your devices from the devices.csv files if you were able to keep those: https://github.com/jokob-sk/NetAlertX/blob/main/docs/BACKUPS.md

Hope this helps,
j

**Comment by theincredibleman** [comment]
Thanks, I’ll keep that in mind should it ever happen again. 
Otherwise love the project, keep up the good work!
