### ISSUE TITLE
Device icons appear as text in the dropdown

### ISSUE THREAD

**Issue by alnviana** [jokob-sk/NetAlertX#802]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

On a new installation, when I open the list of icons on the devices, some appear as text.
![2024-09-22_22-54-45_firefox](https://github.com/user-attachments/assets/9f7652cb-a3f9-4ffb-980e-2c9588b22696)

The list is as follows:
1. PGkgY2xhc3M9J2ZhIGZhLXdpZmknPjwvaT4=
2. PGkgY2xhc3M9ImZhIGZhLWNvbXB1dGVyIj48L2k+
3. PGkgY2xhc3M9ImZhIGZhLWV0aGVybmV0Ij48L2k+
4. PGkgY2xhc3M9ImZhIGZhLWdhbWVwYWQiPjwvaT4
5. PGkgY2xhc3M9ImZhIGZhLWdsb2JlIj48L2k+
6. PGkgY2xhc3M9ImZhIGZhLWxhcHRvcCI+PC9pPg==
7. PGkgY2xhc3M9ImZhIGZhLWxpZ2h0YnVsYiI+PC9pPg==
8. PGkgY2xhc3M9ImZhIGZhLXNoaWVsZCI+PC9pPg==
9. PGkgY2xhc3M9ImZhIGZhLXdpZmkiPjwvaT4
10. PGkgY2xhc3M9J2ZhIGZhLWdhbWVwYWQnPjwvaT4

Which converting manually would leave:
1. `<i class='fa fa-wifi'></i>`
2. `<i class="fa fa-computer"></i>`
3. `<i class="fa fa-ethernet"></i>`
4. `<i class="fa fa-gamepad"></i>`
5. `<i class="fa fa-globe"></i>`
6. `<i class="fa fa-laptop"></i>`
7. `<i class="fa fa-lightbulb"></i>`
8. `<i class="fa fa-shield"></i>`
9. `<i class="fa fa-wifi"></i>`
10. `<i class='fa fa-gamepad'></i>`

Problems encountered:
1. Items 4, 10 and 11 do not convert to icon. Apparently the problem occurs with items that doesn't end in + or =.
2. The items 1, 9, 4 and 10 are duplicated and one of the two should be removed. (Check if any code has a reference before removing)

### Expected Behavior

The icons should appear, not the text. Perhaps it would be a good idea to remove the duplicates.

### Steps To Reproduce

1. Open the list of devices.
2. Edit a device.
3. Open the list of icons.

### app.conf

Use the default file, generated when creating a new environment.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @alnviana ,

Thanks for the report. This should be available in the next release. You can  switch to the `netalertx-dev` docker image (backup everything at first) to test this. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

Thanks in advance,
j

**Comment by alnviana** [comment]
I tested it here in a second container, and it really is fixed there, so I think you can close this issue.

Just one observation:
In the default configuration there, the last two icons in the list of predefined icons are duplicated:
PGkgY2xhc3M9ImZhIGZhLWdhbWVwYWQiPjwvaT4= `<i class="fa fa-gamepad"></i>`

Two icons don't appear in the icon selection list inside the device, but I thought it would be interesting to let you know.

**Comment by jokob-sk** [comment]
Thanks for checking! The duplicate icons should be fixed in the latest dev image.

**Comment by jokob-sk** [comment]
Thanks for the report  @alnviana - this should be fixed in the latest release in ~15 min from now -> Closing
