### ISSUE TITLE
Vendor name containing a special char

### ISSUE THREAD

**Issue by vemore** [jokob-sk/NetAlertX#805]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

I have a device which Vendor name is "Micro-Star INT'L CO., LTD".

The char "'" cause an error when the device is newly detected.

> netalertx  | Traceback (most recent call last):
> netalertx  |   File "<frozen runpy>", line 198, in _run_module_as_main
> netalertx  |   File "<frozen runpy>", line 88, in _run_code
> netalertx  |   File "/app/server/__main__.py", line 209, in <module>
> netalertx  |     sys.exit(main())
> netalertx  |              ^^^^^^
> netalertx  |   File "/app/server/__main__.py", line 139, in main
> netalertx  |     process_scan(db)
> netalertx  |   File "/app/server/networkscan.py", line 37, in process_scan
> netalertx  |     create_new_devices (db)
> netalertx  |   File "/app/server/device.py", line 252, in create_new_devices
> netalertx  |     sql.execute(sqlQuery, (startTime, startTime))

> An error occurred: near "L": syntax error

### Expected Behavior

The device Vendor Name does not cause any error

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thanks for the report  @vemore  - this should be fixed in the latest release in ~15 min from now -> Closing
