### ISSUE TITLE
Minor: Changing settings does not get applied on first save

### ISSUE THREAD

**Issue by Jozko568** [jokob-sk/NetAlertX#818]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

As mentioned in #816 Some settings do not get applied on first save possibly due to cache. 
<ins>Applying the settings again without any change fixes the issue. </ins>

I was able to observe this issue when changing `UI_shown_cards` and `UI_device_columns`. 
Possibly other UI settings are affected as well. Settings show as applied but when you go to check if the change was actually done, the page looks the same. This also persists if I clean the browser cache. 

Disabled cards: 

![image](https://github.com/user-attachments/assets/2d909fd9-6558-4222-819c-5856113c9753)

See that the down and favorites cards are still visible even though they have been disabled.

![image](https://github.com/user-attachments/assets/36f25bea-763e-4e5e-bcbb-d7bca46ff2f1)

Unfortunately I am not able to submit a PR for a fix due to my missing programming knowledge :/ 

### Expected Behavior

Settings are saved on first save

### Steps To Reproduce

1. Make a change in `UI_shown_cards` 
2. Save the changes
3. See the Devices tab, there should not be any change. 
4. Go back to Settings, Save it without any other change
5. See the Devices tab, changes now should be visible

### What branch are you running?

Dev

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thanks for the report - adding it to the backlog if someone wants to spend time on this.
