### ISSUE TITLE
Column ordering doesn't persist after cookie expiration

### ISSUE THREAD

**Issue by TheCBiker** [jokob-sk/NetAlertX#824]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

In version: v24.9.26 the selected column sorting and the display of all entries are not saved in the device view. It worked in the previous version. Use the latest version of Chrome.

### Expected Behavior

column sorting should be saved

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @TheCBiker ,

Could you please let me know the steps on how to reproduce the issue? I tried to change the ordering of a few columns and it seems to persist after a refresh. See video below.
![ezgif-1-83837d9f84](https://github.com/user-attachments/assets/dd81dcb0-3af1-4966-b72f-06ff35b1f9c9)

**Comment by TheCBiker** [comment]
Yes, but ist lose the Settings After close the chrome Browser.Thank youVon Unterwegs gesendetAm 07.10.2024 um 13:08 schrieb jokob-sk ***@***.***>:﻿
Hi @TheCBiker ,
Could you please let me know the steps on how to reproduce the issue? I tried to change the ordering of a few columns and it seems to persist after a refresh. See video below.
ezgif-1-83837d9f84.gif (view on web)

**Comment by TheCBiker** [comment]
﻿Yes, but ist lose the Settings After close the chrome Browser.Thank youVon Unterwegs gesendetAm 07.10.2024 um 13:08 schrieb jokob-sk ***@***.***>:﻿
Hi @TheCBiker ,
Could you please let me know the steps on how to reproduce the issue? I tried to change the ordering of a few columns and it seems to persist after a refresh. See video below.
ezgif-1-83837d9f84.gif (view on web)

**Comment by TheCBiker** [comment]
I prefer to display **all** devices in the device view and sort them by IP address. As soon as the browser is closed, the settings are forgotten. However, when you refresh, they are retained.

thanks

**Comment by jokob-sk** [comment]
Hi @TheCBiker ,

I changed the cookie to expire in 90 days. This is renewed every time you change the order. So, from a users perspective the settings will be persistent. 

This should be available in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

Thanks in advance,
j

**Comment by TheCBiker** [comment]
Great. Now it works. But my homepage widget brings now an API error

**Comment by jokob-sk** [comment]
Great. Can you please open a new issue for the API error?

**Comment by jokob-sk** [comment]
released -> closing
