### ISSUE TITLE
Easier plugin selection

### ISSUE THREAD

**Issue by stanelie** [jokob-sk/NetAlertX#826]
Hello.
I find I have trouble enabling or disabling a plugin in the plugin list without accidentally un-selecting all the plugins (I never know if I need to hold command, shift, ctrl, since I move from mac to pc often), and then, I don't know which plugins were enabled or not.
To me, a list of checkboxes to tick would be better.

**Comment by jokob-sk** [comment]
Hi @stanelie, 

Checkboxes would make break the UI, but I have an alternative UI component. It was however not as extensibly tested as the current one. 

This should be available in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

👉If I don't get a confirmation that this is working I might pull out the feature to prevent bugs. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

![image](https://github.com/user-attachments/assets/d268b052-e081-4e29-a4dc-964c15d2dd29)


Thanks in advance,
j

**Comment by jokob-sk** [comment]
oh, did you already test it?

**Comment by stanelie** [comment]
Yes. It is now impossible for me to inadvertently deselect all my plugins. I've tried enabling a few more plugins, and it worked, their respective settings appeared on the list.

Probably unrelated, but I have to wait a while sometimes for the settings page to load, with a "Loading" popup at the top?

**Comment by jokob-sk** [comment]
Thanks for that! Yes, loading times depend on the number of enabled plugins and system specification that is hosting the app.

**Comment by jokob-sk** [comment]
released -> closing
