### ISSUE TITLE
nmap

### ISSUE THREAD

**Issue by MimaHack** [jokob-sk/NetAlertX#831]
17:01:13 [NMAPDEV] nm[host]: {'hostnames': [{'name': '', 'type': ''}], 'addresses': {'ipv4': '172.19.0.9'}, 'vendor': {}, 'status': {'state': 'up', 'reason': 'echo-reply'}}
17:01:13 [NMAPDEV] Hostname: (unknown), IP: 172.19.0.9, MAC: , Vendor: 
17:01:13 [NMAPDEV] Skipping: (unknown), IP or MAC missing
17:01:13 [NMAPDEV] scan_args: ['sudo', 'nmap', '-sn', '-PR', '-oX', '-', '10.250.250.0/29', '-e', 'ens160']

**Comment by jokob-sk** [comment]
Please open a new issue using the template. I need additional info in order to help you.
