### ISSUE TITLE
Mikrotik plugin IP addresses not showing up

### ISSUE THREAD

**Issue by stanelie** [jokob-sk/NetAlertX#835]
Hello.
I have just enabled the Mikrotik plugin, and it added all the devices from the DHCP leases, but they have no IP addresses populated . Is there anything I can do to fix this?

![Screen Shot 2024-10-10 at 8 22 39 AM](https://github.com/user-attachments/assets/a3692b52-5a3d-4e51-a875-e63537ef38b6)

**Comment by stanelie** [comment]
Oups, never mind, I shows the IP addresses now. Probably a cache problem, as you mentioned. You can close this ticket. Thanks!

**Comment by stanelie** [comment]
I've sent the log to you via email.
Thanks!

**Comment by jokob-sk** [comment]
Hi @stanelie ,

Thanks for the logs, I think I've found the issue.

This should be available in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.


Thanks in advance,
j

**Comment by jokob-sk** [comment]
released -> closing
