### ISSUE TITLE
Homepage Widget API Error

### ISSUE THREAD

**Issue by TheCBiker** [jokob-sk/NetAlertX#838]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Since version 24.10.12 an API error appears in the homepage widget.
![Unbenannt-1](https://github.com/user-attachments/assets/84a277a3-76c3-4cba-bf9d-44b47766a0c8)

### Expected Behavior

Correct display of data fields in the homepage widget.

### What branch are you running?

Production

### app.log

Error log from Homepage Widget:

API-Fehler: Invalid data
URL: http://192.168.XXX.XXX:20211/php/server/devices.php?action=getDevicesTotals
Antwortdaten:

<link rel="stylesheet" href="css/app.css">

<!DOCTYPE html>
<html>
<head>
 <meta charset="utf-8">
  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
 <meta http-equiv="Pragma" content="no-cache" />
  <meta http-equiv="Expires" content="0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>NetAlert X | Log in</title>
  
 <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  
  <link rel="stylesheet" href="lib/AdminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css">
 
 <link rel="stylesheet" href="lib/AdminLTE/bower_components/font-awesome/css/fontawesome.min.css">
  
 <link rel="stylesheet" href="lib/AdminLTE/bower_components/Ionicons/css/ionicons.min.css">
  
  <link rel="stylesheet" href="lib/AdminLTE/dist/css/AdminLTE.min.css">
  
  <link rel="stylesheet" href="lib/AdminLTE/plugins/iCheck/square/blue.css">
  
  <link rel="stylesheet" href="lib/AdminLTE/bower_components/font-awesome/css/fontawesome.min.css">
 <link rel="stylesheet" href="lib/AdminLTE/bower_components/font-awesome/css/solid.css">
  <link rel="stylesheet" href="lib/AdminLTE/bower_components/font-awesome/css/brands.css">
  <link rel="stylesheet" href="lib/AdminLTE/bower_components/font-awesome/css/v5-font-face.css">
  
  <link id="favicon" rel="icon" type="image/x-icon" href="img/NetAlertX_logo.png">

  
  <link rel="stylesheet" href="/css/offline-font.css">
</head>
<body class="hold-transition login-page">
<div class="login-box login-custom">
  <div class="login-logo">
    <a href="/index2.php">Net<b>Alert</b><sup>x</sup></a>
  </div>
  
  <div class="login-box-body">
    <p class="login-box-msg">Enter your password</p>
      <form action="index.php" method="post">
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password" name="loginpassword">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox" name="PWRemember">
                <div style="margin-left: 10px; display: inline-block; vertical-align: top;"> 
                  Remember<br><span style="font-size: smaller">(valid for 7 days)</span>
                </div>
            </label>
          </div>
        </div>
        
        <div class="col-xs-4" style="padding-top: 10px;">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Log in</button>
        </div>
         
      </div>
    </form>

    <div style="padding-top: 10px;">
      <button class="btn btn-xs btn-primary btn-block btn-flat" onclick="Passwordhinfo()">Password Information</button>
    </div>

  </div>
  

 <div id="myDIV" class="box-body" style="margin-top: 50px; display: none;">
      <div class="alert alert-info alert-dismissible">
          <button type="button" class="close" onclick="Passwordhinfo()" aria-hidden="true">X</button>
          <h4><i class="icon fa fa-info"></i>Password Information</h4>
          <p>Passwords are set via the Set Password plugin. Check the <a target="_blank" href="https://github.com/jokob-sk/NetAlertX/tree/main/front/plugins/set_password">SETPWD docs</a> if you have issues logging in.</p>
     </div>
  </div>

</div>

<script src="lib/AdminLTE/bower_components/jquery/dist/jquery.min.js"></script>

<script src="lib/AdminLTE/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

<script src="lib/AdminLTE/plugins/iCheck/icheck.min.js"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blu
e',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });

function Passwordhinfo() {
  var x = document.getElementById("myDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
} 

</script>
</body>
</html>

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @TheCBiker ,

I assume you have a password set? If so, try to disable the password functionality.

**Comment by TheCBiker** [comment]
ok if I remove the password it works. But why did it work with password in the previous version?
![Unbenannt-1](https://github.com/user-attachments/assets/271af82a-0bb3-4504-b32a-01208186f5ef)

**Comment by jokob-sk** [comment]
Glad to hear that! These changes should increase the overall security of the application going forward. I might create some alternative ways to retrieve the data, so that it's accessible even when a password is set, but the first step is to improve the security.

**Comment by TheCBiker** [comment]
I understand. thank you

**Comment by shamoon** [comment]
Homepage dev here. So to clarify the api previously did not use any kind of auth and at some point you may add it? I’ll follow the issue here for if / when you can do and we’ll update on our side to support

**Comment by jokob-sk** [comment]
Thanks @shamoon 🙏if you have any suggestions how other apps are handling this, please let me know. My first thoughts would be either to exclude this API path from authentication, create a new endpoint not requiring authentication or adding support for for a API token/bearer/authentication header.  

There is already a `SYNC_api_token` header bypass build in to support the synchronization plugin if that's something we can use if Homepage supports passing it in the request.

https://github.com/jokob-sk/NetAlertX/blob/3d9bf32ec7131d5d133fc2224ddd19375daa5f47/front/php/templates/security.php#L58

Thanks in advance for the help.

**Comment by shamoon** [comment]
I think token / bearer auth is ideal choice (I think this app deals with sensitive-enough stuff that leaving it completely open isn't ideal). But of course I don't know what your codebase is like and how much of a pain that is (generally Im happy to help with PRs etc but don't really have the bandwidth at the moment).

I'd say low priority but I'll follow along!

**Comment by jokob-sk** [comment]
Thanks, understandable. So if Homepage already supports consuming bearer tokens, then this should be already supported in NetAlertX in the current version. 

Auth header: `Authorization`
Format: `Bearer <SYNC_api_token>`


https://github.com/jokob-sk/NetAlertX/blob/3d9bf32ec7131d5d133fc2224ddd19375daa5f47/front/php/templates/security.php#L34-L65

Let me know if I need to support a different format or if this is already workable.

**Comment by shamoon** [comment]
Oh cool, yea, lemme try it out!

Sorry for being lazy, Im not super familiar with the app, where do you get the SYNC_api_token?

**Comment by shamoon** [comment]
Got it, and yup, works! 😎

I'll PR homepage, feel free to close this =)

<img width="982" alt="Screenshot 2024-10-12 at 3 21 18 PM" src="https://github.com/user-attachments/assets/e4bc19db-86e5-43d1-915b-d53f6f9daf1e">

**Comment by shamoon** [comment]
Oh sorry, spoke too soon. Hmm

**Comment by shamoon** [comment]
LOL, _sorry for all the noise!_ works great =)

(was having some weirdness with saving the settings that confused me)

**Comment by jokob-sk** [comment]
Nah all good :) Thanks for the help and supporting the app in Homepage

For anyone reading - you set the token in NetAlertX here:

![image](https://github.com/user-attachments/assets/e9ee090f-8c4a-4b49-b60a-398faad75fcd)

**Comment by Byrnesdigital** [comment]
> Nah all good :) Thanks for the help and supporting the app in Homepage
> 
> For anyone reading - you set the token in NetAlertX here:
> 
> ![image](https://private-user-images.githubusercontent.com/96159884/375991083-e9ee090f-8c4a-4b49-b60a-398faad75fcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODM3NzAsIm5iZiI6MTcyOTA4MzQ3MCwicGF0aCI6Ii85NjE1OTg4NC8zNzU5OTEwODMtZTllZTA5MGYtOGM0YS00YjQ5LWI2MGEtMzk4ZmFhZDc1ZmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEyNTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYTc4NDEzZTc0OTNjYTdjNzFkYWY3NGYxOTMyMjg2MjljMWM0YjdkNTFhNGE5NTNjNTYxZjQyMTRjNjRiYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4kIeETBMdJbp0SH4P38Ro9KKgtIBppFBColAWOFfxgk)

My apologies but how does one generate an API token? This is what I'm currently staring at 
![image](https://github.com/user-attachments/assets/01bcf886-b782-4ec0-a7dd-97be85fe17be)

And this is the API error I'm getting on Homepage, I'm assuming for not having the api token set up in services.
![image](https://github.com/user-attachments/assets/8feb4cdc-31fd-4388-bfcc-56e1e6d96174)

**Comment by shamoon** [comment]
Did you try… typing one into that field?

**Comment by Byrnesdigital** [comment]
> Did you try… typing one into that field?

Of course....not. Wasn't sure if it was the kinda thing that had to be generated by the app itself. Managed to create a token, pop it in there, and now I'm good to go.

**Comment by jokob-sk** [comment]
Added a button to generate one and mentioned in teh description taht any value can be used: 
![image](https://github.com/user-attachments/assets/7bae2229-ce8d-4b04-96c3-70449591001b)

**Comment by jokob-sk** [comment]
released -> closing
