### ISSUE TITLE
ERROR: MQTT service not set up correctly. Check your app.conf MQTT_* variables.

### ISSUE THREAD

**Issue by derekoharrow** [jokob-sk/NetAlertX#841]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

I'm trying to use MQTT alerting to Home Assistant and it is not working - see app.log extract below.

### Expected Behavior

NetAlertX should publish devices and statistics to MQTT, but this isn't happening.

### Steps To Reproduce

Tried with below app.conf. I've also tried changing the run schedule to always_after_scan, on_new_device, etc. I've tried changing the MQTT broker to mqtt.lan (the DNS name for my MQTT server). 

### app.conf

```python
MQTT_RUN='schedule'
MQTT_CMD='python3 /app/front/plugins/_publisher_mqtt/mqtt.py devices={devices}'
MQTT_RUN_SCHD='*/3 * * * *'
MQTT_RUN_TIMEOUT=10
MQTT_BROKER='192.168.1.14'
MQTT_PORT=1883
MQTT_TLS=False
MQTT_USER=''
MQTT_PASSWORD=''
MQTT_SEND_STATS=True
MQTT_DEVICE_ID='netalertx'
MQTT_DEVICE_NAME='NetAlertX'
MQTT_SEND_DEVICES=True
MQTT_topic_root='netalertx'
MQTT_DEVICES_SQL='select rowid, * from Devices where dev_Name not in ({s-quote}null{s-quote}, {s-quote}(name not found){s-quote}, {s-quote}(unknown){s-quote})'
MQTT_QOS=0
MQTT_VERSION=5
MQTT_DELAY_SEC=2
```

### docker-compose.yml

```python
netalertx:
    privileged: true
    container_name: netalertx
    image: "jokobsk/netalertx-dev"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data/appdata/docker/netalertx/config:/app/config
      - /data/appdata/docker/netalertx/db:/app/db
      - /mnt/network.lan:/mnt/network.lan
      - /mnt/pi3.lan:/mnt/pi3.lan
      - /etc/resolv.conf:/etc/resolv.conf:ro
    environment:
      - TZ=Europe/London
      - PORT=20211
```

### What branch are you running?

Production

### app.log

11:47:13 [Plugin utils] display_name: MQTT publisher
11:47:13 [Plugin utils] description: A plugin to publish a notification via MQTT to Home Assistant.
11:47:14 [Config] Plugins to load: ['ARPSCAN', 'AVAHISCAN', 'INTRNT', 'NMAPDEV', 'NSLOOKUP', 'MQTT', 'PUSHOVER', 'CSVBCKP', 'DBCLNP', 'MAINT', 'NEWDEV', 'NTFPRCS', 'PHOLUS', 'SETPWD', 'SYNC', 'UI', 'VNDRPDT', 'WORKFLOWS']
11:47:14 [Scheduler] - Scheduler run for MQTT: NO
11:49:47 [Scheduler] - Scheduler run for MQTT: YES
11:49:48 [Plugin utils] display_name: MQTT publisher
11:49:49 [MQTT](publisher) In script
11:49:49 [Check Config] ⚠ ERROR: MQTT service not set up correctly. Check your app.conf MQTT_* variables.
11:49:49 [MQTT] ⚠ ERROR: Publisher notification gateway not set up correctly. Check your app.conf MQTT_* variables.
11:49:49 [Plugins] No output received from the plugin "MQTT"

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by derekoharrow** [comment]
Also, if I go into Integrations -> Plugins -> MQTT Publisher it doesn't show any objects/events/history at all.

**Comment by jokob-sk** [comment]
Hi,

The user name and password are mandatory. Please check the guide for details : https://github.com/jokob-sk/NetAlertX/blob/main/docs/HOME_ASSISTANT.md
