### ISSUE TITLE
Settings: Search as you type and Save user interface

### ISSUE THREAD

**Issue by joel72265** [jokob-sk/NetAlertX#843]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

**New Feature**: Suggestion to have the Search and Save button on the Settings page than on an overlay. 

### Describe the solution you'd like

When a user starts typing in the search box, all the related field boxes are filtered, kinda like in Chrome/Firefox search settings. Maybe even move the Search-Save box to the top right 

![netalertx-07](https://github.com/user-attachments/assets/1b2af605-011d-409f-aa42-9ec0dd7e2785)

### Describe alternatives you've considered

None

### Anything else?

NA

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [ ] Yes
- [X] No

**Comment by jokob-sk** [comment]
Hi @joel72265,

Can you please provide information why you'd prefer to move the button to the top?

I had it at the bottom but it was annoying to always scroll down. I also have to think about mobile designers.

If you can mock up an example for mobile and desktop, that would help me understand the benefits better probably.

I definitely want the button and filter always visible, that's why I picked an overlay.

Thanks in advance,
J

**Comment by joel72265** [comment]
sure, here are my 2c

1) Can you please provide information why you'd prefer to move the button to the top ? _**top**: ergonomics and usability with regards to the Search box, the Save button saves space if its together with the search box. **top-right**: majority of users are right-handed so the cursor and scroll bars are on the right_

2) I had it at the bottom but it was annoying to always scroll down. I also have to think about mobile designers. - _I agree having it at the bottom of the page is not a good idea.

3) If you can mock up an example for mobile and desktop, that would help me understand the benefits better probably. - _done, there might be better UI designers here I hope they chime in_

4) I definitely want the button and filter always visible, that's why I picked an overlay. - _If each Setting sub-group has ~10 options then when a User searches all the related options are filtered and the Searchbox, Save button are always visible. But if a sub-group has 15-20 options then the user would need to scroll down.


![netalertx-07](https://github.com/user-attachments/assets/d9d477df-734c-4f98-ab6f-b797a0f3d4fe)
![netalertx-08](https://github.com/user-attachments/assets/80f474a5-9beb-48e9-8065-09b9963ad3ab)

**Comment by jokob-sk** [comment]
Thansk a lot! How would this behave if you scroll down? Would it be an overlay or scroll up? 

![377029744-80f474a5-9beb-48e9-8065-09b9963ad3ab](https://github.com/user-attachments/assets/f8c6cd89-50a9-4bab-8db5-00558b6a72a2)

My opinion is that if scrolling down would hide the save button and the filter then that would be a worse user experience than the current design that is available. Frankly I don't see currently big benefits adjusting the UI here. If there are other users/designers with ideas how to solve for this, I'm happy for them to submit a PR. Requirements would be:

- Filter and save button always visible/accessible
- Design working on mobile and desktop
- Information density and scannability over over-simplified design choices 
- reduce the need of scrolling as much as possible

**Comment by jokob-sk** [comment]
no contributors -> closing for now
