### ISSUE TITLE
vendor field bug

### ISSUE THREAD

**Issue by stanelie** [jokob-sk/NetAlertX#844]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

The vendor field gets populated with the last word of a sentence only.
Example : "Dell inc." is the correct vendor according to a reverse mac database lookup of a mac address I have on my network. However, in NetAlertX, I only see "inc." as the vendor field. Same thing for "TELEMECANIQUE ELECTRIQUE", which shows up as "ELECTRIQUE" only.

### Expected Behavior

The whole name from the mac address database should show up, not just the last word.

Maybe it's related to https://github.com/jokob-sk/NetAlertX/issues/805 ?
I am running the DEV container

### What branch are you running?

Dev

**Comment by jokob-sk** [comment]
Hi @stanelie,

Can you please follow the template and provide the logs?

Are the correct vendors only missing from the devices from a certain plugin or is this happening to all devices? 

Logs help me to solve issues faster and I can be more effective with my time.

Thanks,
J

**Comment by stanelie** [comment]
I just had a look and it appears the issue has resolved itself.
I will try to investigate more before I file another bug report, maybe it was just a web browser cache issue this time.

Sorry about that.

**Comment by jokob-sk** [comment]
No problem! Thanks for helping me make the app better 🙏
