### ISSUE TITLE
After update NetalertX I get a Homepage api error

### ISSUE THREAD

**Issue by JackD-01** [jokob-sk/NetAlertX#845]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

After updating NetAlertX to v24.10.12(docker) the homepage software gives a api error.
It does not show the NetAlertX info on homepage software.
(I did refresh an delete tempfiles/cookies)
Nothing changes on the homepage software side, I run the latest version (v09.11)

Is there a change on how to get the info out of NetAlertX, do we now need perhaps a api key?. If this is the case than I have to post the bug on the Homepage. (GitHubhttps://github.com/gethomepage/homepage) But for now I put the possible bug/problem here first. because the problem started with the new NetAlertX update I did.

Hope you can help, I am not a programmer, just a happy NetAlertX user, so forgive me if I ask or say something "stupid"

Regards,
Jack

![ERROR_HOMEPAGE_NETALERTX](https://github.com/user-attachments/assets/677c649a-356e-44f3-a6f9-b31c0b614ddd)

![My Dashboard_ERROR](https://github.com/user-attachments/assets/32c179fd-5e06-449c-99b9-904868b09daf)

[ERROR_DATA_API_HOMEPAGE.txt](https://github.com/user-attachments/files/17394087/ERROR_DATA_API_HOMEPAGE.txt)

![HOMEPAGE SETTINGS_FOR_NETALERTX](https://github.com/user-attachments/assets/c3c22ed8-d6e7-4a64-9030-f99f235b532f)

### Expected Behavior

I would like to see "totaal", "connected", "new_devices" and "down_alerts again on my homepage software.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi there,

Please disable login or wait until the related Homepage version is released supporting NetAlertX instances with enabled login. See this issue for details:

https://github.com/jokob-sk/NetAlertX/issues/838

**Comment by jokob-sk** [comment]
Also, thanks for the detailed description, this is always appreciated 🙏

**Comment by JackD-01** [comment]
Thanks for the feedback, nice to read that I did not do something wrong :-) 
For now I disable login and wait for a new release of Homepage with support for enabled login.
I closed down access from outside my private network to NetAlertX for security. 

Thank you for your advice,

Regards,
Jack

**Comment by JackD-01** [comment]
Just some additional info for others with the same problem..

Took a closer look and you can run NetAlertX with login enabled with Homepage v09.11, as stated by jokob-sk
Add sync plugin in NetAlertX(if you don't already), generate a token and copy it into the "API token [n,h]" field, and set "when to run"
Use the same token in the services.yaml settings file from Homepage and you now have NetAlertX with logon enabled and you got the NetalertX info presented in the Homepage wigdet. 


.
![NetAlertX_sync_settings copy](https://github.com/user-attachments/assets/ab1e9c5a-dea5-4c99-b0b2-d691d55e73bf)

![Homepage_netalertx_settings copy 2](https://github.com/user-attachments/assets/03c4364a-4839-4598-a0ce-5c9efb3c89bd)

![with_api_token_and logon_enabled](https://github.com/user-attachments/assets/4d5e32af-e25b-435d-b563-afa8ce66a30f)
