### ISSUE TITLE
website discord links are invalid

### ISSUE THREAD

**Issue by thoraxe** [jokob-sk/NetAlertX#849]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

The website features links to the NetalertX Discord, but they are no longer valid.

### Expected Behavior

.

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @thoraxe ,

Thanks for the report. Please use this link in the mean time: https://discord.gg/NczTUTWyRr

Let me know if you have issues.

**Comment by jokob-sk** [comment]
Fixed, closing
