### ISSUE TITLE
Make "Last IP" clickable to access Webserver

### ISSUE THREAD

**Issue by AdmiralRaccoon** [jokob-sk/NetAlertX#856]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Just a convenience issue

### Describe the solution you'd like

Right now, I copy & paste the IP Adress manually into another browser window, however, it would be very useful if the IP was clickable to open a new browser windows within NetalertX itself to access the webserver (if any) from the device.

For non port 80 / 443 webserver, maybe there could be a custom field to be manually filled, which will be appended to the IP Adress.

Thanks and have a nice day,
Philipp

### Describe alternatives you've considered

Continuing copy and pasting the ip adress manually

### Anything else?

![image](https://github.com/user-attachments/assets/90310c2f-9d3b-4a31-82e2-fd8f11ecd97e)

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [ ] Yes
- [X] No

**Comment by jokob-sk** [comment]
Hi @AdmiralRaccoon ,

![Screenshot_20241021_214803](https://github.com/user-attachments/assets/f3fb7e25-2c33-49d6-990c-88604c6579c1)

This should be available in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now. 

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

⭐ Consider sharing the app on socials ⭐

Thanks in advance,
j

**Comment by jokob-sk** [comment]
Just FYI, if you enable the NMAP port scanner, the system will generate these links for individual ports: 
![image](https://github.com/user-attachments/assets/347429dd-d5fc-4382-9aea-d4924a6e106e)

**Comment by AdmiralRaccoon** [comment]
Hey, I´d really love to test, but this time I´m struggeling with the Dev Image as I can´t access the "My devices" page, as the "Loading" Button is circling for eternity.

I already created the dev config from scratch and used different browsers with cache clearing etc.

**Comment by jokob-sk** [comment]
Please make sure you clear the browser cache, app cache and if still not working check the browser error log.

**Comment by AdmiralRaccoon** [comment]
Well, I checked again now and it works again.
Also the clickable IP is working, thanks for that!

**Comment by jokob-sk** [comment]
releasing in 15 min -> closing
