### ISSUE TITLE
"Network" screen stuck on Loading

### ISSUE THREAD

**Issue by Metathesus** [jokob-sk/NetAlertX#857]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

"Network" screen stuck on "Loading"

- Cache cleared
- Container recreated with logs and config volume deleted  (only the db has been keeped)
- Error in in console browser (F12)

![Capture d’écran 2024-10-21 130451](https://github.com/user-attachments/assets/4c7cda33-b7fa-4282-9d71-37a51f6c83aa)
![Capture d’écran 2024-10-21 143650](https://github.com/user-attachments/assets/875f7e81-7f48-43d9-9a95-dd79ab208277)

### Expected Behavior

Network screen load correctly

### docker-compose.yml

```python
services:
  netalertx:
    container_name: netalertx 
    image: "jokobsk/netalertx:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - /mnt/Docker/netalertx/config:/app/config
      - /mnt/Docker/netalertx/db:/app/db      
      # (optional) useful for debugging if you have issues setting up the container
      - /mnt/Docker/netalertx/logs:/app/front/log
    environment:
      - TZ=Europe/Paris     
      - PORT=2480
```

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by Metathesus** [comment]
The parent node of internet was internet. How was it possible? I don't know because it was always greyed out...
I'have delete this device and has been recreatd automatically and now parent is "unknown" and all working well

**Comment by Metathesus** [comment]
Thanks for your help

**Comment by jokob-sk** [comment]
Great! Reopening for tracking, will close after next release

**Comment by jokob-sk** [comment]
releasing in 15 min -> closing
