### ISSUE TITLE
Multi-Site UNIFIMP for Importing Hosts in a Multi-Site Unifi Infrastructure

### ISSUE THREAD

**Issue by Disciplus86** [jokob-sk/NetAlertX#858]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Hi,

I have two sites, each with its own cloud key, but currently, UNIFIMP can only import one site.

### Describe the solution you'd like

 Do you think it’s possible to duplicate the UNIFIMP plugin to create a second or third UNIFIMP module (e.g., UNIFIMP1, UNIFIMP2)?

### Describe alternatives you've considered

What would be easier: modifying the existing module or duplicating it?

### Anything else?

nothing

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [X] Yes
- [ ] No

**Comment by jokob-sk** [comment]
Hi @Disciplus86,

The plugin should allow you to add multiple sites.

https://github.com/jokob-sk/NetAlertX/blob/05e4de0dc80f86c8ccc99a687a137875429b5d7e/front/plugins/unifi_import/script.py#L89

The code loops thru all sites and collects devices. Have you tried adding more sites in the setting UNIFI_SITES?

**Comment by jokob-sk** [comment]
If you have different log ins and or controllers you can potentially run multiple NAX instances and synchronize them with the sync plugin: https://github.com/jokob-sk/NetAlertX/tree/main/front/plugins/sync

**Comment by Disciplus86** [comment]
> Hi @Disciplus86,
> 
> The plugin should allow you to add multiple sites.
> 
> https://github.com/jokob-sk/NetAlertX/blob/05e4de0dc80f86c8ccc99a687a137875429b5d7e/front/plugins/unifi_import/script.py#L89
> 
> The code loops thru all sites and collects devices. Have you tried adding more sites in the setting UNIFI_SITES?

Hi @jokob-sk , 
It's 

> Hi @Disciplus86,
> 
> The plugin should allow you to add multiple sites.
> 
> https://github.com/jokob-sk/NetAlertX/blob/05e4de0dc80f86c8ccc99a687a137875429b5d7e/front/plugins/unifi_import/script.py#L89
> 
> The code loops thru all sites and collects devices. Have you tried adding more sites in the setting UNIFI_SITES?

No, i can't.
I have 2 controller (UNIFI_HOST) with one site :/

in the code :
c = Controller(UNIFI_HOST, UNIFI_USERNAME, UNIFI_PASSWORD, port=PORT, version=VERSION, ssl_verify=VERIFYSSL, site_id=site)

I will try to duplicate the plugin :/

**Comment by Disciplus86** [comment]
> If you have different log ins and or controllers you can potentially run multiple NAX instances and synchronize them with the sync plugin: https://github.com/jokob-sk/NetAlertX/tree/main/front/plugins/sync

Yes, i think is the most easier.

**Comment by jokob-sk** [comment]
Closing as resolved, will reopen if needed
