### ISSUE TITLE
Device with trunk link : several IP to 1 MAC address

### ISSUE THREAD

**Issue by biggranben** [jokob-sk/NetAlertX#859]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have a Proxmox server connected to my managed switch by a single ethernet interface in trunk mode. When I do an ARP scan on each subnet, the Proxmox host appears twice with the same MAC address but with different IPs, which triggers alerts : 
![image](https://github.com/user-attachments/assets/03cd2fd9-d0dc-48ad-9712-f0afdeb92f8f)

### Describe the solution you'd like

Assign multiple IP to one device (detect they are not on the same subnet)

### Describe alternatives you've considered

No

### Anything else?

No

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [ ] Yes
- [X] No

**Comment by jokob-sk** [comment]
Hi there,

This is problematic as the mac is used as a unique identifier so changing this is not feasible. Can you have a read through this thread?

https://github.com/jokob-sk/NetAlertX/issues/89

@corasaniti if you are around, have you managed to resolve the problem? 

Other alternatives are:

- disable notifications for the device
- exclude ip address from notifications

Check the docs for more details https://github.com/jokob-sk/NetAlertX/blob/main/docs/NOTIFICATIONS.md

**Comment by jokob-sk** [comment]
no reply for a week-> closing

**Comment by corasaniti** [comment]
@jokob-sk 
Hi, unfortunately I have not yet solved the problem described above, it remains for me.

PS
Hi, can you tell me what the padlock symbol in the IP column in version 24.10.31 indicates?
Thanks in advance

**Comment by jokob-sk** [comment]
Hi, it's the https link of the ip

**Comment by jokob-sk** [comment]
I'll think about it
