### ISSUE TITLE
Sort device in network overview

### ISSUE THREAD

**Issue by biggranben** [jokob-sk/NetAlertX#860]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Devices are not sorted in the network overview : nor by port, nor by Name : 
![image](https://github.com/user-attachments/assets/8490e8ec-9d0c-45d3-8a40-c75581ba88b9)

### Describe the solution you'd like

Add menu to sort by Port, by IP, by Name

### Describe alternatives you've considered

No

### Anything else?

No

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [ ] Yes
- [X] No

**Comment by jokob-sk** [comment]
Hi @biggranben ,

![image](https://github.com/user-attachments/assets/cab5eccf-84ad-4bdb-b722-1302d2ca0a7b)

This should be available in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first), in about 15 minutes (or after the last [action finishes](https://github.com/jokob-sk/NetAlertX/actions)) from now?

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

⭐ Consider becoming sharing the app on socials⭐

Thanks in advance,
j

**Comment by biggranben** [comment]
It works well for Alphabetical sorting ! 
Thank you !

**Comment by biggranben** [comment]
Next step : add the possibility to sort by ports or by IP.

**Comment by jokob-sk** [comment]
Thanks, I'll think about it. For now this is good enough.

**Comment by jokob-sk** [comment]
releasing in 15 min -> closing
