### ISSUE TITLE
New device notifications always show "name not found" but are found shortly after

### ISSUE THREAD

**Issue by nathang21** [jokob-sk/NetAlertX#870]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### Current Behavior

Almost always when the new device notifications fire, they show "name not found" which make them not very useful. I have multiple name resolution plugins enabled, and typically after the scans run most devices have a name. I have all of the relevant scans scheduled to run on the same internal as recommended, is there a way to wait for the scans/resolutions to finish before the publishers fire? From reading the docs I thought that is how it's supposed to work already, but in practice that is not my experience.

### Expected Behavior

Ideally the notification would wait until at least 1 round of name resolutions has been attempted by all plugins that run on the same schedule as when the device was detected, to make the notification more useful. 

### Steps To Reproduce

1. Delete all devices in database (or wait until a new device joins the network)
2. Wait for next scan interval (/15 min for most plugins)
3. Notice name not found on the device. 

### app.conf

```python
See email.
```

### docker-compose.yml

```python
services:
  netalertx:
    image: jokobsk/netalertx-dev:latest 
    pull_policy: always
    container_name: netalertx
    healthcheck:
      test: curl -f http://localhost:20211/ || exit 1
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 300s
    mem_limit: 2g
    shm_size: 2g
    cpu_shares: 768
    network_mode: host
    security_opt:
      - no-new-privileges:true
    restart: always # unless-stopped # no
    stop_grace_period: 2m
    logging:
      driver: json-file
      options:
        max-file: 3
        max-size: 100k
    volumes:
      - /volume2/docker/netalertx/config:/app/config   
      - /volume2/docker/netalertx/db:/app/db   
      - /volume2/docker/netalertx/logs:/app/front/log  
      - /volume2/docker/netalertx/config/resolv.conf:/etc/resolv.conf   # Enable Reverse DNS
    environment:
      - LOG_LEVEL='trace' # info #
      # Fix Permissions by following:
      # https://github.com/jokob-sk/NetAlertX/blob/main/docs/FILE_PERMISSIONS.md
      # https://amoklauf.ch/posts/synology/changeid/
      - PUID=1030 
      - PGID=100
      - HOST_USER_ID=1030
      - HOST_USER_GID=100
      - TZ=America/New_York
```

### What branch are you running?

Dev

### app.log

See email.

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @nathang21 ,

I checked your config and I see that name resolution plugins are configured to run on a schedule:

```python
# AVAHISCAN
#---------------------------
AVAHISCAN_RUN='schedule'

...

# NBTSCAN
#---------------------------
NBTSCAN_RUN='schedule'

...

# NSLOOKUP
#---------------------------
NSLOOKUP_RUN='schedule'

...


# PHOLUS
#---------------------------
PHOLUS_RUN='schedule'
...

```

The recommended value is `before_name_updates`. Could you please give this a go?

Thanks,
j

**Comment by jokob-sk** [comment]
Just realized it's not correctly stated in the description, will update that next.

**Comment by nathang21** [comment]
Thanks yeah the docs were a little unclear on that, but this makes sense now.

I updated it for AVAHISCAN, NBTSCAN, and NSLOOKUP.

It doesn't appear to be an option for PHOLUS, and based on the description it shouldn't be run too frequently anyways and I already have that schedule to only be once a day. 

Will report back a bit later.

**Comment by jokob-sk** [comment]
I'm also thinking about deprecating Pholus and just including the other name resolution services. They should have pretty much the same coverage with less of an impact on performance.

**Comment by nathang21** [comment]
Okay this definitely helped improved things, I cleared the DB as a test, and now some of the notifications have device names. While not all have them, i'm sure that is somewhat expected?

If so, we can go ahead and resolve this, changing that setting seems to do the trick.

--- 

Interesting about Pholus, I don't know much about the differences but between the different methods but i'm sure i'm well covered by the other plugins at this point.

**Comment by jokob-sk** [comment]
Thanks for the update @nathang21 ! There will be always a couple of devices where the name discovery fails, maybe a future plugin will resolve those names as well :) closing for now
