### ISSUE TITLE
[UI] Performance improvements / Stopping a scan in progress

### ISSUE THREAD

**Issue by kim3636** [jokob-sk/NetAlertX#875]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### The issue occurs in the following browsers. Select at least 2.

- [X] Firefox
- [ ] Chrome
- [X] Edge
- [ ] Safari (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### Current Behavior

i added NMAP plugin and enabaled it, since i have about 3330 machines, it is stuck on loading page whenever i try to access settings  and devices,  and i can't do anything. 

![image](https://github.com/user-attachments/assets/2a444e31-a8b6-4e0b-b1eb-712e87bfbebc)

### Expected Behavior

I want to know is there a way to speed up the prosess of scan or is there a way to stop it ?
![image](https://github.com/user-attachments/assets/d43682d8-4de0-4788-b472-f23a09fd2b07)

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi,

You can always restart the backend, but that can cause database inconsistencies, so proceed with cation and I recommend taking a backup. 

https://github.com/jokob-sk/NetAlertX/blob/main/docs/BACKUPS.md

You can restart the backend in Maintenance -> Logs -> Next to app.log -> Restart Server. 

An alternative is to restart the container.

Hope this helps,
j

**Comment by kim3636** [comment]
![image](https://github.com/user-attachments/assets/e9b027b9-2aaf-4d93-ac8d-ad323fb8b85a)
i still have to wait until the processes of the actual scan end. The page is still stuck on loading. It will be very useful if the execution of scans doesn't block us from continuing to use netalertx or maybe a solution to accelarate the process. Do you have any suggestions ?

**Comment by jokob-sk** [comment]
Hi,

Have you tried the suggestions I posted above?

1. You can restart the backend in Maintenance -> Logs -> Next to app.log -> Restart Server.
2. You can restart the container.

You can also configure timeouts on plugins or disable plugins you don't use. 

I don't currently plan to implement a way to cancel plugin scans but I might re-visit the request in the future as this is the first time such a request was brought up.

**Comment by jokob-sk** [comment]
Also a couple of questions on where the biggest impact is felt:

1. Is the application slow only on certain screens?
2. Is the application usable if a scan is not running?
3. What plugins do you have enabled?
4. What schedules do you have set?
5. Did you consider limiting the scan to a subset of devices to reduce the scan impact?

**Comment by jokob-sk** [comment]
Thanks for the details. I'll try to work towards improving the performance further, that being said, it will take time - I have to rework the middle layer of the application whilst preserving functionality, like sorting and filtering in tables, which is not easy if you nee dto load data asynchronously. 

In the mean time, until one app is able to handle more devices (I'll do my best, but 3000 is quite a number, so I can't promise anything) you can try setting up separate NetAlertX instances. I'd recommend not to have more than ~500 devices per instance. You can try 1000 and see how it performs. Please let me know what resources you allocated and number of devices so I know the real capability at the current state.

If it's OK I will tag you if I need to do some performance testing in the future. 

I personally use 3 approaches (you can pick any):

1. Manual: Stop the container, delete the container, the image, run docker compose up. 
2. Manual: Force pull `docker-compose up --pull always`
3. Manual with [Dockcheck](https://github.com/mag37/dockcheck)
4. Automated with [watchtower](https://github.com/containrrr/watchtower)

You can pick any, I personally use Watchtower to test the latest `netalertx-dev` build of NetAlertX. I use Dockcheck when I know I can mass-update containers and I have time fixing things if something breaks and I use the Manual approach if I want to fix one container that is currently broken, but I don't have much time.

**Comment by kim3636** [comment]
Hello, 
- right now , the VM has 8 GB of RAM, 4 Cpus and 30GB of disk space ( i have increased the RAM and cpus today). 

- Actually the approach that you proposed to restart the server or restart docker unfortunately didn't work , since the scan didn't stop and the pages are still blocked on loading. We actually did another approach. We copied the content of an old configuration backup file saved in the config directory ( with many others ) into the app.conf file , so we stored the old version of netalertx before the NMAP scan.

- As for the approach of connecting many instances, i dont' think it can work in our case, since we're discovering the network by snmp discovery, by retrieving the ARP cash of a core layer 3 switch, so it gives the inforamations of 3000 machines.

**Comment by jokob-sk** [comment]
I started working on improving the performance of the devices page - ordering, searching is still broken but the loading times should be better. 

This should be available in the next release. It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (⚠backup everything at first or start a new container ⚠), in about 15 minutes from now?

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

Thanks in advance,
j

**Comment by kim3636** [comment]
Hello, 
I was in school period so i didn't get the chance to continue the tests. 
Right now the devices listing page is working well, though i have to wait a certain ammount of time ( 20 seconds or more) to access it. And for now there is the snmp discovery and avahi scan going on every 30 minutes. But i didn't try to to launch many scans at the same time ( to test whether it blocks as always or not ). 

What other tests do you suggest ?

**Comment by kim3636** [comment]
Wanted to add that the settings screen is also stuck sometimes. 
I have another question also, is there a feature that can detect the network topology automatically ? without having to do it manually in the "Network" section

**Comment by jokob-sk** [comment]
Scans still work the same way, I mostly focused on UI performance improvements. 

Some plugins detect the network topology, although this data is not available everywhere (look at the Features column):  https://github.com/jokob-sk/NetAlertX/blob/main/front/plugins/README.md

**Comment by jokob-sk** [comment]
Releasing -> Closing
