### ISSUE TITLE
Email report shows HTML tag in first line of Datetime column

### ISSUE THREAD

**Issue by ozmule** [jokob-sk/NetAlertX#879]
< /td> shown in Datetime column on emailed (smtp) notification

![image](https://github.com/user-attachments/assets/27bccc2d-d71e-4642-bf55-2e33ef055cbd)

Built on: 2024-11-02 | Version: v24.10.31

**Comment by jokob-sk** [comment]
Hi,

Might be related to https://github.com/jokob-sk/NetAlertX/issues/432

What smtp provider are you using?

**Comment by ozmule** [comment]
Hi, 
it is a HCL Domino mail server which is behind [Scrollout F1](https://www.scrolloutf1.com/).

**Comment by jokob-sk** [comment]
Can you try a different SMTP server as a test, e.g. GMAIL?

https://github.com/jokob-sk/NetAlertX/blob/main/docs/SMTP.md

My current assumption is that the issue is caused by the mail server.

**Comment by ozmule** [comment]
Sorry for the delay I was away from home for work.

Some further information is that the issue only happens when there is more than 1 entry (see below images)

<img width="118" alt="{DE3577ED-EAFD-49A3-9482-ECBD55B457A5}" src="https://github.com/user-attachments/assets/ab7ea8c7-6315-4114-ae7a-f2b81a590d53">

<img width="96" alt="{40739A76-5606-4E8E-AB34-AA75CF4CB616}" src="https://github.com/user-attachments/assets/1f2413b5-e6ba-49e0-b728-a67589746aeb">

**Comment by ozmule** [comment]
I can confirm that this issue does not appear when going to HCL Domino server direct and bypassing the ScrolloutF1 appliance.

**Comment by jokob-sk** [comment]
Thanks @ozmule for confirming! That helps me and others to answer future questions.

**Comment by ozmule** [comment]
@jokob-sk thank you for your replies and ongoing efforts on this project.

**Comment by jokob-sk** [comment]
🙏🖤
