### ISSUE TITLE
Half of devices not detected?

### ISSUE THREAD

**Issue by To-Azamat** [jokob-sk/NetAlertX#881]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### The issue occurs in the following browsers. Select at least 2.

- [ ] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Safari (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### Current Behavior

Just starting with NetAlertX, not sure if this is a bug or just the way it works.
Half of devices in my network are not detected. I do not see any clear pattern: iPad is detected but iPhone is not, Synology NAS is detected but VMs running on it are not, AppleTV and AirPort AP not detected. Most interesting are two identical smart bulbs in two different rooms - one is detected and the other not. All devices are on same network. 
Loaded DB from Pihole to populate the list, but respective devices are always offline. 
Is there anything I can do about it?

### Expected Behavior

Online devices to show

### What branch are you running?

Production

**Comment by jokob-sk** [comment]
Hi @To-Azamat ,

The detection depends on your network setup as well. So for example, if you have extenders or vlans that will make detection more difficult. See this documentation for details: https://github.com/jokob-sk/NetAlertX/blob/main/docs/SUBNETS.md

Please also make sure you have the same scan interval for all device scanners set up, so the schedule for all plugins discovering devices should be the same.

**Comment by To-Azamat** [comment]
Nope, there is nothing too fancy. It is a wired Microtik as a router with 2 AirPorts as wi-fi APs on a single /24 network.
Checked logs and looks like ARP scan sees only half of the devices, no errors.
Let there be difficulties with wi-fi devices, but wired APs, PS4/5, Linux VMs are not detected as well.
Anyway thenk you for reply, I guess thats just the way it works )

**Comment by jokob-sk** [comment]
Hmmm, are there any commonalities between the undetected devices, such as the the AP they connect to?

You could try to complement the Arpscan with the NMAPDEV scanner.

**Comment by To-Azamat** [comment]
No, no pattern I can figure out.
VMs on Synology on a hosted network, Synology connected to router via switch. Switch, Synology detected, VMs are not.
APs connected directly to router, not detected.
All wi-fi devices connect through one of APs, some of them detected, some not. Quite strange.
Ok I will try NMAPDEV and report.

**Comment by To-Azamat** [comment]
It was totally my bad. I had eth0 instead of ovs_bond1 in settings.
If it did not work at all I'd check it right away, but as it worked in part I relaxed a bit )
Now all is working, thank you for the help!
Should I leave NMAPDEV enabled or disable it now?

**Comment by jokob-sk** [comment]
Glad to hear that it's working :) 

Up to you, NMAPDEV has better online presence discoverability for some devices, so if it doesn't impact the performance too much you can leave it on. 

Closing as resolved
