### ISSUE TITLE
No output received from the plugin "OMDSDN" - IndexError: list index out of range

### ISSUE THREAD

**Issue by YeloMelo95** [jokob-sk/NetAlertX#882]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### The issue occurs in the following browsers. Select at least 2.

- [ ] Firefox
- [X] Chrome
- [X] Edge
- [ ] Safari (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### Current Behavior

When running the Omada SDN plugin, a connection is successfully made and my devices populate in the logs, but an error message appears. Plugin successfully displays the 3 Omada devices and all clients in the logs but seems to fail afterwards.

### Expected Behavior

Plugin should update the device list successfully

### Steps To Reproduce

1. Enable OMDSDN plugin
2. Configure the settings
3. Run the plugin on a schedule or manually

### app.conf

```python
# General
#---------------------------
LOADED_PLUGINS=['ARPSCAN','CSVBCKP','DBCLNP','INTRNT','MAINT','NEWDEV','NSLOOKUP','NTFPRCS','AVAHISCAN','SETPWD','SYNC','VNDRPDT','WORKFLOWS','TELEGRAM','NMAP','SNMPDSC','OMDSDN']
LOADED_PLUGINS__metadata="                      {}\n                    "
SCAN_SUBNETS=['192.168.0.0/24','192.168.30.0/24','192.168.50.0/24','192.168.20.0/24','192.168.40.0/24']
SCAN_SUBNETS__metadata="                      {}\n                    "
LOG_LEVEL='trace'
LOG_LEVEL__metadata="                      {}\n                    "
TIMEZONE='America/Toronto'
TIMEZONE__metadata="                      {}\n                    "
PLUGINS_KEEP_HIST=250
PLUGINS_KEEP_HIST__metadata="                      {}\n                    "
REPORT_DASHBOARD_URL='http://netalertx'
REPORT_DASHBOARD_URL__metadata="                      {}\n                    "
DAYS_TO_KEEP_EVENTS=90
DAYS_TO_KEEP_EVENTS__metadata="                      {}\n                    "
HRS_TO_KEEP_NEWDEV=0
HRS_TO_KEEP_NEWDEV__metadata="                      {}\n                    "
HRS_TO_KEEP_OFFDEV=0
HRS_TO_KEEP_OFFDEV__metadata="                      {}\n                    "
CLEAR_NEW_FLAG=0
CLEAR_NEW_FLAG__metadata="                      {}\n                    "
API_CUSTOM_SQL='SELECT * FROM Devices WHERE devPresentLastScan = 0'
API_CUSTOM_SQL__metadata="                      {}\n                    "
VERSION='1731329435'
VERSION__metadata="                      {}\n                    "
NETWORK_DEVICE_TYPES=['AP','Gateway','Firewall','Hypervisor','Powerline','Switch','WLAN','PLC','Router','USB LAN Adapter','USB WIFI Adapter','Internet','NAS']
NETWORK_DEVICE_TYPES__metadata="                      {}\n                    "
GRAPHQL_PORT=20212
GRAPHQL_PORT__metadata="                      {}\n                    "
API_TOKEN=''
API_TOKEN__metadata="                      {}\n                    "

# OMDSDN
#---------------------------
OMDSDN_RUN='disabled'
OMDSDN_RUN__metadata="                      {\"function\": \"RUN\", \"events\": [\"run\"], \"type\": {\"dataType\": \"string\", \"elements\": [{\"elementType\": \"select\", \"elementOptions\": [], \"transformers\": []}]}, \"default_value\": \"disabled\", \"options\": [\"disabled\", \"once\", \"schedule\", \"always_after_scan\"], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"When to run\"}, {\"language_code\": \"es_es\", \"string\": \"Cu\\u00e1ndo ejecutar\"}, {\"language_code\": \"de_de\", \"string\": \"Wann laufen\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"When the scan should run. Good options are: <code>schedule</code>\"}]}\n                    "
OMDSDN_RUN_SCHD='*/5 * * * *'
OMDSDN_RUN_SCHD__metadata="                      {\"function\": \"RUN_SCHD\", \"type\": {\"dataType\": \"string\", \"elements\": [{\"elementType\": \"input\", \"elementOptions\": [], \"transformers\": []}]}, \"default_value\": \"*/5 * * * *\", \"options\": [], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"Schedule\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Only enabled if you select <code>schedule</code> in the <a href=\\\"#SYNC_RUN\\\"><code>SYNC_RUN</code> setting</a>. Make sure you enter the schedule in the correct cron-like format (e.g. validate at <a href=\\\"https://crontab.guru/\\\" target=\\\"_blank\\\">crontab.guru</a>). For example entering <code>0 4 * * *</code> will run the scan after 4 am in the <a onclick=\\\"toggleAllSettings()\\\" href=\\\"#TIMEZONE\\\"><code>TIMEZONE</code> you set above</a>. Will be run NEXT time the time passes.\"}, {\"language_code\": \"es_es\", \"string\": \"Solo est\\u00e1 habilitado si selecciona <code>schedule</code> en la configuraci\\u00f3n <a href=\\\"#SYNC_RUN\\\"><code>SYNC_RUN</code></a>. Aseg\\u00farese de ingresar la programaci\\u00f3n en el formato similar a cron correcto (por ejemplo, valide en <a href=\\\"https://crontab.guru/\\\" target=\\\"_blank\\\">crontab.guru</a>). Por ejemplo, ingresar <code>0 4 * * *</code> ejecutar\\u00e1 el escaneo despu\\u00e9s de las 4 a.m. en el <a onclick=\\\"toggleAllSettings()\\\" href=\\\"#TIMEZONE\\\"><code>TIMEZONE</ c\\u00f3digo> que configur\\u00f3 arriba</a>. Se ejecutar\\u00e1 la PR\\u00d3XIMA vez que pase el tiempo.\"}, {\"language_code\": \"de_de\", \"string\": \"Nur aktiviert, wenn Sie <code>schedule</code> in der <a href=\\\"#SYNC_RUN\\\"><code>SYNC_RUN</code>-Einstellung</a> ausw\\u00e4hlen. Stellen Sie sicher, dass Sie den Zeitplan im richtigen Cron-\\u00e4hnlichen Format eingeben (z. B. validieren unter <a href=\\\"https://crontab.guru/\\\" target=\\\"_blank\\\">crontab.guru</a>). Wenn Sie beispielsweise <code>0 4 * * *</code> eingeben, wird der Scan nach 4 Uhr morgens in der <a onclick=\\\"toggleAllSettings()\\\" href=\\\"#TIMEZONE\\\"><code>TIMEZONE</ ausgef\\u00fchrt. Code> den Sie oben festgelegt haben</a>. Wird das N\\u00c4CHSTE Mal ausgef\\u00fchrt, wenn die Zeit vergeht.\"}]}\n                    "
OMDSDN_url='http://192.168.0.199:8088'
OMDSDN_url__metadata="                      {\"function\": \"url\", \"type\": {\"dataType\": \"string\", \"elements\": [{\"elementType\": \"input\", \"elementOptions\": [], \"transformers\": []}]}, \"maxLength\": 50, \"default_value\": \"\", \"options\": [], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"URL\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Enter full URL with protocol <code>https://CHANGEME_omada.mylocaldomain:PORT</code>.\"}]}\n                    "
OMDSDN_sites=['##########']
OMDSDN_sites__metadata="                      {\"function\": \"sites\", \"type\": {\"dataType\": \"array\", \"elements\": [{\"elementType\": \"input\", \"elementOptions\": [{\"placeholder\": \"Enter value\"}, {\"suffix\": \"_in\"}, {\"cssClasses\": \"col-sm-10\"}, {\"prefillValue\": \"null\"}], \"transformers\": []}, {\"elementType\": \"button\", \"elementOptions\": [{\"sourceSuffixes\": [\"_in\"]}, {\"separator\": \"\"}, {\"cssClasses\": \"col-xs-12\"}, {\"onClick\": \"addList(this, false)\"}, {\"getStringKey\": \"Gen_Add\"}], \"transformers\": []}, {\"elementType\": \"select\", \"elementHasInputValue\": 1, \"elementOptions\": [{\"multiple\": \"true\"}, {\"readonly\": \"true\"}, {\"editable\": \"true\"}], \"transformers\": []}, {\"elementType\": \"button\", \"elementOptions\": [{\"sourceSuffixes\": []}, {\"separator\": \"\"}, {\"cssClasses\": \"col-xs-6\"}, {\"onClick\": \"removeAllOptions(this)\"}, {\"getStringKey\": \"Gen_Remove_All\"}], \"transformers\": []}, {\"elementType\": \"button\", \"elementOptions\": [{\"sourceSuffixes\": []}, {\"separator\": \"\"}, {\"cssClasses\": \"col-xs-6\"}, {\"onClick\": \"removeFromList(this)\"}, {\"getStringKey\": \"Gen_Remove_Last\"}], \"transformers\": []}]}, \"default_value\": [], \"options\": [], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"OMADA sites\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Omada SDN site IDs. For now, we only process the first site listed since NetAlertX's other probes won't traverse across NAT and routers. But if needed please submit an issue in github with your specific use case for consideration:  <code>https://github.com/jokob-sk/NetAlertX/issues </code> \"}]}\n                    "
OMDSDN_username='##########'
OMDSDN_username__metadata="                      {\"function\": \"username\", \"type\": {\"dataType\": \"string\", \"elements\": [{\"elementType\": \"input\", \"elementOptions\": [], \"transformers\": []}]}, \"maxLength\": 50, \"default_value\": \"\", \"options\": [], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"User name\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Omada SDN instance user name.\"}]}\n                    "
OMDSDN_password='##########'
OMDSDN_password__metadata="                      {\"function\": \"password\", \"type\": {\"dataType\": \"string\", \"elements\": [{\"elementType\": \"input\", \"elementOptions\": [{\"type\": \"password\"}], \"transformers\": []}]}, \"maxLength\": 50, \"default_value\": \"\", \"options\": [], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"Password\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Omada SDN instance password.\"}]}\n                    "
OMDSDN_force_overwrite=True
OMDSDN_force_overwrite__metadata="                      {\"function\": \"force_overwrite\", \"type\": {\"dataType\": \"boolean\", \"elements\": [{\"elementType\": \"input\", \"elementOptions\": [{\"type\": \"checkbox\"}], \"transformers\": []}]}, \"default_value\": false, \"options\": [], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"Force overwrite\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"The plugin synchronizes names from NetAlertX to OMADA Clients. By default NetAlertX will only populate missing names in OMADASDN devices (i.e.: where the name is defaulting to the device MAC address); with this setting toggled, it will overwrite existing values regardless.\"}]}\n                    "
OMDSDN_CMD='python3 /app/front/plugins/omada_sdn_imp/omada_sdn.py'
OMDSDN_CMD__metadata="                      {\"function\": \"CMD\", \"type\": {\"dataType\": \"string\", \"elements\": [{\"elementType\": \"input\", \"elementOptions\": [{\"readonly\": \"true\"}], \"transformers\": []}]}, \"default_value\": \"python3 /app/front/plugins/omada_sdn_imp/omada_sdn.py\", \"options\": [], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"Command\"}, {\"language_code\": \"es_es\", \"string\": \"Comando\"}, {\"language_code\": \"de_de\", \"string\": \"Befehl\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Command to run. This can not be changed\"}, {\"language_code\": \"es_es\", \"string\": \"Comando a ejecutar. Esto no se puede cambiar\"}, {\"language_code\": \"de_de\", \"string\": \"Befehl zum Ausf\\u00fchren. Dies kann nicht ge\\u00e4ndert werden\"}]}\n                    "
OMDSDN_RUN_TIMEOUT=30
OMDSDN_RUN_TIMEOUT__metadata="                      {\"function\": \"RUN_TIMEOUT\", \"type\": {\"dataType\": \"integer\", \"elements\": [{\"elementType\": \"input\", \"elementOptions\": [{\"type\": \"number\"}], \"transformers\": []}]}, \"default_value\": 30, \"options\": [], \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"Run timeout\"}, {\"language_code\": \"es_es\", \"string\": \"Tiempo l\\u00edmite de ejecuci\\u00f3n\"}, {\"language_code\": \"de_de\", \"string\": \"Zeit\\u00fcberschreitung\"}], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Maximum time in seconds to wait for the script to finish. If this time is exceeded the script is aborted.\"}, {\"language_code\": \"es_es\", \"string\": \"Tiempo m\\u00e1ximo en segundos para esperar a que finalice el script. Si se supera este tiempo, el script se cancela.\"}, {\"language_code\": \"de_de\", \"string\": \"Maximale Zeit in Sekunden, die auf den Abschluss des Skripts gewartet werden soll. Bei \\u00dcberschreitung dieser Zeit wird das Skript abgebrochen.\"}]}\n                    "
OMDSDN_WATCH=[]
OMDSDN_WATCH__metadata="                      {\"default_value\": [], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Send a notification if selected values change. Use <code>CTRL + Click</code> to select/deselect. <ul> <li><code>Watched_Value1</code> is Hostname </li><li><code>Watched_Value2</code> is Parent Node </li><li><code>Watched_Value3</code> is Port </li><li><code>Watched_Value4</code> is SSID </li></ul>\"}], \"function\": \"WATCH\", \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"Watched\"}, {\"language_code\": \"es_es\", \"string\": \"Visto\"}], \"options\": [\"Watched_Value1\", \"Watched_Value2\", \"Watched_Value3\", \"Watched_Value4\"], \"type\": {\"dataType\": \"array\", \"elements\": [{\"elementType\": \"select\", \"elementOptions\": [{\"multiple\": \"true\"}], \"transformers\": []}]}}\n                    "
OMDSDN_REPORT_ON=['new','watched-changed']
OMDSDN_REPORT_ON__metadata="                      {\"default_value\": [\"new\", \"watched-changed\"], \"description\": [{\"language_code\": \"en_us\", \"string\": \"Send a notification only on these statuses. <code>new</code> means a new unique (unique combination of PrimaryId and SecondaryId) object was discovered. <code>watched-changed</code> means that selected <code>Watched_ValueN</code> columns changed.\"}], \"function\": \"REPORT_ON\", \"localized\": [\"name\", \"description\"], \"name\": [{\"language_code\": \"en_us\", \"string\": \"Report on\"}], \"options\": [\"new\", \"watched-changed\", \"watched-not-changed\", \"missing-in-last-scan\"], \"type\": {\"dataType\": \"array\", \"elements\": [{\"elementType\": \"select\", \"elementOptions\": [{\"multiple\": \"true\"}], \"transformers\": []}]}}\n                    "
```

### What branch are you running?

Dev

### app.log

08:46:38 [2024-11-11 08:46:38-05:00] START Run: OMDSDN
08:46:38 [Plugins] Timeout: 30
08:46:38 [Plugin utils] Pre-Resolved CMD: python3/app/front/plugins/omada_sdn_imp/omada_sdn.py
08:46:38 [Plugins] Executing: python3 /app/front/plugins/omada_sdn_imp/omada_sdn.py
08:46:38 [Plugins] Resolved : ['python3', '/app/front/plugins/omada_sdn_imp/omada_sdn.py']
08:46:39 [OMDSDN] starting execution
08:46:39 [Database] Opening DB
08:46:39 [OMDSDN] callomada:-t myomada target --url http://192.168.0.199:8088 --user ###### --password ###### --site ###### --set-default
08:46:40 [OMDSDN] login to omada result is: Set target myomada to controller ###### and site ######

08:46:40 [OMDSDN] callomada:-t myomada clients
08:46:42 [OMDSDN] clients found:"71"

*** DEVICE LIST REDACTED ***

08:46:42 [OMDSDN] callomada:-t myomada devices
08:46:43 [OMDSDN] omada devices (switches, access points) found:"3" 
*** MAC ***           192.168.0.3      ap CONNECTED        BNET-LR-AP1          EAP245(Canada) v3.0
*** MAC ***           192.168.0.1 gateway CONNECTED        BNET-RACK-R1         ER605 v1.0
*** MAC ***           192.168.0.2  switch CONNECTED        BNET-RACK-SW1        TL-SG2008P v1.0

08:46:47 [OMDSDN] switches details collected "3"
08:46:47 [OMDSDN] dump details collected "3"
08:46:47 [OMDSDN] updating omada server because odevice_data is: "Microwave and naxname is: "wled-2b86dc"
08:46:47 [OMDSDN] updating omada server because odevice_data is: "BC-24-11-4A-1A-C1 and naxname is: "netalertx-docker"
08:46:47 [OMDSDN] updating omada server because odevice_data is: "Asustor and naxname is: "Asustor NAS"
08:46:47 [plugin_helper] reading config file
08:46:39 [OMDSDN] starting execution
08:46:39 [Database] Opening DB
08:46:39 [OMDSDN] callomada:-t myomada target --url http://192.168.0.199:8088 --user ###### --password ###### --site ###### --set-default
08:46:40 [OMDSDN] login to omada result is: Set target myomada to controller ###### and site ######

08:46:40 [OMDSDN] callomada:-t myomada clients
08:46:42 [OMDSDN] clients found:"71"

*** DEVICE LIST REDACTED ***

08:46:42 [OMDSDN] callomada:-t myomada devices
08:46:43 [OMDSDN] omada devices (switches, access points) found:"3" 
*** MAC ***            192.168.0.3      ap CONNECTED        BNET-LR-AP1          EAP245(Canada) v3.0
*** MAC ***            192.168.0.1 gateway CONNECTED        BNET-RACK-R1         ER605 v1.0
*** MAC ***            192.168.0.2  switch CONNECTED        BNET-RACK-SW1        TL-SG2008P v1.0

08:46:47 [OMDSDN] switches details collected "3"
08:46:47 [OMDSDN] dump details collected "3"
08:46:47 [OMDSDN] updating omada server because odevice_data is: "Microwave and naxname is: "wled-2b86dc"
08:46:47 [OMDSDN] updating omada server because odevice_data is: "BC-24-11-4A-1A-C1 and naxname is: "netalertx-docker"
08:46:47 [OMDSDN] updating omada server because odevice_data is: "Asustor and naxname is: "Asustor NAS"
Traceback (most recent call last):
  File "/app/front/plugins/omada_sdn_imp/omada_sdn.py", line 517, in <module>
    main()
  File "/app/front/plugins/omada_sdn_imp/omada_sdn.py", line 217, in main
    device_data = get_device_data(clients_list, switches_and_aps, device_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/front/plugins/omada_sdn_imp/omada_sdn.py", line 465, in get_device_data
    mightbeport = odevice_data[cPORT_SSID].lstrip('(')
                  ~~~~~~~~~~~~^^^^^^^^^^^^
IndexError: list index out of range

08:46:47 [Plugins] ⚠ ERROR - enable LOG_LEVEL=debug and check logs
08:46:47 [Plugins] No output received from the plugin "OMDSDN"
08:46:47 [2024-11-11 08:46:47-05:00] END Run: OMDSDN

### Debug enabled

- [x] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Another one to look at @FlyingToto if you have a chance. Not sure if duplicate. Thanks in advance for the help!

**Comment by FlyingToto** [comment]
@jokob-sk hey so I finaly got my pc running but for some reasons, my dev copy of nax fails to start...  
- I downloaded the latest copy from github 
- I kept my docker-compose.yml.ffsb42 and .env.omada.ffsfb42
- when I start the docker with:  "sudo docker-compose --env-file .env.omada.ffsb42  -f ./docker-compose.yml.ffsb42  up"

I get the following flask error:

![image](https://github.com/user-attachments/assets/a91c1d61-4850-47f7-85f3-f353ae9a9b72)

**Comment by jokob-sk** [comment]
Hi @FlyingToto ,

Hummm, was that an existing container or image?  You might need to delete all previous dev containers (maybe even production ones) of netalertx and also images. It's possible that your code is attaching to an existing image instead of building the image from scratch. flask was added a week or so, so you need to rebuild the image from scratch. in Docker, AFAIK, if there is an existing image, it's used, even if it's out of date.

Flask itself should be installed during build time, as it is here in the source code: https://github.com/jokob-sk/NetAlertX/blob/60492157d15d798c16879702e2a842ef843b219a/Dockerfile#L18

The docker-compose file differences shouldn't matter. 

Thanks for the help!

**Comment by FlyingToto** [comment]
I actually remove the whole NetAlextX folder when I do a resync to NetAlertX.$BACKUP_VERSION...  
these are the steps I follow... my data and config folders  are preserved but that wouldnt have any incidence on flask

how can I  clear the cache for the container itself? would changing the container-name do the trick?


`
```
savefolder=~/naxdev/NetAlertX.v7    # path to the latest backup versioned
cd ~/naxdev   
mv NetAlertX $savefolder            # backup current one to latest version
gh repo clone FlyingToto/NetAlertX  # sync my clone in github first then refresh locally 
cd NetAlertX
ln -s ../docker-compose.yml.ffsb42 .    # link my saved custom docker-compose
ln -s ../.env.omada.ffsb42 .            # link my saved custom env
cd front/plugins/omada_sdn_imp/
cp -p $savefolder/front/plugins/omada_sdn_imp/omada_sdn.py* .    # copy back my working latest copies... 
cp -p $savefolder/front/plugins/omada_sdn_imp/README.md .
cp -p $savefolder/front/plugins/omada_sdn_imp/omada_account_sample.png .
#cp -p $savefolder/front/plugins/omada_sdn_imp/testre.py .
cd ~/naxdev/NetAlertX
sudo docker-compose --env-file .env.omada.ffsb42  -f ./docker-compose.yml.ffsb42  up   # start and pray


```
`

**Comment by FlyingToto** [comment]
ok so... 

- I fixed that issue by removing all the images of containers not running using: `docker system prune -a`
- after that every got rebuilt from scratch including downloading flask...  

however, now I have a different error when trying to start the dev instance....
```
netalertxdev2 | 08:24:38 [Settings] ⚠ ERROR - JSONDecodeError or FileNotFoundError for file /app/front/api/table_settings.json
n

```
![image](https://github.com/user-attachments/assets/15ab16bb-2e3d-4216-a5dc-0d6adb189c9e)

**Comment by jokob-sk** [comment]
Hey @FlyingToto,

Can you please try to pull the latest code? I think I fixed this previously. The DB structure has changed and I missed something in the code.

Your code base shouldn't contain many (I think only one) references to the dev_sourcePlugin. I renamed it to dev_sourcePlugin.

Hopefully this works 🤞

**Comment by FlyingToto** [comment]
that did the trick!   now we are back in business.... I just have to remember how python work...

From https://github.com/jokob-sk/NetAlertX
 * [new branch]        main           -> upstream/main
 * [new tag]           23.01.14       -> 23.01.14

**Comment by FlyingToto** [comment]
I got a different error  again but I think it was because my dadatabase/configs were too old... so I had to reset everything from scratch and it is working again...  now I can try to play with it...

**Comment by jokob-sk** [comment]
Great to hear that! I know, still doing heavy modifications so lots of things are not yet how they are supposed to be.

**Comment by jokob-sk** [comment]
Thanks to @Leicas this should be available in the next release 🙏 It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first or, ideally spin up a **separate container with a separate db and config**)

Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.

Thanks in advance,
j

**Comment by FlyingToto** [comment]
@jokob-sk ,

1) did you already fix the default gateway logic in the plugin? 

according to my notes, my code  was doing this:
![image](https://github.com/user-attachments/assets/e1e18439-0833-4356-b5f4-3b53a5e7face)

but  according to the latest version from the repo:
(it does add extra checks for netmasks values as well which were not part of my file for some reasons)
![image](https://github.com/user-attachments/assets/e37a6fdf-587b-482a-8dbb-f64c0004b5aa)

**Comment by YeloMelo95** [comment]
> Thanks to @Leicas this should be available in the next release 🙏 It would be great if you could test this. Can you please switch to the `netalertx-dev` docker image (backup everything at first or, ideally spin up a **separate container with a separate db and config**)
> 
> Make sure you refresh your browser cache - and click the 🔄 refresh button in the top right corner.
> 
> Thanks in advance, j

I am still getting the same error running on the latest netalert-dev build (12-02); it looks like it connects and sees all devices correctly, but then it fails with this:

13:00:39 [OMDSDN] switches details collected "3"
13:00:39 [OMDSDN] dump details collected "3"
Traceback (most recent call last):
  File "/app/front/plugins/omada_sdn_imp/omada_sdn.py", line 517, in <module>
    main()
  File "/app/front/plugins/omada_sdn_imp/omada_sdn.py", line 217, in main
    device_data = get_device_data(clients_list, switches_and_aps, device_handler)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/front/plugins/omada_sdn_imp/omada_sdn.py", line 465, in get_device_data
    mightbeport = odevice_data[cPORT_SSID].lstrip('(')
                  ~~~~~~~~~~~~^^^^^^^^^^^^
IndexError: list index out of range

13:00:39 [Plugins] ⚠ ERROR - enable LOG_LEVEL=debug and check logs
13:00:39 [Plugins] No output received from the plugin "OMDSDN"
13:00:39 [2024-12-02 13:00:39-05:00] END Run: OMDSDN

**Comment by FlyingToto** [comment]
hum, that's an odd one, because it is just trying to parse one of the device record provided by the switch or access point... it might be another one of the omada  oddities...  which models of omada devices to you have exactly? it looks like it found 3 devices in total.

**Comment by jokob-sk** [comment]
Releasing -> Closing
