### ISSUE TITLE
Error when Starting NetAlertX server on Raspberry Pi 3 B+

### ISSUE THREAD

**Issue by mtinman** [jokob-sk/NetAlertX#884]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### The issue occurs in the following browsers. Select at least 2.

- [X] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Safari (unsupported) - PRs welcome
- [X] N/A - This is an issue with the backend

### Current Behavior

Ran install using WGET installation procedure, went well until startup, will post error log below.

### Expected Behavior

Thought it would work as RaspiOS is derivitive of Debian 12 (Bookworm).

### app.conf

```python
[INSTALL] 🚀 Starting app - navigate to your <server IP>:
17:19:24 [Settings] ⚠ ERROR - JSONDecodeError or FileNotFoundError for file /app/front/api/table_settings.json
17:19:24 [Settings] ⚠ ERROR - JSONDecodeError or FileNotFoundError for file /app/front/api/table_settings.json
17:19:24 [MAIN] Setting up ...
17:19:24 [conf.tz] Setting up ...
17:19:24 

17:19:24 The backend restarted (started). If this is unexpected check https://bit.ly/NetAlertX_debug for troubleshooting tips.
17:19:24 

17:19:24 Permissions check (All should be True)
17:19:24 ------------------------------------------------
17:19:24   /config/app.conf |  READ  | True
17:19:24   /config/app.conf |  WRITE | True
17:19:24   /db/app.db       |  READ  | True
17:19:24   /db/app.db       |  WRITE | True
17:19:24 ------------------------------------------------
17:19:24 [Setup] Attempting to fix permissions.
17:19:24 [Setup] Attempting to fix permissions.
17:19:24 [Database] Opening DB
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app//server/__main__.py", line 209, in <module>
    sys.exit(main())       
             ^^^^^^
  File "/app//server/__main__.py", line 76, in main
    db.upgradeDB()
  File "/app//server/database.py", line 226, in upgradeDB
    self.sql.execute(sql_copy_from_devices)
sqlite3.OperationalError: no such column: dev_Network_Node_MAC_ADDR
```

### What branch are you running?

Production

### app.log

17:19:24 [Settings] ⚠ ERROR - JSONDecodeError or FileNotFoundError for file /app/front/api/table_settings.json
17:19:24 [Settings] ⚠ ERROR - JSONDecodeError or FileNotFoundError for file /app/front/api/table_settings.json
17:19:24 [MAIN] Setting up ...
17:19:24 [conf.tz] Setting up ...
17:19:24 

17:19:24 The backend restarted (started). If this is unexpected check https://bit.ly/NetAlertX_debug for troubleshooting tips.
17:19:24 

17:19:24 Permissions check (All should be True)
17:19:24 ------------------------------------------------
17:19:24   /config/app.conf |  READ  | True
17:19:24   /config/app.conf |  WRITE | True
17:19:24   /db/app.db       |  READ  | True
17:19:24   /db/app.db       |  WRITE | True
17:19:24 ------------------------------------------------
17:19:24 [Setup] Attempting to fix permissions.
17:19:24 [Setup] Attempting to fix permissions.
17:19:24 [Database] Opening DB

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @mtinman ,

Can you try again - this should have been fixed. Just FYI, the current code is being heavily modified, so things will work partially or not at all in some cases. If you want a more stable experience, get an older version of the app from the releases section. You will need to modify the script a bit (not to use curl/wget, but the local files) to use the older code instead. 

Thanks,
j

**Comment by jokob-sk** [comment]
Sorry, I don't provide an uninstall script :/ deleting the created folders under /app/  will remove most of the application, however there might be lingering dependencies. These are installed via this script: https://github.com/jokob-sk/NetAlertX/blob/60492157d15d798c16879702e2a842ef843b219a/install/install_dependencies.debian.sh

Feel free to submit an uninstalls script via PR if interested.

**Comment by mtinman** [comment]
J,
Thanks for that, and I will get to it over the weekend, and get back to you on this. I'll attempt the older install script as advised, and report findings. I GREATLY appreciate the help, and will try to help in return.

**Comment by jokob-sk** [comment]
Releasing -> Closing
