### ISSUE TITLE
UI settings vanished

### ISSUE THREAD

**Issue by cyberbrix** [jokob-sk/NetAlertX#888]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### The issue occurs in the following browsers. Select at least 2.

- [X] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Safari (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### Current Behavior

I cannot locate the UI settings under Settings or Maintenance

### Expected Behavior

There used to be an option to modify the UI, select which columns were visible, etc

### docker-compose.yml

```python
Currently ignoring the following plugins:
plugins/csv_backup
plugins/dhcp_servers
plugins/pihole_scan
plugins/_publisher_apprise
plugins/_publisher_ntfy
plugins/ddns_update
plugins/internet_ip
plugins/internet_speedtest
plugins/_publisher_pushsafer
plugins/_publisher_webhook
plugins/website_monitor
plugins/dhcp_leases
plugins/unifi_import
plugins/_publisher_email
plugins/_publisher_mqtt
```

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @cyberbrix ,

I've tried to ignore the same plugins but the app still works.

![ezgif-2-c9e558c9fd](https://github.com/user-attachments/assets/22edae76-3f1c-4939-9f50-a6cadbb06674)

Could you please provide:

1. Browser console debug output on the Settings page?
2. Relevant app.log output?


I'd recommend you to keep the csv_backup plugin running, it's a last result backup option which might come in handy.

**Comment by jokob-sk** [comment]
No reply for a week -> closing
