### ISSUE TITLE
Link leads to nothing

### ISSUE THREAD

**Issue by vgdh** [jokob-sk/NetAlertX#893]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### The issue occurs in the following browsers. Select at least 2.

- [ ] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Safari (unsupported) - PRs welcome
- [ ] N/A - This is an issue with the backend

### Current Behavior

This plugin is to execute a Pholus (name discovery) on the local network [Read more in the docs.](https://github.com/jokob-sk/NetAlertX/tree/main/front/plugins/pholus_scan)
Link is broken

### Expected Behavior

correct link

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Hi @vgdh,

Pholus will be removed in the next version completely, so I'm removing links and documentation as we speak. See the upcoming release announcement for details, under plugins : https://github.com/jokob-sk/NetAlertX/issues/138

**Comment by jokob-sk** [comment]
Releasing -> Closing
