### ISSUE TITLE
Manage SSIDs with multiple APs

### ISSUE THREAD

**Issue by vince122** [jokob-sk/NetAlertX#897]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No problem

### Describe the solution you'd like

Would it be possible to improve the Network map against Wifi, like this :

I have multiple AP, each access point is broadcasting multiple SSID, which could be common to other access points

Like this :
SSID A : AP1, AP2, AP3
SSID B : AP1, AP3

Then, some network assets are connected to SSID A or SSID B, whatever the AP.

Would it be possible to improve the devices infos / network map to be able to display each network asset, connected to each SSID, whatever the AP behind this SSID ?

### Describe alternatives you've considered

I was thinking on creating a Dummy device, with the SSID associated

### Anything else?

Great tool :)

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [X] Yes
- [ ] No

**Comment by jokob-sk** [comment]
Hi @vince122 ,

thanks for the suggestion. Could you please sketch out a solution - not sure how this would look visually.

Thanks in advance!
PS. Not yet decided if I implement this - need to see the complexity of implementing this and the value.

**Comment by FlyingToto** [comment]
not sure how easy it would be but what about changing the curent view
from:
-  for wireless connections -> wifi symbol  then device name
- for wired connections -> ehternet port symbol overwritten with port number then device name

to:
-  for wireless connections -> wifi symbol , then SSID, then device name
- for wired connections -> ehternet port symbol, then with port number then device name


![image](https://github.com/user-attachments/assets/f93ae4a6-b832-4959-8f56-16e21aeb6233)

**Comment by jokob-sk** [comment]
Thanks @FlyingToto - it's not difficult, just thinking that this would stretch the width of the diagram even more. Trying to figure out if that's an issue - like should I reduce the width or height to display information better. Maybe I'm overthinking it...

**Comment by jokob-sk** [comment]
no reply from OP (@vince122) on implementation details - closing for now
