### ISSUE TITLE
Customize webhook notifications

### ISSUE THREAD

**Issue by Strux-DK** [jokob-sk/NetAlertX#906]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Webhook notifications are rather large text-wise and gives (me, personally) a lot of information i don't need.
For example:
`Report Date: 2024-12-05 00:55
Server:      docker-reports

⚡ Events
---------
MAC:         aa:bb:cc:dd:ee:ff
Datetime:     2024-12-05 00:55:50+01:00
IP:         192.168.1.254
Event Type:     Down Reconnected
Device name:     TP-Link Switch
Comments:     Model: TL-SG1016PE`
I would probably just change to:
`Device TP-Link Switch has changed status to Down`

### Describe the solution you'd like

It would be nice with the possibility of customizing the webhook notifications with the information each user needs and maybe also how it is formatted/shwon when sent.

### Describe alternatives you've considered

I tried searching for custom plugins others have made, because i'm not much of a developer, but haven't been able to find any. I also considered trying to modify the webhook script, but again, i'm not much of a developer and would probably break something.

### Anything else?

Yes, it could be nice to also implement some sort of debug log of the information that the application is getting from all the devices. Specifically, my switch is flapping up and down a couple of times per day, according to your application, but there are no other indications of anything wrong. I already opened an issue about it and you wrote you can't do much about it, which i understand and respect, but it would be nice to see the information it is gathering to do some troubleshooting myself.
I really love this application and the work you do. Keep it up!

PS: I was a little unsure about the last question "Can i implement this?". Yes, i would love to help you all i can, but again, i'm not a developer and do not have much experience with this.

### Am I willing to test this? 🧪

- [X] I will do my best to test this feature on the `netlertx-dev` image when requested within 48h and report bugs to help deliver a great user experience for everyone and not to break existing installations.

### Can I help implement this? 👩‍💻👨‍💻

- [ ] Yes
- [X] No

**Comment by Strux-DK** [comment]
Oh, sorry. I have no idea how webhooks work, i just thought that the message (in my case, in Discord) must get the data from somewhere and that the developer must provide it with that data. So the developer must be able to decide what information is passed to the webhook message. But i'm probably wrong.

I looked at n8n and it seems like a universe in and of itself, so i'll keep it as-is for now and maybe i'll see if i can find some middleware to make it do exactly what i want.

Thanks!

**Comment by jokob-sk** [comment]
It's certainly possible, but similar to my responses here, I don't see an easy way to achieve this: https://github.com/jokob-sk/NetAlertX/issues/727

It's also more of an nice to have and I don't consider it missing core functionality. There is already 80+ notification gateways and a handful of native gateways. So  I think there's plenty of choice. 

If a feature is too complex to implement or causes too much maintenance in the future, I don't see too much value implementing it. I rather spend more time on core functionality.

Also FYI you can turn on debug mode and all plugin data can be found under Integrations - > Plugins.

Hope that makes sense,
J

**Comment by jokob-sk** [comment]
Leaving in backlog
