### ISSUE TITLE
NMAP plugin dev branch

### ISSUE THREAD

**Issue by antoninchadima** [jokob-sk/NetAlertX#913]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues and I checked the docs https://github.com/jokob-sk/NetAlertX/tree/main/docs

### The issue occurs in the following browsers. Select at least 2.

- [ ] Firefox
- [ ] Chrome
- [ ] Edge
- [ ] Safari (unsupported) - PRs welcome
- [X] N/A - This is an issue with the backend

### Current Behavior

```
06:50:00 [Plugin utils] Pre-Resolved CMD: python3/app/front/plugins/nmap_scan/script.pyips={ips}macs={macs}timeout={timeout}args={args}
06:50:00 [Plugins] Executing: python3 /app/front/plugins/nmap_scan/script.py ips={ips} macs={macs} timeout={timeout} args={args}
06:50:00 [Plugins] Resolved : ['python3', '/app/front/plugins/nmap_scan/script.py', 'ips=172.18.2.68,172.18.2.192,172.18.2.55,172.18.2.137,172.18.3.166,172.18.2.218,172.18.3.140,172.18.3.37,172.18.3.218,172.18.0.1,172.18.0.2,147.231.81.33', 'macs=00:bf:69:84:5c:06,0e:37:45:45:a3:ba,22:63:22:8a:6f:38,3a:f6:b2:21:ee:4c,5c:80:b6:f3:3b:bc,76:45:54:df:37:f7,82:13:c5:38:13:9b,84:b8:b8:ad:17:d3,a0:57:e3:58:b8:26,bc:24:11:88:89:2b,bc:24:11:93:c8:ba,Internet', 'timeout=30', "args=b'LUEgLVQ0'"]
06:50:00   File "/app/front/plugins/nmap_scan/script.py", line 165
    mylog('verbose', [ff'[{pluginName}] {newPortsPerDevice} ports found on {deviceMACs[devIndex]}'])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax
```

### Expected Behavior

no error

### Steps To Reproduce

1. clean install
2. enable NMAP plugin
3. run NMAP plugin

### What branch are you running?

Production

### Debug enabled

- [X] I have read and followed the steps in the wiki link above and provided the required debug logs and the log section covers the time when the issue occurs.

**Comment by jokob-sk** [comment]
Thanks for the report @antoninchadima! Fix will be in the dev image in ~15 min.

**Comment by antoninchadima** [comment]
:+1: 
fixed
