### ISSUE TITLE
Trying to add my own network types device

### ISSUE THREAD

**Issue by bakka5** [jokob-sk/NetAlertX#924]
I’m adding my own network type devices. It shows up in the list in the settings, but it does not show up in the list when you’re trying to assign them to different devices on your network I’ve tried restarting the server that it’s on. I’ve tried restarting just a docker instance of it and nothing seems to work. I’m not sure if I’m doing it correctly. I’ve even gone into the config file to make sure that it was added to the config file it which it is, but it still does not show up in the list when you assign them to devices on your network.

**Comment by jokob-sk** [comment]
Hi @bakka5 ,

Did you add the same type on the device and setting?
![image](https://github.com/user-attachments/assets/8546226c-ce3e-4fde-81ac-0614d9f18c9f)
![image](https://github.com/user-attachments/assets/730b16ee-aa4e-43dd-833d-e9997216bf6f)
![image](https://github.com/user-attachments/assets/deb00226-695e-4a87-8c46-7b483045cc6d)

**Comment by bakka5** [comment]
Thank you that worked

**Comment by jokob-sk** [comment]
glad to hear that -> closing
